### PR TITLE
fix(codegen): preserve coverage comments before object properties

### LINKED ISSUE #21302: codegen: preserve coverage comments before `ObjectExpression`'s `properties[]`
Similar request as

- https://github.com/oxc-project/oxc/issues/21301

#### Input:

```js
const obj = {
    a: () => 1,
    /* v8 ignore next */
    b: () => 2,
}
```

#### Expected output:

```js
const obj = {
    a: () => 1,
    /* v8 ignore next */
    b: () => 2,
}
```

#### Actual output

```js
const obj = {
    a: () => 1,
    b: () => 2,
}
```

#### Reproduction

[https://playground.oxc.rs/?t=ast&options=%7B%22run...](https://playground.oxc.rs/?options=%7B%22run%22%3A%7B%22lint%22%3Atrue%2C%22formatter%22%3Afalse%2C%22transform%22%3Afalse%2C%22isolatedDeclarations%22%3Afalse%2C%22whitespace%22%3Afalse%2C%22mangle%22%3Afalse%2C%22compress%22%3Afalse%2C%22scope%22%3Atrue%2C%22symbol%22%3Atrue%2C%22cfg%22%3Afalse%7D%2C%22parser%22%3A%7B%22extension%22%3A%22tsx%22%2C%22allowReturnOutsideFunction%22%3Atrue%2C%22preserveParens%22%3Atrue%2C%22allowV8Intrinsics%22%3Atrue%2C%22semanticErrors%22%3Atrue%7D%2C%22linter%22%3A%7B%7D%2C%22formatter%22%3A%7B%22useTabs%22%3Afalse%2C%22tabWidth%22%3A2%2C%22endOfLine%22%3A%22lf%22%2C%22printWidth%22%3A80%2C%22singleQuote%22%3Afalse%2C%22jsxSingleQuote%22%3Afalse%2C%22quoteProps%22%3A%22as-needed%22%2C%22trailingComma%22%3A%22all%22%2C%22semi%22%3Atrue%2C%22arrowParens%22%3A%22always%22%2C%22bracketSpacing%22%3Atrue%2C%22bracketSameLine%22%3Afalse%2C%22objectWrap%22%3A%22preserve%22%2C%22singleAttributePerLine%22%3Afalse%7D%2C%22transformer%22%3A%7B%22target%22%3A%22es2015%22%2C%22useDefineForClassFields%22%3Atrue%2C%22experimentalDecorators%22%3Atrue%2C%22emitDecoratorMetadata%22%3Atrue%7D%2C%22isolatedDeclarations%22%3A%7B%22stripInternal%22%3Afalse%7D%2C%22codegen%22%3A%7B%22normal%22%3Atrue%2C%22jsdoc%22%3Atrue%2C%22annotation%22%3Atrue%2C%22legal%22%3Atrue%7D%2C%22compress%22%3A%7B%7D%2C%22mangle%22%3A%7B%22topLevel%22%3Atrue%2C%22keepNames%22%3Afalse%7D%2C%22controlFlow%22%3A%7B%22verbose%22%3Afalse%7D%2C%22inject%22%3A%7B%22inject%22%3A%7B%7D%7D%2C%22define%22%3A%7B%22define%22%3A%7B%7D%7D%7D&code=const+obj+%3D+%7B%0A++++a%3A+%28%29+%3D%3E+1%2C%0A++++%2F*+v8+ignore+next+*%2F%0A++++b%3A+%28%29+%3D%3E+2%2C%0A%7D%0A#eNptU01v2zAM/SuGLv1AtnYFBhTZaWgXYEC3ZuuwXnKhZcZRKoseRecDQf77KCdyuqG5RH4UyfceqZ2xZmyEt8VuFgr9WQqRPL73VJ+fCUY5u/g0C/tZsCB2UZwj80VxdVmsbgtXB2IsAm6kuLz6v4BeJO6vp3wzMmTGO8NdSH/eBTFj4Q5HZk7cgAiyGc/BR0WEIcQED4jTkiBY3aP1wCBOmwzB9cIp0RYsDlADofanT0tNyxhPKdFSq+EDgbhtSvL5y87r47X9yLTAMRHbGRWJIWrfZFfcqB7wntY/UToOj51EV+GkCzZRy6VST+QVToE1N6N93u/br0HYaUU7BCIqbXH2S3LuiCqH5FXPQc+vvNqZLuIvKE+iBMpnV8nCjG9GBkP1OH9wQVUaP1e6rXaTY/z2Wru5ZNGPjuTk0zJunt6A/6SvKVOrvQzEdwGxwkpr6qCc0qvvqGkgxbxXVHW4QaxqWWf9Gl/DNuqVksG+oDzp0DQ9X84oNHhgfuxP5RKtPDO0WiObmhr1XD+LGll2yhD5nzTctMiuwSDgH/UIQjyl6A4jSg4ZtXRYtoOpAlyj7qbBeHP94aN2UZvvca6FJ8R3HmKcOPTVMLXXXXQ9qW9zijZOBvQbClQg6tRxtG+v9c5EVdTqgiAH0MXM22ipwhr7B6Qvr0mhQ5dlrEjf8dHyEEj6WhnxWOe7fZX8GNJG5Zeiyql9wBUORV8Q2+86irxgfaouLfmJLnDKWCGXFLPhSU9Ig0qh4bRXuOrtS/Bw2ic82Zw17f8Cm3Oc3Q==)

Mentioned in issue below (cc. @marzelc, @saskliutas)
- https://github.com/oxc-project/oxc/issues/20549#issuecomment-4098069149

### PR DESCRIPTION
**Pull request by babu-ch**
Closes #21302

### CODE REVIEW

File: apps/oxlint/src-js/generated/deserialize.js [hunk 1]
```diff
@@ -21,6 +21,7 @@ for (let i = 0; i <= 64; i++) stringDecodeArrays[i] = Array(i).fill(0);
 
 const NodeProto = Object.create(Object.prototype, {
   loc: {
+    // Note: Not configurable
```
Comment (camc314) [inline apps/oxlint/src-js/generated/deserialize.js]: can you revert these additions? looks unrelated

Comment (babu-ch) [reply apps/oxlint/src-js/generated/deserialize.js]: This diff is a side effect of the codegen change itself. The AST tools use `oxc_codegen` to emit the generated JS, and the templates in `crates/oxc_ast/src/serialize/ts.rs` already contain these comments — they were just being stripped before.

We could narrow the fix to annotation comments only (via `is_annotation()`) to avoid this cascade, but the existing fixes for `SwitchCase` and `ConditionalExpression` alternate (#20718) also preserve all comments without filtering. Adding a filter here would break that consistency.

Which direction do you prefer: keep it consistent with the existing fixes (current PR), or narrow this one to annotation comments only?

Comment (camc314) [reply apps/oxlint/src-js/generated/deserialize.js]: Ah i see, ignore me - I forgot codegen was run on this code

**Review by Dunqing — APPROVED** [review]
Thank you!
