### PR TITLE
fix(ast): replace ArrayElementType

### LINKED ISSUE #325: bug(ast): ArrayExpression element should not be `Argument`
The correct ArrayExpressionElement type should be the following from jsparagus, the current type `Argument`, which is wrong.

```rust
#[derive(Debug, PartialEq)]
pub enum ArrayExpressionElement<'alloc> {
    SpreadElement(arena::Box<'alloc, Expression<'alloc>>),
    Expression(arena::Box<'alloc, Expression<'alloc>>),
    Elision {
        loc: SourceLocation,
    },
}
```

Action:

Add a `ArrayExpressionElement` for `ArrayExpression`

```rust
#[derive(Debug, PartialEq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize), serde(untagged))]
pub enum ArrayExpressionElement<'a> {
    SpreadElement(Box<'a, SpreadElement<'a>>),
    Expression(Expression<'a>),
    Elision(Span)
}

```

Change

```rust
#[derive(Debug, PartialEq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize), serde(tag = "type"))]
pub struct ArrayExpression<'a> {
    #[cfg_attr(feature = "serde", serde(flatten))]
    pub span: Span,
    pub elements: Vec<'a, ArrayExpressionElement<'a>>,
    pub trailing_comma: Option<Span>,
}

```

### PR DESCRIPTION
**Pull request by mysteryven**
fix: #325 

Not ready for review. I draft it to test CI and will check it in more detail.

`cargo coverage` passed now, but I am not really sure if I should write more test cases for this PR.

### CODE REVIEW

File: crates/oxc_parser/src/js/grammar.rs [hunk 1]
```diff
@@ -71,25 +71,22 @@ impl<'a> CoverGrammar<'a, ArrayExpression<'a>> for ArrayAssignmentTarget<'a> {
...
+                        if let Some(span) = expr.trailing_comma {
+                            p.error(diagnostics::RestElementTrailingComma(span));
                         }
+                    } else {
+                        return Err(diagnostics::SpreadLastElement(elem.span).into());
                     }
                 }
-            } else {
-                elements.push(None);
+                ArrayExpressionElement::Elision(_) => elements.push(None),
```
Comment (mysteryven) [inline crates/oxc_parser/src/js/grammar.rs:89]: Keep same with [jsparagus](https://github.com/mozilla-spidermonkey/jsparagus/blob/212f6bdbc2cae909e7d5cfebf36284560c3c4ef4/crates/generated_parser/src/ast_builder.rs#L1983).

**Comment by Boshen** [comment]
> cargo coverage passed now, but I am not really sure if I should write more test cases for this PR.

`cargo coverage` covers everything, there is no need to create standalone tests (unless it's a fuzzing test).

Besides this, is this PR ready from your side?

**Review by Boshen — APPROVED** [review]
