### PR TITLE
fix(parser): terminate parsing if an EmptyParenthesizedExpression error occurs

### LINKED ISSUE #1870: EmptyParenthesizedExpression should generate non-recoverable error
EmptyParenthesizedExpression should generate a non-recoverable error since when it happens, the ast is no longer valid.

### PR DESCRIPTION
**Pull request by Dunqing**
close: https://github.com/oxc-project/oxc/issues/1870#issue-2061901976

### CODE REVIEW

**Comment by Dunqing** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1874** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1874?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1874?utm_source=stack-comment).

File: crates/oxc_parser/src/js/expression.rs [hunk 1]
```diff
@@ -202,13 +202,14 @@ impl<'a> Parser<'a> {
         let mut expressions = list.elements;
         let paren_span = self.end_span(span);
 
+        if expressions.is_empty() {
```
Comment (u9g) [inline crates/oxc_parser/src/js/expression.rs:205]: why did you move this diagnostic up?

Comment (Dunqing) [reply crates/oxc_parser/src/js/expression.rs:205]: Because if the expression is empty we need to return the diagnostic. So we don't neet to check `expression.len() == 1`

**Review by Boshen — APPROVED** [review]
This is producing better parser diagnostics 👍
