### PR TITLE
fix(transformer/legacy-decorator): abstract class doesn't work in metadata

### LINKED ISSUE #10926: TS decorator metadata is not applied to abstract classes
Hello!

I found an issue where TS (legacy) decorator metadata is not applied to abstract classes.

### Reproduction: 

- Clone https://github.com/zsilbi/oxc-transform-repro
- Install dependencies
- Run: `node run-repro.js` 

### Provided input
```ts
// src/index.ts

function MyTSClassDecorator() {
  return (target: unknown) => {
    console.log("MyTSClassDecorator called");
  };
}

class Dependency {}

@MyTSClassDecorator()
export class RegularClass {
  constructor(dependency: Dependency) {}
}

@MyTSClassDecorator()
export abstract class AbstractClass {
  constructor(dependency: Dependency) {}
}
```

### Transformed output
```ts
import _decorateMetadata from "@oxc-project/runtime/helpers/decorateMetadata";
import _decorate from "@oxc-project/runtime/helpers/decorate";
var _ref;
function MyTSClassDecorator() {
        return (target) => {
                console.log("MyTSClassDecorator called");
        };
}
class Dependency {}
let RegularClass = class RegularClass {
        constructor(dependency) {}
};
RegularClass = _decorate([MyTSClassDecorator(), _decorateMetadata("design:paramtypes", [typeof (_ref = typeof Dependency !== "undefined" && Dependency) === "function" ? _ref : Object])], RegularClass);
export { RegularClass };
let AbstractClass = class AbstractClass {
        constructor(dependency) {}
};
AbstractClass = _decorate([MyTSClassDecorator()], AbstractClass);
export { AbstractClass };
```

### Expected output

`AbstractClass` should be also decorated with the same metadata as `RegularClass`

### Versions
oxc -transform v0.68.1
Ubuntu / Node v23.9.0

### PR DESCRIPTION
**Pull request by Dunqing**
close: #10926

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#10952** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/10952?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/10952?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=10952).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: tasks/transform_conformance/tests/legacy-decorators/test/fixtures/oxc/metadata/abstrct-class/input.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+import { dce, type Dependency } from "mod";
```
Comment (zsilbi) [inline tasks/transform_conformance/tests/legacy-decorators/test/fixtures/oxc/metadata/abstrct-class/input.ts:1]: `Dependency` should not be imported as a `type` in order to resolve the correct `paramtype` during runtime. 

When it's imported as a `type` the `paramtype` will be always `Object` (it should be `Dependecy`)

_(Folder name has a typo, an `a` is missing: `abstrct-class`)_

Comment (Dunqing) [reply tasks/transform_conformance/tests/legacy-decorators/test/fixtures/oxc/metadata/abstrct-class/input.ts]: Thank you for reviewing this! I mainly want to test whether `abstract class` can correctly generate metadata, so there's no need to worry about what `paramtype` is like—but a meaningful test would be very useful!

**Comment by Boshen** [comment]
### Merge activity

* **May 12, 9:11 AM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **May 12, 9:11 AM EDT**: `Boshen` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
