### PR TITLE
fix(oxlint): don't search for nested config outside base config

### LINKED ISSUE #20904: linter: .oxlintrc.json in parent directory overrides config in current directory
### What version of Oxlint are you using?

1.58.0

### What command did you run?

`../node_modules/.bin/oxlint bug-test.ts`

### Root:

```jsonc
{
  "$schema": "node_modules/oxlint/configuration_schema.json",
  "plugins": ["typescript"],
  "rules": {
    "typescript/no-explicit-any": "error"
  }
}
```

### `tests` directory:

```jsonc
{
  "$schema": "node_modules/oxlint/configuration_schema.json",
  "plugins": ["typescript"],
  "rules": {
    "eslint/no-unused-vars": "off",
    "typescript/no-explicit-any": "off"
  }
}
```

### What happened?

In the `tests` directory under the project root, linted the file `bug-test.ts`:

```typescript
const ab: any = 2;
```

I expected that, based on the nested `.oxlintrc.json`, no lints would be output. Instead:

```
> ../node_modules/.bin/oxlint bug-test.ts

  ⚠ eslint(no-unused-vars): Variable 'ab' is declared but never used. Unused variables should start with a '_'.
   ╭─[bug-test.ts:1:7]
 1 │ const ab: any = 2;
   ·       ─┬
   ·        ╰── 'ab' is declared here
   ╰────
  help: Consider removing this declaration.

  × typescript-eslint(no-explicit-any): Unexpected `any`. Specify a different type.
   ╭─[bug-test.ts:1:11]
 1 │ const ab: any = 2;
   ·           ───
   ╰────
  help: Use `unknown` instead, this will force you to explicitly, and safely, assert the type is correct.

Found 1 warning and 1 error.
Finished in 26ms on 1 file using 10 threads.
```

Removing the .oxlintrc.json in the parent directory results in the expected behaviour, as does reverting to 1.57.0.

```
> ../node_modules/.bin/oxlint bug-test.ts
Found 0 warnings and 0 errors.
Finished in 4ms on 1 file with 66 rules using 10 threads.
```

Curiously, the bug also does not manifest if you run oxlint from the parent directory, but it also does not print the number of rules evaluated:

```
> node_modules/.bin/oxlint tests/bug-test.ts 
Found 0 warnings and 0 errors.
Finished in 4ms on 1 file using 10 threads.
```

### LINKED ISSUE #21030: linter: Nested config discovery: child config rule overrides not applied at lint time (but --print-config shows correct merged value)
### What version of Oxlint are you using?

1.58.0

### What command did you run?

_No response_

### What happened?

When a child directory has its own `oxlint.config.ts` that overrides a rule from a parent config (e.g., sets `eslint/no-console` to `"off"`), the override is **not applied during linting** — the parent's `"error"` setting still takes effect. However, `--print-config` correctly shows the merged result as `"allow"`.

This indicates a discrepancy between config resolution in `--print-config` and the actual lint execution path.

## Reproduction

**Repo:** https://github.com/YKDZ/oxlint-nested-config-repro

```
oxlint.config.ts          # "eslint/no-console": "error"
child/
  oxlint.config.ts        # "eslint/no-console": "off"
  test.ts                 # console.log("hello");
```

```bash
git clone https://github.com/YKDZ/oxlint-nested-config-repro.git
cd oxlint-nested-config-repro
npm install

# ❌ BUG: reports 1 error (no-console), child override not applied
npm run test:bug

# ✅ Workaround: 0 errors — disabling nested discovery + using extends works
npm run test:workaround

# Shows no-console: "allow" — config merging is correct here
npm run test:print-config
```

### Variant: with explicit `extends`

The same bug occurs when the child config uses `extends: [rootConfig]`:

```ts
// child/oxlint.config.ts
import { defineConfig } from "oxlint";
import rootConfig from "../oxlint.config.ts";
export default defineConfig({
  extends: [rootConfig],
  rules: {
    "eslint/no-console": "off",
  },
});
```

In both cases (with or without `extends`), the child's `"off"` is ignored at runtime.

## Expected Behavior

Running `oxlint` from `child/` should apply the child config's `"eslint/no-console": "off"`, resulting in **0 errors**. This matches what `--print-config` reports.

## Actual Behavior

Running `oxlint` from `child/` reports a `no-console` error, as if the parent config's `"error"` takes final precedence. `--print-config` shows `"allow"` (correct merged value) but the linter does not honor it.

## Workaround

Using `--disable-nested-config` and relying on explicit `extends: [rootConfig]` in the child config produces the correct behavior (0 errors).

## Environment

- **oxlint**: 1.58.0
- **Node.js**: v24.x
- **OS**: Debian 12 (bookworm) / Linux

### PR DESCRIPTION
**Pull request by Sysix**
Fixes https://github.com/oxc-project/oxc/issues/21030, Fixes https://github.com/oxc-project/oxc/issues/20904, Obsoletes https://github.com/oxc-project/oxc/pull/21041

Nested config search did include the configs outside the current working directory. Resolving the config did find first the nested config outside the `cwd`, before falling back to the base config.

### CODE REVIEW

**Comment by Sysix** [comment]
* **#21055** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/21055?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#21051** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/21051?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/21051?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#21050** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/21050?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent changes, fast-track this PR to the front of the merge queue

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=21051).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: apps/oxlint/src/config_loader.rs [hunk 1]
```diff
@@ -57,6 +58,10 @@ pub fn discover_configs_in_ancestors<P: AsRef<Path>>(
         // Start from the file's parent directory and walk up the tree
         let mut current = path.parent();
         while let Some(dir) = current {
+            if dir == cwd {
+                // Stop if we've reached the workspace root (base config directory)
+                break;
+            }
```
[the remark this answers is not in the document]
Comment (Sysix) [reply apps/oxlint/src/config_loader.rs:65]: I think we want this behavior 🤞

File: apps/oxlint/src/config_loader.rs [hunk 2]
```diff
@@ -57,6 +59,10 @@ pub fn discover_configs_in_ancestors<P: AsRef<Path>>(
         // Start from the file's parent directory and walk up the tree
         let mut current = path.parent();
         while let Some(dir) = current {
+            if dir == cwd {
+                // Stop if we've reached the workspace root (base config directory)
```
Comment (Leonabcd123) [inline apps/oxlint/src/config_loader.rs]: If we have this, do we need this check?:

```
if config.path() == base_config_path {
  // Skip the base config file (e.g., root oxlintrc) to avoid duplicate loading
  continue;
}
```

We should break before we reach that part.

Comment (Sysix) [reply apps/oxlint/src/config_loader.rs]: Good catch! I updated the code :) Thank again for your help!

**Comment by alexkuz** [comment]
Since you're fixing nested configs, would you mind looking at these tests?
(they are not the part of any PR currently)

https://github.com/alexkuz/oxc/commit/99df23f182962743fc1e6759f3248c146b29fe32

one of them is passing now but the other one (test_run_from_nested_dir_with_root_type_aware) is still failing.

**Comment by Sysix** [comment]
@alexkuz I would expect it to fail. The "base" config is searching from the current cwd (which you defined as "nested"), or you pass it with `--config <path>`.
Looking it upwards beside the `cwd`, will create new problems. 
What if you have a setup like:
```
- ~/.oxlintrc.json // home dir
- ~/project/.oxlintrc.json // project dir
```

And then you lint from `~/project`, I would expect that the project config will still be the base config.  
Feel free to create a new issue for this, specially because it effects the `typeAware/Check` option.

**Review by camc314 — APPROVED** [review]
Thank you! 🙏

**Comment by camc314** [comment]
### Merge activity

* **Apr 5, 11:44 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Apr 5, 11:44 AM UTC**: `camc314` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Apr 5, 11:56 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
