### PR TITLE
fix(semantic): resolve references to the incorrect symbol

### LINKED ISSUE #3799: Incorrect reference resolve in function parameter's type
```typescript
import * as foo from 'foo';

function bar(foo: foo) {}
```

We treat function parameter `foo`'s type refers to itself.

CleanShot 2024-06-21 at 10 00 04@2x

CleanShot 2024-06-21 at 10 03 02@2x

1. [our playground](https://oxc-project.github.io/oxc/playground/?code=3YCAAIC1gICAgICAgIC0G8rnONK887cdP8rOL8UC6QnA9HB4rpM9rpIjLjycp13Au8%2FJhmDB5RAx7SoW4A0Y7lXumf54QLmA) 
2. [typescript playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wGYQpqERwDkWEhA3AFBVUYCuAdgMYzAT0oAUJAXJtgJRwA3hThwKAXyA)

### PR DESCRIPTION
**Pull request by Dunqing**
close: #3799
related: #3863

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4280?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4280** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4280?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4253** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4253?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_syntax/src/symbol.rs [hunk 1]
```diff
@@ -46,25 +46,26 @@ bitflags! {
         const Class                   = 1 << 5;
         const CatchVariable           = 1 << 6; // try {} catch(catch_variable) {}
         const Function                = 1 << 7;
-        const ImportBinding           = 1 << 8; // Imported ESM binding
+        const Import             = 1 << 8; // Imported ESM binding
+        const TypeImport              = 1 << 9; // Imported ESM type-only binding
```
Comment (Dunqing) [inline crates/oxc_syntax/src/symbol.rs:50]: TypeScript doesn't have both symbols. I added it because we can quickly look up type binding and need it in #3827

**Review by Boshen — APPROVED** [review]

File: crates/oxc_syntax/src/symbol.rs (hunk 1 above)
Comment (DonIsaac) [reply crates/oxc_syntax/src/symbol.rs:50]: This will help with lint rules too, tyvm.

**Review by DonIsaac — APPROVED** [review]
