### PR TITLE
fix(minifier): Preserve init variable declarations when removing `for` statements during DCE

### LINKED ISSUE #6547: Wrong full-elimination on `for` stmt with `var` decl.
Given the code:

```js
for (var { c, x: [d] } = {}; 0;);
```

In reality, our actual behavior is to eliminate the entire code, which is incorrect. We need to eliminate it to:

```js
var { c: a, x: [c] } = {};
```

Also given:

```js
for (var se = [1, 2]; false;);
```

need we handle it to:

```js
var se=[1,2];
```

### PR DESCRIPTION
**Pull request by magic-akari**
- Closes: #6547

### CODE REVIEW

File: crates/oxc_ast/src/ast_builder_impl.rs [hunk 1]
```diff
@@ -112,6 +112,20 @@ impl<'a> AstBuilder<'a> {
...
+        decl: &mut VariableDeclaration<'a>,
+    ) -> VariableDeclaration<'a> {
+        let empty_decl = self.variable_declaration(
+            Span::default(),
+            VariableDeclarationKind::Var,
+            self.vec(),
+            false,
+        );
+        mem::replace(decl, empty_decl)
+    }
```
Comment (7086cmd) [inline crates/oxc_ast/src/ast_builder_impl.rs:127]: Will the `var` raise some effects on `KeepVar`?

Comment (magic-akari) [reply crates/oxc_ast/src/ast_builder_impl.rs:127]: Not sure what you mean, but you can review the added test cases.

Comment (magic-akari) [reply crates/oxc_ast/src/ast_builder_impl.rs:127]: Do you mean this case?

```JavaScript
for(let i = 0; i < 10; i++) {
    var a = 0;
}
```

In this case, we should not count the variable `a` because it is in block scope.

Comment (camc314) [reply crates/oxc_ast/src/ast_builder_impl.rs:127]: Screenshot 2024-10-14 at 13 12 59

why do we drop `a` ?

Comment (7086cmd) [reply crates/oxc_ast/src/ast_builder_impl.rs:127]: Well, I got misunderstood. You can ignore this review :joy:

**Review by 7086cmd — APPROVED** [review]
LGTM
