### PR TITLE
fix(linter/prefer-called-once): avoid panic on trailing comma

### LINKED ISSUE #17733: oxlint: `vitest/prefer-called-once` rule panic if arguments have a trailing comma
> I think the fixer for this rule may cause a panic here?: https://github.com/oxc-project/oxc-ecosystem-ci/actions/runs/20762060613/job/59619842862#step:8:193
> 
> not 100% sure if this is the cause but it seems likely

_Originally posted by @connorshea in https://github.com/oxc-project/oxc/issues/17674#issuecomment-3716775521_

Following you can see the test is failing:

```
expect(window.HTMLElement.prototype.scrollIntoView).toHaveBeenCalledTimes(
      1,
    );
```

Which becomes:

```
 expect(window.HTMLElement.prototype.scrollIntoView).toHaveBeenCalledOnce(
      ,
    );
```

### PR DESCRIPTION
**Pull request by Afsoon**
Fix https://github.com/oxc-project/oxc/issues/17733

### CODE REVIEW

**Review by connorshea — APPROVED** [review]
~~Thanks! LGTM :)~~ Jk I missed a typo

File: crates/oxc_linter/src/rules/vitest/prefer_called_once.rs [hunk 1]
```diff
@@ -125,6 +128,28 @@ impl PreferCalledOnce {
...
+fn is_open_parenthesis(source_text: &str) -> bool {
+    source_text.starts_with('(')
+}
+
+fn is_close_parenthesis(source_text: &str) -> bool {
+    source_text.ends_with(')')
+}
+
+fn get_inside_parenthesis_span(argument_span: Span, ctx: &LintContext<'_>) -> Span {
+    let mut inside_parentehsis_span = Span::new(argument_span.start, argument_span.end);
```
Comment (connorshea) [inline crates/oxc_linter/src/rules/vitest/prefer_called_once.rs]: Typo (need to fix this elsewhere in the method as well):

```suggestion
    let mut inside_parenthesis_span = Span::new(argument_span.start, argument_span.end);
```

Comment (connorshea) [reply crates/oxc_linter/src/rules/vitest/prefer_called_once.rs]: I guess it could be argued that this should really be `inside_parentheses_span` but eh

File: crates/oxc_linter/src/rules/vitest/prefer_called_once.rs [hunk 2]
```diff
@@ -125,6 +128,28 @@ impl PreferCalledOnce {
...
+
+    while !is_open_parenthesis(ctx.source_range(inside_parentehsis_span.expand_left(1))) {
+        inside_parentehsis_span = inside_parentehsis_span.expand_left(1);
+    }
+
+    while !is_close_parenthesis(ctx.source_range(inside_parentehsis_span.expand_right(1))) {
+        inside_parentehsis_span = inside_parentehsis_span.expand_right(1);
+    }
+
+    inside_parentehsis_span
```
Comment (connorshea) [inline crates/oxc_linter/src/rules/vitest/prefer_called_once.rs]:
```suggestion
    let mut inside_parenthesis_span = Span::new(argument_span.start, argument_span.end);

    while !is_open_parenthesis(ctx.source_range(inside_parenthesis_span.expand_left(1))) {
        inside_parenthesis_span = inside_parenthesis_span.expand_left(1);
    }

    while !is_close_parenthesis(ctx.source_range(inside_parenthesis_span.expand_right(1))) {
        inside_parenthesis_span = inside_parenthesis_span.expand_right(1);
    }

    inside_parenthesis_span
```

**Review by connorshea — DISMISSED** [review]
I realized this was using source text checks that won't work in certain cases, so I've added a few test cases where this will fail to fix the code correctly.

(Technically I guess it shouldn't delete the code comments, so the tests I've added are arguably wrong, but I feel less strongly about keeping those)

````
---- rules::vitest::prefer_called_once::test stdout ----

thread 'rules::vitest::prefer_called_once::test' (12306774) panicked at crates/oxc_linter/src/fixer/mod.rs:395:13:
Linter fixer produced invalid syntax.

Input code: 
```
expect(window.HTMLElement.prototype.scrollIntoView).toHaveBeenCalledTimes(/* comment (because why not) */1,);
```

Fixed code: 
```
expect(window.HTMLElement.prototype.scrollIntoView).toHaveBeenCalledOnce(/* comment ();
```

Parse errors: [OxcDiagnostic { inner: OxcDiagnosticInner { message: "Unterminated multiline comment", labels: Some([LabeledSpan { label: None, span: SourceSpan { offset: SourceOffset(73), length: 14 }, primary: false }]), help: None, note: None, severity: Error, code: OxcCode { scope: None, number: None }, url: None } }]
````

I also added some tests to the other rules with similar fixers just to make sure this isn't a problem on those rules, you can ignore those.

**Comment by Afsoon** [comment]
I will convert this PR to draft, you are right with those assumptions. In this state, it doesn't solve the problem.

**Comment by Afsoon** [comment]
I change how I handle the fix. Now instead of remove everything, I'm only removing the argument span and comma span. Or if it's okay to remove the comment, I can replace completly the modifiers and args.

**Review by camc314 — CHANGES_REQUESTED** [review]
there're still bugs here. I'm going to take a look

File: crates/oxc_linter/src/rules/vitest/prefer_called_once.rs [hunk 3]
```diff
@@ -112,19 +112,49 @@ impl PreferCalledOnce {
...
+    {
+        offset += 1;
+    }
+
+    if call_expr.end == argument_span.end + offset {
+        return None;
+    }
+
+    Some(Span::new(argument_span.start + offset, argument_span.end + offset))
+}
```
Comment (camc314) [inline crates/oxc_linter/src/rules/vitest/prefer_called_once.rs]: if there is a `,` inside a comment, but after the argument, create an invalid fix

**Review by camc314 — APPROVED** [review]
Thank you!

File: crates/oxc_linter/src/rules/vitest/prefer_called_once.rs (hunk 3 above)
Comment (camc314) [reply crates/oxc_linter/src/rules/vitest/prefer_called_once.rs]: https://github.com/oxc-project/oxc/pull/17735/commits/c3b9bdbe93d734be729b28d1565181e67dd1a1b1

**Comment by camc314** [comment]
> there're still bugs here. I'm going to take a look

fixed by https://github.com/oxc-project/oxc/pull/17735/commits/c3b9bdbe93d734be729b28d1565181e67dd1a1b1
