### PR TITLE
fix(linter): improve diagnostics for no-control-regex

### LINKED ISSUE #10950: linter: `eslint(no-control-regex)` warns `\0` as unexpected control character
### What version of Oxlint are you using?

0.16.10

### What command did you run?

using vscode extension without installing oxlint in the project

### What does your `.oxlintrc.json` config file look like?

No config is used.

### What happened?

`/\f/` is warned by `eslint(no-control-regex)` rule.
[playground](https://playground.oxc.rs/#eNpFkEFLxEAMhf/KknNxdwUvFW/Sq6LXgqTTdBmZTkqSri5L/7tpS+tpEnh533tzhwAlBM5qh68BzUjy+fByONb16fhcZyiAobyDjHl+9JYNf6E0GamAFLNtswYeaF9ufcNp20wwa8fSQ9lhUpoKGFCUZHbElPjng2yU/DaaxpaqMQeL7Lz1fBBy7ZXeUSjrjuBRAlUxUcbewWCk9vCt4O5zrsXd5x2+4gzlQh4aSB9P5yevF5UTGrWvFBIKzmSHbEEDt3ShpbuDmkSfC7fH4V/Txxy7uAH9L004VV5rvrqSNKwecFVP0x+ni4Oh)
This code is not warned by the original rule ([playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tY29udHJvbC1yZWdleDogXCJlcnJvclwiKi9cblxuY29uc3QgcGF0dGVybjEgPSAvXFwwLztcbiIsIm9wdGlvbnMiOnsicnVsZXMiOnt9LCJsYW5ndWFnZU9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==)).

refs #10310

### PR DESCRIPTION
**Pull request by camc314**
closes #10950, by improving the diagnostic when (deprecated) octal escapes are used

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/no_control_regex.rs [hunk 1]
```diff
@@ -1,25 +1,86 @@
...
+    }
+
+    if !null_chars.is_empty() {
+        writeln!(
+        help,
+        "'\\0' matches the null character (U+0000), which is a control character. If you intend to match the null character, consider using '\\x00' or '\\u0000' for clarity."
+        ).unwrap();
+    }
+
+    help.truncate(help.len() - 1);
```
[the remark this answers is not in the document]
Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_control_regex.rs]: that code path should be unreachable as we always call `writeln` at least once on `help`. this means that `help` will always end with a trailing newline, which is what we're removing

File: crates/oxc_linter/src/rules/eslint/no_control_regex.rs [hunk 2]
```diff
@@ -1,25 +1,90 @@
...
+    }
+
+    if !null_chars.is_empty() {
+        writeln!(
+        help,
+        "'\\0' matches the null character (U+0000), which is a control character. If you intend to match the null character, consider using '\\x00' or '\\u0000' for clarity."
+        ).unwrap();
+    }
+
+    debug_assert!(help.chars().last().is_some_and(|char| char == '\n'));
```
[the remark this answers is not in the document]
Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_control_regex.rs:74]: 👎 help should never be empty

File: crates/oxc_linter/src/snapshots/eslint_no_control_regex@capture-group-indexing.snap [hunk 3]
```diff
@@ -6,25 +6,25 @@ source: crates/oxc_linter/src/tester.rs
  1 │ const r = /\0/;
    ·           ────
    ╰────
-  help: '\0' is not a valid control character.
+  help: '\0' matches the null character (U+0000), which is a control character. If you intend to match the null character, consider using '\x00' or '\u0000' for clarity.
```
Comment (sapphi-red) [inline crates/oxc_linter/src/snapshots/eslint_no_control_regex@capture-group-indexing.snap:9]: This suggestion doesn't seem correct. Both `\x00` or `\u0000` will be warned by this rule.
[playground](https://playground.oxc.rs/#eNpVkE1rwzAMhv9K0bmsaWGXjN1GrhvbNTAURykejh0kuWsp+e9TEpJRXyyhj+d9dQcHJbgURXffA6oSx+PudXeo62tRHF7q+Fg7LbVc2JuqsIcE5R04x+mTW1S8QqmcaQ/BR11jcWmgLbn1TQprpoxRusQ9lB0GoXEPA7IQTxsxhPT7SZo5vmcV31KVo1OfjLeMD0zWe6EPZIqyIVJmR5UPFLE3MCiJPv0I2PZJ17zd4g2+4BT5TCYaSE7F8dnseUkBldo3cgEZJ7JBVqEutXSm2buBmkBfM7fH4b+n99F3fgXaPZVTqMzWNHUhbpKYwKV7HP8AO4iN7A==)

I kind of opened the issue straight ahead without thinking because `\0` was not warned by eslint. But on second thought, given that `\0` is a control character, it actually makes sense for this rule to catch it.

File: crates/oxc_linter/src/rules/eslint/no_control_regex.rs [hunk 4]
```diff
@@ -1,25 +1,88 @@
...
+        }
+    }
+
+    let mut help = String::new();
+
+    if !other_chars.is_empty() {
+        let regexes = other_chars.iter().join(", ");
+        writeln!(
+            help,
+            "'{regexes}' {} not {}valid control character{}.",
```
Comment (sapphi-red) [inline crates/oxc_linter/src/rules/eslint/no_control_regex.rs:43]: BTW I guess this message is wrong. This rule (`no-control-regex`) detects [control characters](https://en.wikipedia.org/wiki/Control_character#In_ASCII), so this message should output "'\x01' is a control character" instead.

File: crates/oxc_linter/src/snapshots/eslint_no_control_regex@capture-group-indexing.snap (hunk 3 above)
Comment (camc314) [reply crates/oxc_linter/src/snapshots/eslint_no_control_regex@capture-group-indexing.snap:9]: https://github.com/oxc-project/oxc/pull/10993

File: crates/oxc_linter/src/rules/eslint/no_control_regex.rs (hunk 4 above)
Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_control_regex.rs:43]: yeah - you're right, thanks for catching
