### PR TITLE
fix(linter/unicorn): consistent-function-scoping false positive on assignment expression

### LINKED ISSUE #5159: bug(linter): false positive in `consistent-function-scoping` in `AssignmentExpression`s
This snippet should not violate `unicorn/consistent-function-scoping`, but it currently does:

```js
module.exports = function foo() {}
```

### PR DESCRIPTION
**Pull request by Arian94**
fixes #5159 and any other named function assigned to a property like:
```js
const foo = {};
foo.bar = function fooBar() {}
```

### CODE REVIEW

File: crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs [hunk 1]
```diff
@@ -160,6 +160,10 @@ impl Rule for ConsistentFunctionScoping {
     fn run<'a>(&self, node: &AstNode<'a>, ctx: &LintContext<'a>) {
         let (function_declaration_symbol_id, function_body, reporter_span) = match node.kind() {
             AstKind::Function(function) => {
+                if let Some(AstKind::AssignmentExpression(_)) = ctx.nodes().parent_kind(node.id()) {
```
Comment (DonIsaac) [inline crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:163]: I don't know if I agree with this.

This case would now not be reported:
```ts
function outer() {
  const inner = function inner() {}
}
```

IMO, we should be checking for assignment expressions and, when found, using that node's scope id instead of t he function's scope id.

**Review by DonIsaac — CHANGES_REQUESTED** [review]

File: crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs (hunk 1 above)
Comment (Arian94) [reply crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:163]: Are you sure? I am getting the error.
```
  ⚠ eslint-plugin-unicorn(consistent-function-scoping): Function does not capture any variables from the outer scope.
   ╭─[consistent_function_scoping.tsx:2:31]
 1 │ function outer() {
 2 │                 const inner = function inner() {}
   ·                               ────────
 3 │             }
   ╰────
  help: Move this function to the outer scope.
```

Comment (camc314) [reply crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:163]: ah @DonIsaac this is because that's a variable declaration, whereas this is fixing an assignment expressin.

pesky JS 🙂 

Regardless. i think we should add this as a `fail` test case. 
We should also add

```ts
function outer() { 
    inner = function foo() {}
}
```

as a `fail` test case

Comment (Arian94) [reply crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:163]: @camc314 the other thing is if you pay close attention to the underlined keyword of the error, it's the ```function``` keyword which is underlined. The correct keyword should be the ```inner``` token.

Why should we add the second example you mentioned as a failed test? It is getting passed in Eslint.

File: crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs [hunk 2]
```diff
@@ -172,8 +176,15 @@ impl Rule for ConsistentFunctionScoping {
                     (
                         binding_ident.symbol_id.get().unwrap(),
                         function_body,
-                        // 8 for "function"
-                        Span::sized(function.span.start, 8),
+                        function
+                            .id
+                            .as_ref()
+                            .unwrap_or(&oxc_ast::ast::BindingIdentifier {
```
Comment (DonIsaac) [inline crates/oxc_linter/src/rules/unicorn/consistent_function_scoping.rs:182]: Use map to get the span, don't create a new binding identifier.

**Review by DonIsaac — CHANGES_REQUESTED** [review]

**Review by camc314 — APPROVED** [review]
Thanks!

**Review by DonIsaac — APPROVED** [review]
