### PR TITLE
fix(eslint/no-obj-calls): should resolve non-global binding correctly

### LINKED ISSUE #744: eslint/no-obj-calls: should try resolve non-global binding in scope chain instead of only current scope
I know this is already merged and closed but I don't want to open a new issue when it's so recent.

When running the current main branch against the `eslint` codebase I get the following `panic!`:
```
     Running `/home/maneren/.cache/cargo/target/debug/oxc_cli lint /home/maneren/git-repos/eslint/lib/`
thread '<unnamed>' panicked at 'No binding id found, but this IdentifierReference is not a global', crates/oxc_linter/src/rules/eslint/no_obj_calls.rs:94:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
[1]    17749 IOT instruction (core dumped)  cargo r --bin oxc_cli -- lint /home/maneren/git-repos/eslint/lib/
```
That doesn't seem like it's supposed to happen.

_Originally posted by @Maneren in https://github.com/web-infra-dev/oxc/issues/508#issuecomment-1618850742_

### PR DESCRIPTION
**Pull request by hyfdev**
Fixes #744

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/no_obj_calls.rs [hunk 1]
```diff
@@ -88,11 +88,13 @@ fn resolve_global_binding<'a, 'b: 'a>(
         let scope = ctx.scopes();
         let nodes = ctx.nodes();
         let symbols = ctx.symbols();
-        scope.get_binding(scope_id, &ident.name).map_or_else(
+        scope.ancestors(scope_id).find_map(|id| scope.get_binding(id, &ident.name)).map_or_else(
             || {
-                // panic!("No binding id found for {}, but this IdentifierReference
-                // is not a global", &ident.name);
-                None
+                panic!(
```
Comment (hyf0) [inline crates/oxc_linter/src/rules/eslint/no_obj_calls.rs:93]: I'm not sure. Maybe `unreachable!` is better than `panic!`?

**Review by Boshen — APPROVED** [review]
