### PR TITLE
fix(oxfmt): Ignore unsupported options

### LINKED ISSUE #15930: oxfmt: report an error if the option we don't support
I just found out that the experimental option can be resolved, but it shouldn't be, as we don't support this option yet. We should report an error for all options that we haven't supported; otherwise, it would lead to confusion as to why this option doesn't work!

https://github.com/oxc-project/oxc/blob/4b9d8d2c4abbeda1cd2cbb0ca5e530d2690ab00a/crates/oxc_formatter/src/service/oxfmtrc.rs#L353-L360

### PR DESCRIPTION
**Pull request by leaysgur**
Fixes #15930

Previously `experimentalOperatorPosition` was suggested in `.oxfmtrc` completion. But it is not actually used(not implemented yet).

As a first step, just ignore it. + Report error => #16088

### CODE REVIEW

**Comment by leaysgur** [comment]
* **#16085** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16085?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#16086](https://github.com/oxc-project/oxc/pull/16086) <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16086?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#16088](https://github.com/oxc-project/oxc/pull/16088) <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16088?utm_source=stack-comment-icon" target="_blank">Graphite</a>) 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16085?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=16085).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_formatter/src/service/oxfmtrc.rs [hunk 1]
```diff
@@ -351,13 +337,9 @@ impl Oxfmtrc {
...
 
+        // Not yet supported options:
         // [Prettier] experimentalOperatorPosition: "start" | "end"
-        if let Some(position) = self.experimental_operator_position {
-            options.experimental_operator_position = match position {
-                OperatorPositionConfig::Start => OperatorPosition::Start,
-                OperatorPositionConfig::End => OperatorPosition::End,
-            };
-        }
+        // [Prettier] experimentalTernaries: boolean
```
Comment (Dunqing) [inline crates/oxc_formatter/src/service/oxfmtrc.rs:342]: How about returning an error directly here instead? Then, we should disable generating the schema for this option

**Review by Dunqing — CHANGES_REQUESTED** [review]

File: crates/oxc_formatter/src/service/oxfmtrc.rs (hunk 1 above)
Comment (leaysgur) [reply crates/oxc_formatter/src/service/oxfmtrc.rs:342]: (You're commenting after seeing #16086, right?)

Initially, I intended to do that, but I was concerned about defining unnecessary fields solely for specifying `#[schemars(skip)]`, which led me to this implementation.

Which do you prefer?

Comment (leaysgur) [reply crates/oxc_formatter/src/service/oxfmtrc.rs:342]: After taking another look, I realized it wasn't as bad as I thought. 🙂 => #16088

**Review by Dunqing — APPROVED** [review]
