### PR TITLE
fix(linter): junit support for multiple files/errors/diagnostics

### LINKED ISSUE #16567: linter: junit formatter contains last file diagnistics only
### What version of Oxlint are you using?

1.31.0

### What command did you run?

`oxlint -c .oxintrc.json --format junit`

### What does your `.oxlintrc.json` config file look like?
N/A

### What happened?

consider this default oxlint output for a given two file project
```
> pnpm oxlint *.tsx -D all

  × eslint(curly): Expected { after 'if' condition.
   ╭─[bar.tsx:4:22]
 3 │ const DummyComponent: React.FC = () => {
 4 │     if (ref.current) ref.current.focus()
   ·                      ───────────────────
 5 │ 
   ╰────
  help: Replace `ref.current.focus()` with `{ref.current.focus()}`.

  × eslint(curly): Expected { after 'if' condition.
   ╭─[foo.tsx:7:22]
 6 │   useEffect(() => {
 7 │     if (ref.current) ref.current.focus()
   ·                      ───────────────────
 8 │   }, [])
   ╰────
  help: Replace `ref.current.focus()` with `{ref.current.focus()}`.

  × eslint(no-constant-binary-expression): Unexpected constant nullishness on the left-hand side of a "??" expression
    ╭─[foo.tsx:11:11]
 10 │       return (
 11 │ ╭─▶     <div>{Boolean(ref.current) ?? (
 12 │ │         <input type="text" ref={ref} />
 13 │ ╰─▶     )}
 14 │         </div>
    ╰────
  help: This expression always evaluates to the constant on the left-hand side

Found 0 warnings and 3 errors.
Finished in 40ms on 2 files with 335 rules using 12 threads.
```

It has simillar correct outputs with other formatters
<details><summary>stylish</summary>

```
> pnpm oxlint *.tsx -D all --format stylish

/tmp/tmp.lLodRLQny0/foo.tsx
  7:22   error  Expected { after 'if' condition.  eslint(curly)
  11:11  error  Unexpected constant nullishness on the left-hand side of a "??" expression  eslint(no-constant-binary-expression)

/tmp/tmp.lLodRLQny0/bar.tsx
  4:20  error  Expected { after 'if' condition.  eslint(curly)
```

</details>

<details>
<summary>Json</summary>

```
> pnpm oxlint *.tsx -D all --format json
{ "diagnostics": [{"message": "Expected { after 'if' condition.","code": "eslint(curly)","severity": "error","causes": [],"url": "https://oxc.rs/docs/guide/usage/linter/rules/eslint/curly.html","help": "Replace `ref.current.focus()` with `{ref.current.focus()}`.","filename": "foo.tsx","labels": [{"span": {"offset": 178,"length": 19,"line": 7,"column": 22}}],"related": []},
{"message": "Unexpected constant nullishness on the left-hand side of a \"??\" expression","code": "eslint(no-constant-binary-expression)","severity": "error","causes": [],"url": "https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-constant-binary-expression.html","help": "This expression always evaluates to the constant on the left-hand side","filename": "foo.tsx","labels": [{"span": {"offset": 229,"length": 69,"line": 11,"column": 11}}],"related": []},
{"message": "Expected { after 'if' condition.","code": "eslint(curly)","severity": "error","causes": [],"url": "https://oxc.rs/docs/guide/usage/linter/rules/eslint/curly.html","help": "Replace `ref.current.focus()` with `{ref.current.focus()}`.","filename": "bar.tsx","labels": [{"span": {"offset": 94,"length": 19,"line": 4,"column": 20}}],"related": []}],
              "number_of_files": 2,
              "number_of_rules": 335,
              "threads_count": 12,
              "start_time": 0.029430435
            }
              
```

</details>

<details>
<summary>Checkstyle</summary>

```
> pnpm oxlint *.tsx -D all --format checkstyle
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="foo.tsx"><error line="7" column="22" severity="error" message="Expected { after &apos;if&apos; condition." source="eslint(curly)" /><error line="11" column="11" severity="error" message="Unexpected constant nullishness on the left-hand side of a &quot;??&quot; expression" source="eslint(no-constant-binary-expression)" /></file> <file name="bar.tsx"><error line="4" column="20" severity="error" message="Expected { after &apos;if&apos; condition." source="eslint(curly)" /></file></checkstyle>
```

</details> 

However for the junit output - it only has a **singular** error, and for only a singular file

```
> pnpm oxlint *.tsx -D all --format junit
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Oxlint" tests="3" failures="0" errors="3">
    <testsuite name="bar.tsx" tests="1" disabled="0" errors="1" failures="0">
        <testcase name="eslint(curly)">
            <error message="Expected { after &apos;if&apos; condition.">line 4, column 20, Expected { after &apos;if&apos; condition.</error>
        </testcase>
    </testsuite>
</testsuites>
```

Where we would instead expect multiple testSuites and multiple `errors`

I have a PR that might fix this which will raise shortly - but needs someone to check it :D

### PR DESCRIPTION
**Pull request by spanishpear**
Attempt to fix #16567 

includes simple test

### CODE REVIEW

File: apps/oxlint/src/output_formatter/junit.rs [hunk 1]
```diff
@@ -33,18 +33,21 @@ impl DiagnosticReporter for JUnitReporter {
...
         let info = Info::new(diagnostic);
         grouped.entry(info.filename).or_default().push(diagnostic);
     }
 
-    let mut test_suite = String::new();
-    for diagnostics in grouped.values() {
-        let diagnostic = diagnostics[0];
-        let filename = Info::new(diagnostic).filename;
+    let mut filenames: Vec<_> = grouped.keys().cloned().collect();
+    filenames.sort();
```
Comment (spanishpear) [inline apps/oxlint/src/output_formatter/junit.rs:43]: This is a bit sus and requires an allocation - think I could get rid of it, but would make the junit output instead non-deterministic on hashmap insertion

File: apps/oxlint/src/output_formatter/junit.rs [hunk 2]
```diff
@@ -33,18 +33,21 @@ impl DiagnosticReporter for JUnitReporter {
...
+
+    let mut total_errors = 0;
+    let mut total_warnings = 0;
+    let mut test_suites = Vec::new();
+
+    for filename in filenames {
+        let diagnostics = grouped.get(&filename).expect("filename collected from map");
```
Comment (spanishpear) [inline apps/oxlint/src/output_formatter/junit.rs:50]: we generally have guarantees on presence here, but alternatively we we can also handle gracefully and continue 👁️

File: apps/oxlint/src/output_formatter/junit.rs [hunk 3]
```diff
@@ -72,25 +75,26 @@ fn format_junit(diagnostics: &[Error]) -> String {
                 description,
                 severity
             );
-            let test_case =
-                format!("\n        <testcase name=\"{rule}\">\n{status}\n        </testcase>");
-            test_cases = format!("{test_cases}{test_case}");
+            let test_case = format!(
+                "\n        <testcase name=\"{rule}\">\n{status}\n        </testcase>"
+            );
+            test_cases.push_str(&test_case);
```
Comment (spanishpear) [inline apps/oxlint/src/output_formatter/junit.rs:80]: Slight perf to reduce allocations compared to rebuilding the new `String` in `format!` each time. append in place only now

File: apps/oxlint/src/output_formatter/junit.rs (hunk 1 above)
Comment (camc314) [reply apps/oxlint/src/output_formatter/junit.rs:43]: I think this is ok, the fast path (and hopefully most common) is when `filenames` is empty, so there shouldn't be too many allocations there.

**Review by camc314 — APPROVED** [review]
Thank you!

**Comment by spanishpear** [comment]
Thanks for the fast review!! Autofix CI is neat - my local env is a bit broken and was just scrambling to fix it - now I'm not as worried😍
