### PR TITLE
fix(linter) Improve span for jsx key

### LINKED ISSUE #1034: Improve the error span on jsx-key
After testing it on some large codebases, I found the spans that are currently pointing to the entire element is not precise, would it be possible to point it to the iterator method as well as the element name?

### PR DESCRIPTION
**Pull request by camc314**
closes #1034

### CODE REVIEW

File: crates/oxc_linter/src/rules/react/jsx_key.rs [hunk 1]
```diff
@@ -113,6 +119,28 @@ fn is_in_array_or_iter<'a, 'b>(
     }
 }
 
+fn get_member_expression_name_and_span<'a>(
```
Comment (Boshen) [inline crates/oxc_linter/src/rules/react/jsx_key.rs:122]: You can use `static_property_name` from `MemberExpression` and also `.span()` 😁

File: crates/oxc_linter/src/snapshots/jsx_key.snap [hunk 2]
```diff
@@ -23,86 +23,128 @@ expression: jsx_key
   ⚠ eslint-plugin-react(jsx-key): Missing "key" prop for element in iterator.
    ╭─[jsx_key.tsx:1:1]
  1 │ [1, 2 ,3].map(function(x) { return <App /> });
-   ·                                    ───────
+   ·           ─┬─                      ───┬───
```
Comment (Boshen) [inline crates/oxc_linter/src/snapshots/jsx_key.snap:26]: The element can be very long, so perhaps focusing on the name is enough.

**Review by Boshen — APPROVED** [review]
