### PR TITLE
fix(linter/filename-case): fix default config when no config is provided

### LINKED ISSUE #12276: `eslint-plugin-unicorn (filename-case)` under `"style"` doesn't work as expected
# Steps to Reproduce
1. Create a new Next.js application.
```
npx create-next-app@latest
```
2. Create an `.oxlintrc.json` file.
```
code .oxlintrc.json
```
```json
{
	"categories": {
		"style": "deny"
	}
}
```
3. Run `npx oxlint@latest`.
```
npx oxlint@latest
```

# Expected behavior
`src/app/page.tsx` shouldn't have a filename issue, but even if it does have one, `oxlint` should tell me what it is.

# Actual behavior
```
$ npx oxlint@latest 

  × eslint(sort-keys): Object keys should be sorted
    ╭─[src/app/layout.tsx:15:35]
 14 │     
 15 │ ╭─▶ export const metadata: Metadata = {
 16 │ │     title: "Create Next App",
 17 │ │     description: "Generated by create next app",
 18 │ ╰─▶ };
 19 │     
    ╰────

  × eslint-plugin-unicorn(filename-case): Filename should be in 
   ╭─[src/app/layout.tsx:1:1]
 1 │ import type { Metadata } from "next";
   · ▲
 2 │ import { Geist, Geist_Mono } from "next/font/google";
   ╰────
  help: Rename the file to

  × eslint-plugin-unicorn(filename-case): Filename should be in 
   ╭─[src/app/page.tsx:1:1]
 1 │ import Image from "next/image";
   · ▲
 2 │ 
   ╰────
  help: Rename the file to
```

### PR DESCRIPTION
**Pull request by camc314**
fixes #12276

### CODE REVIEW

**Comment by camc314** [comment]
* **#12389** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12389?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12389?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=12389).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_linter/src/rules/unicorn/filename_case.rs [hunk 1]
```diff
@@ -37,6 +37,19 @@ pub struct FilenameCaseConfig {
     multi_extensions: bool,
 }
 
+impl Default for FilenameCaseConfig {
```
Comment (camc314) [inline crates/oxc_linter/src/rules/unicorn/filename_case.rs:40]: this copies the same config as unicorn
