### PR TITLE
fix(linter): fix false positives in loss-of-precision lint

### LINKED ISSUE #656: bug(linter): incorrect no-loss-of-precision
From the vscode codebase

image

cc @Devin-Yeung

### PR DESCRIPTION
**Pull request by Devin-Yeung**
Almost rewrite the no-loss-of-precision lint, fix known false positives, close #656

### CODE REVIEW

**Review by Abdel-Monaam-Aouini — APPROVED** [review]

File: crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs [hunk 1]
```diff
@@ -48,18 +49,89 @@ impl Rule for NoLossOfPrecision {
...
+            }
+            return self.exp == other.exp;
+        }
+        false
+    }
+}
+
+impl<'a> RawNum<'a> {
+    fn new(num: &str) -> Option<RawNum<'_>> {
+        let re = Regex::new(
```
Comment (Boshen) [inline crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs:81]: Need to move this to a static, otherwise it's constructed every time you run it.

**Review by Boshen — CHANGES_REQUESTED** [review]

File: crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs [hunk 2]
```diff
@@ -48,18 +50,87 @@ impl Rule for NoLossOfPrecision {
...
+            }
+            return self.exp == other.exp;
+        }
+        false
+    }
+}
+
+impl<'a> RawNum<'a> {
+    fn new(num: &str) -> Option<RawNum<'_>> {
+        static RE: OnceLock<Regex> = OnceLock::new();
```
Comment (DonIsaac) [inline crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs:82]: consider `lazy_static`

**Review by DonIsaac — DISMISSED** [review]

File: crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs (hunk 2 above)
Comment (Boshen) [reply crates/oxc_linter/src/rules/eslint/no_loss_of_precision.rs:82]: https://docs.rs/regex/latest/regex/#avoid-re-compiling-regexes-especially-in-a-loop

We can use `once_cell::sync::Lazy`, which should give us the best tradeoffs.

**Review by Boshen — APPROVED** [review]
