### PR TITLE
fix(linter): accept bools as valid values for `fixable`

### LINKED ISSUE #17967: linter: JS plugins "rule.meta.fixable"
### What version of Oxlint are you using?

1.38.0

### What command did you run?

npx oxlint

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
    "jsPlugins": ["eslint-plugin-lit-a11y"],
    "rules": {
        "lit-a11y/alt-text": "warn"
    }
}
```

```jsonc
{
  "jsPlugins": ["@html-eslint/eslint-plugin"],
  "rules": {
    "html/no-duplicate-class": "error",
  }
}
```

### What happened?

I saw that JS plugins are in technical preview so wanted to see if I could get the `eslint-plugin-lit-a11y` working. 

I also tried `@html-eslint/eslint-plugin` though i wasn't expecting that to work due to the ".html" extension not being supported. 

I ended up with this output for both:

`TypeError: Invalid 'rule.meta.fixable'`

Am I doing something silly? This plugin doesn't support fixable so is set to null. Is null not supported yet?

Thanks in advance.

Full output:
```
Failed to parse oxlint configuration file.

  × Failed to load JS plugin: eslint-plugin-lit-a11y
  │   TypeError: Invalid `rule.meta.fixable`
  │   TypeError: Invalid `rule.meta.fixable`
  │     at registerPlugin (file:///Users/jack/Developer/Phase/astro/node_modules/oxlint/dist/lint.js:15217:63)
  │     at loadPlugin (file:///Users/jack/Developer/Phase/astro/node_modules/oxlint/dist/lint.js:15203:35)
```

```
Failed to parse oxlint configuration file.

  × Failed to load JS plugin: @html-eslint/eslint-plugin
  │   TypeError: Invalid `rule.meta.fixable`
  │     at registerPlugin (file:///Users/jack/Developer/Phase/astro/node_modules/oxlint/dist/lint.js:15217:63)
  │     at loadPlugin (file:///Users/jack/Developer/Phase/astro/node_modules/oxlint/dist/lint.js:15203:35)
```

Link to rule fixer definition:

https://github.com/open-wc/open-wc/blob/5aeaf35e01a2f15b6663d71102eeea3333e4c57d/packages/eslint-plugin-lit-a11y/lib/rules/aria-attrs.js#L27

### LINKED ISSUE #18700: linter: Eslint plugin license header is not compatible with oxlint
### What version of Oxlint are you using?

1.42.0

### What command did you run?

`oxlint`

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "jsPlugins": ["eslint-plugin-license-header"],
  "rules": {
     "license-header/header": ["error", [
        "/* my header */"
     ]],
  }
}
```

### What happened?

License header is not detected even when present in the files.

This plugin was patched with patch package and diff:
```
diff --git a/node_modules/eslint-plugin-license-header/lib/rules/header.js b/node_modules/eslint-plugin-license-header/lib/rules/header.js
index 5e59ab3..58f8b7b 100644
--- a/node_modules/eslint-plugin-license-header/lib/rules/header.js
+++ b/node_modules/eslint-plugin-license-header/lib/rules/header.js
@@ -17,7 +17,7 @@ module.exports = {
       category: 'Possible Errors',
       recommended: true
     },
-    fixable: true,
+    fixable: 'code',
     schema: [
       {
         type: [ 'string', 'array' ],

```

### PR DESCRIPTION
**Pull request by camc314**
fixes https://github.com/oxc-project/oxc/issues/17967
fixes https://github.com/oxc-project/oxc/issues/18700
closes https://github.com/oxc-project/oxc/pull/18011

This PR allows boolean values as valid options for meta.fixable. While this technically doesn't align exactly with eslint, it reduces some friction about getting users to migrate from exlint to oxlint, by increasing the number of plugins that are compatible.

### CODE REVIEW

**Comment by camc314** [comment]
* **#18772** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18772?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18772?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=18772).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: apps/oxlint/src-js/plugins/load.ts [hunk 1]
```diff
@@ -179,7 +179,14 @@ export function registerPlugin(
...
+        // backward compatibility with some ESLint plugins
+        if (
+          fixable !== "code" &&
+          fixable !== "whitespace" &&
+          fixable !== true &&
+          fixable !== false
+        ) {
           throw new TypeError("Invalid `rule.meta.fixable`");
         }
         isFixable = true;
```
Comment (connorshea) [inline apps/oxlint/src-js/plugins/load.ts]: I agree with the bot, we shouldn't mark it as fixable when set to `false`. False should be treated the same as `null`, which is to say it's not fixable

**Review by connorshea — CHANGES_REQUESTED** [review]
false is handled incorrectly here

File: apps/oxlint/src-js/plugins/load.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (camc314) [reply apps/oxlint/src-js/plugins/load.ts]: yep youre right

Comment (camc314) [reply apps/oxlint/src-js/plugins/load.ts]: fixed - good catch

File: apps/oxlint/test/fixtures/fixable_boolean/fix.snap.md [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+   `----
+
+Found 0 warnings and 1 error.
+Finished in Xms on 1 file with 2 rules using X threads.
+```
+
+# stderr
+```
+WARNING: JS plugins are experimental and not subject to semver.
+Breaking changes are possible while JS plugins support is under development.
```
Comment (connorshea) [inline apps/oxlint/test/fixtures/fixable_boolean/fix.snap.md:20]: You'll get fun merge conflicts with #18771 but you probably know that already :)

**Review by connorshea — APPROVED** [review]
LGTM

File: apps/oxlint/test/fixtures/fixable_boolean/fix.snap.md (hunk 2 above)
Comment (camc314) [reply apps/oxlint/test/fixtures/fixable_boolean/fix.snap.md:20]: ugh haha

**Comment by camc314** [comment]
### Merge activity

* **Jan 31, 3:47 PM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Jan 31, 3:47 PM UTC**: `camc314` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Jan 31, 4:33 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
