### PR TITLE
fix(linter): handle loops in `getter-return` rule

### LINKED ISSUE #3935: linter: getter-return false positive
```javascript
  get steps() {
    const steps = [];

    const gradient = colorGradient('#3D68FF', '#8845FF', this.maxStepsNumber);

    for (let i = 0; i < this.maxStepsNumber; i++) {
      steps.push({
        stepnum: i + 1,
        status: i <= this.currentStepIndex ? 'active' : '',
        background: htmlSafe(`background: ${gradient[i]};`),
      });
    }

    return steps;
  }
```

https://github.com/1024pix/pix/blob/1352bd8d7f6070f1ff8da79867f543c1c1926e59/mon-pix/app/components/progress-bar.js#L29-L43

### PR DESCRIPTION
**Pull request by camchenry**
- Fixes https://github.com/oxc-project/oxc/issues/3935

Prior to this, it didn't seem like we were correctly continuing to search the graph after we encountered a backedge (loop). Now, when encountering a cycle, we will not automatically break or prune the search.

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/getter_return.rs [hunk 1]
```diff
@@ -426,6 +478,31 @@ fn test() {
...
+            None,
+        ),
+        (
+            "
+            var foo = {
+                get bar() {
+                    let i = 0;
+                    while (i < 10) {
+                        return i;
+                    }
```
Comment (camchenry) [inline crates/oxc_linter/src/rules/eslint/getter_return.rs:500]: Although this might actually return in all cases practically, in general it would be impossible to know if this actually returns or not (halting problem). So, we just assume that it won't and require it to be explicit

**Comment by rzvxa** [comment]
Thank you for your contribution, Funnily enough, earlier this day I was looking into this issue; I'm so glad you submitted this PR as early as you did otherwise we would've lost some time working on the same thing.

File: crates/oxc_linter/src/rules/eslint/getter_return.rs (hunk 1 above)
Comment (rzvxa) [reply crates/oxc_linter/src/rules/eslint/getter_return.rs:500]: Right, In most cases we can't detect it, However, We have `ControlFlowGraph::is_infinite_loop_start` which does a super simple constant evaluation that detects things like `while(true)` and `for (;;)`; We may want to enhance this rule in the future to pass things like this:

```js
class foo {
  get bar() {
    while(true) { return 0 }
  }
}
```

While linting code like:

```js
class foo {
  get bar() {
    while(false) { return 0 }
  }
}
```

However, it isn't necessary for now and seems out of the scope of this PR.

**Review by rzvxa — CHANGES_REQUESTED** [review]

File: crates/oxc_linter/src/rules/eslint/getter_return.rs (hunk 1 above)
Comment (rzvxa) [reply crates/oxc_linter/src/rules/eslint/getter_return.rs:500]: You are right, We have means to detect infinite loops like `while(true)` and `for(;;)` via constant evaluation but supporting it here might be out of scope.

**Review by rzvxa — APPROVED** [review]

**Comment by rzvxa** [comment]
Please update snapshots so the tests pass.
I personally use `cargo insta test` to regenerate all snapshots.

**Comment by camchenry** [comment]
@rzvxa Thanks, just updated it now!
