### PR TITLE
fix(editor): re-add tester and prevent empty inverted diagnostics 

### LINKED ISSUE #9958: editor: Presence of `typescript-eslint(no-non-null-asserted-optional-chain)` error causes errors not to be shown
### What version of Oxlint are you using?

0.16.1

### What command did you run?

VS Code extension

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",

  "env": {
    "browser": true,
    "node": true,
    "es2022": true
  },

  "plugins": [
    "node",
    "eslint",
    "oxc",
    "unicorn",
    // "import",
    "typescript",
    "react",
    "react-perf",
    "jsx-a11y",
    "vitest",
    "nextjs"
  ],

  "rules": {
    "eqeqeq": "error",
    "react/rules-of-hooks": "error",
    "react/exhaustive-deps": "error",
    "eslint/no-unused-vars": [
      "error",
      {
        "varsIgnorePattern": "^_",
        "argsIgnorePattern": "^_",
        "caughtErrorsIgnorePattern": "^_",
        "ignoreRestSiblings": true
      }
    ]
  },

  "categories": {
    "correctness": "error"
    // "perf": "warn",
    // "suspicious": "warn"
  },

  "overrides": [
    {
      "files": ["**/*.spec.{ts,tsx,js,jsx}"],
      "rules": {
        "typescript/no-non-null-assertion": "off",
        "typescript/no-non-null-asserted-optional-chain": "off"
      }
    }
  ],

  "ignorePatterns": ["e2e/**/*", "codemods/**/*", "scripts/**/*"]
}
```

### What happened?

I noticed some strange behavior in VS Code with this code snippet:
```
export function test() {
  let x = true;
  console.log(!!x ? 10 : 20);

  let a: {
    b?: {
      c: number;
    };
  } = {};

  console.log(a?.b?.c!);
}
```

There are two lint errors present here:
* `eslint(no-extra-boolean-cast): Redundant double negation` on line 3
* `typescript-eslint(no-non-null-asserted-optional-chain): non-null assertions after an optional chain expression` on line 11

However the VS Code extension does not show either of these errors.
If I either comment out line 11, or remove the non-null assertion, then the `no-extra-boolean-cast` starts showing up. 
If I then add back the non-null assertion, and fix the double negation, VS Code will continue to show it as a lint error, unless I again remove the non-null assertion.
oxlint cli reports both of these errors correctly.

I captured the following `publishDiagnostics` trace:
```
2025-03-21 18:15:30.553 [info] [Trace - 6:15:30 PM] Received notification 'textDocument/publishDiagnostics'.
2025-03-21 18:15:30.553 [info] Params: {
    "uri": "file:///redacted/l.ts",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 2,
                    "character": 14
                },
                "end": {
                    "line": 2,
                    "character": 17
                }
            },
            "severity": 1,
            "code": "eslint(no-extra-boolean-cast)",
            "codeDescription": {
                "href": "https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-extra-boolean-cast"
            },
            "source": "oxc",
            "message": "Redundant double negation\nhelp: Remove the double negation as it will already be coerced to a boolean",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///redacted/l.ts",
                        "range": {
                            "start": {
                                "line": 2,
                                "character": 14
                            },
                            "end": {
                                "line": 2,
                                "character": 17
                            }
                        }
                    },
                    "message": ""
                }
            ]
        },
        {
            "range": {
                "start": {
                    "line": 10,
                    "character": 18
                },
                "end": {
                    "line": 10,
                    "character": 18
                }
            },
            "severity": 1,
            "code": "typescript-eslint(no-non-null-asserted-optional-chain)",
            "codeDescription": {
                "href": "https://oxc.rs/docs/guide/usage/linter/rules/typescript_eslint/no-non-null-asserted-optional-chain"
            },
            "source": "oxc",
            "message": "non-null assertions after an optional chain expression\nhelp: Optional chain expressions can return undefined by design - using a non-null assertion is unsafe and wrong. You should remove the non-null assertion.",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///redacted/l.ts",
                        "range": {
                            "start": {
                                "line": 10,
                                "character": 18
                            },
                            "end": {
                                "line": 10,
                                "character": 18
                            }
                        }
                    },
                    "message": ""
                },
                {
                    "location": {
                        "uri": "file:///redacted/l.ts",
                        "range": {
                            "start": {
                                "line": 10,
                                "character": 21
                            },
                            "end": {
                                "line": 10,
                                "character": 21
                            }
                        }
                    },
                    "message": ""
                }
            ]
        },
        {
            "range": {
                "start": {
                    "line": 10,
                    "character": 21
                },
                "end": {
                    "line": 10,
                    "character": 21
                }
            },
            "severity": 4,
            "source": "oxc",
            "message": "",
            "relatedInformation": [
                {
                    "location": {
                        "uri": "file:///redacted/l.ts",
                        "range": {
                            "start": {
                                "line": 10,
                                "character": 18
                            },
                            "end": {
                                "line": 10,
                                "character": 18
                            }
                        }
                    },
                    "message": "original diagnostic"
                }
            ]
        }
    ],
    "version": 391
}
```

### PR DESCRIPTION
**Pull request by camchenry**
- fixes https://github.com/oxc-project/oxc/issues/9958
- reverts + fixes https://github.com/oxc-project/oxc/pull/9982

This PR fixes an issue where the "inverted diagnostics" (i.e., the hint spans converted into diagnostic reports) cause issues in VS Code because the spans are not labeled. This happens to be the case in `no-non-null-asserted-optional-chain`: there are two diagnostic spans, but neither is labeled. This ends up creating "empty" diagnostics which cause problems. So, the fix is to simply skip creating the full diagnostic report when the message content is empty. The better fix for the future is to ensure we always label spans, as this also results in more helpful error messages.

This also re-adds the testing code which was reverted previously. I've hopefully reduced the flakiness of these tests by replacing more of the file path content to a static value.

### CODE REVIEW

**Comment by camchenry** [comment]
* **#9991** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9991?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9991?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=9991).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_language_server/src/linter/tester.rs [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+impl Tester<'_> {
+    pub fn new() -> Self {
+        Self { snapshot_suffix: None, server_linter: ServerLinter::new() }
+    }
+
+    pub fn new_with_linter(linter: Linter) -> Self {
+        Self { snapshot_suffix: None, server_linter: ServerLinter::new_with_linter(linter) }
+    }
+
+    pub fn with_snapshot_suffix(mut self, suffix: &'static str) -> Self {
```
Comment (Sysix) [inline crates/oxc_language_server/src/linter/tester.rs:101]: can trhis be removed and used file names which describe the purpose of the test

File: crates/oxc_language_server/src/linter/tester.rs [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+
+use super::{error_with_position::DiagnosticReport, server_linter::ServerLinter};
+
+const CURRENT_DIR: &str = env!("CARGO_MANIFEST_DIR");
+
+/// Given a file path relative to the crate root directory, return the URI of the file.
+pub fn get_file_uri(relative_file_path: &str) -> Url {
+    let absolute_file_path = PathBuf::from(CURRENT_DIR).join(relative_file_path);
+    let file_path = format!("file://{}", absolute_file_path.display());
+    Url::parse(&file_path).unwrap()
```
Comment (Sysix) [inline crates/oxc_language_server/src/linter/tester.rs:12]: is it possible to remove the `file://` prefix and use `Url::from_file_path` instead?
Did not test my suggestion

File: crates/oxc_language_server/src/linter/tester.rs [hunk 3]
```diff
@@ -0,0 +1,131 @@
+use oxc_linter::Linter;
+use tower_lsp::lsp_types::Url;
+
+use super::{error_with_position::DiagnosticReport, server_linter::ServerLinter};
+
+const CURRENT_DIR: &str = env!("CARGO_MANIFEST_DIR");
```
Comment (Sysix) [inline crates/oxc_language_server/src/linter/tester.rs:6]: feels wierd to rely on `cargo` env. the `oxlint` app is using `env::current_dir()` in its `Tester`. Is it possible to do the same?

File: crates/oxc_language_server/src/linter/tester.rs (hunk 1 above)
Comment (camchenry) [reply crates/oxc_language_server/src/linter/tester.rs:101]: I think some form of this is necessary, as it allows us to test on the same file, but with different configurations in the linter or editor. This is just a wrapper of what `insta` natively supports

File: crates/oxc_language_server/src/linter/tester.rs (hunk 3 above)
Comment (camchenry) [reply crates/oxc_language_server/src/linter/tester.rs:6]: Yeah, that's fair. I had a thought that maybe this would be faster, but I'll just stick with what we do elsewhere for now.

File: crates/oxc_language_server/src/linter/tester.rs (hunk 2 above)
Comment (camchenry) [reply crates/oxc_language_server/src/linter/tester.rs:12]: Good idea, I didn't look too closely at what other `Url` methods were available, so I didn't know about this one, thanks for the suggestion.

**Comment by camchenry** [comment]
### Merge activity

* **Mar 23, 10:16 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
