### PR TITLE
fix(transfomer/using): remove use of child ids

### LINKED ISSUE #9744: transformer: `using` crashes
The following files crashes:

* https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/esbuild/lower/lower_async_generator/entry.ts
* https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/esbuild/lower/lower_async_generator_no_await/entry.ts
* https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/esbuild/lower/lower_using_inside_ts_namespace/entry.ts

### PR DESCRIPTION
**Pull request by camc314**
fixes #9744

### CODE REVIEW

**Comment by camc314** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9961?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#9961** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9961?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9961?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#9960** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9960?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=9961).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_traverse/src/context/scoping.rs [hunk 1]
```diff
@@ -193,6 +193,38 @@ impl TraverseScoping {
...
+        parent_id: ScopeId,
+        child_id: ScopeId,
+        flags: ScopeFlags,
+    ) -> ScopeId {
+        let scope_id = self.create_child_scope(parent_id, flags);
+
+        self.scoping.remove_child_scopes(parent_id, &[child_id]);
+        self.scoping.set_scope_parent_id(child_id, Some(scope_id));
+        scope_id
+    }
```
Comment (overlookmotel) [inline crates/oxc_traverse/src/context/scoping.rs:226]: Please add a "shortcut" method to `TraverseCtx` too.

It would be preferable to add a new method `remove_child_scope` (singular) to `Scoping`. That method can be more efficient than `remove_child_scopes` because it only needs to search the `Vec` of children up until it finds the `ScopeId` it's looking for, whereas `remove_child_scopes` uses `retain` which carries on looking for more matches even after its found the first - which is pointless because there can be only 1 match.

Then:

```diff
- self.scoping.remove_child_scopes(parent_id, &[child_id]);
+ self.scoping.remove_child_scope(parent_id, child_id);
```

There should probably be a `debug_assert!` in this method checking that `parent_id` is indeed the parent of `child_id`.

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs [hunk 2]
```diff
@@ -158,10 +158,31 @@ impl<'a> Traverse<'a> for ExplicitResourceManagement<'a, '_> {
...
-            block.body = ctx.ast.vec1(replacement);
+            let static_block_new_scope_id = ctx.scoping.insert_scope_between(
+                ctx.scoping().scope_parent_id(scope_id).unwrap(),
+                scope_id,
+                ScopeFlags::ClassStaticBlock,
+            );
+
+            ctx.scoping_mut().set_symbol_scope_id(using_ctx.symbol_id, static_block_new_scope_id);
+            ctx.scoping_mut().move_binding(scope_id, static_block_new_scope_id, &using_ctx.name);
+            ctx.scoping_mut().scope_flags_mut(scope_id).remove(ScopeFlags::ClassStaticBlock);
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/proposals/explicit_resource_management.rs:172]: I could be wrong, but I think this is equivalent, and would be slightly faster (unconditional write, instead of read + calculate + write):

```suggestion
            *ctx.scoping_mut().scope_flags_mut(scope_id) = ScopeFlags::StrictMode;
```

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs [hunk 3]
```diff
@@ -158,10 +158,31 @@ impl<'a> Traverse<'a> for ExplicitResourceManagement<'a, '_> {
...
+                SPAN,
+                ctx.ast.block_statement_with_scope_id(SPAN, new_stmts, scope_id),
+                Some(Self::create_catch_clause(&using_ctx, static_block_new_scope_id, ctx)),
+                Some(Self::create_finally_block(
+                    &using_ctx,
+                    static_block_new_scope_id,
+                    needs_await,
+                    ctx,
+                )),
+            ));
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/proposals/explicit_resource_management.rs:185]: This logic for creating a `try` statement is repeated in 4 places. Maybe move that logic into a method?

Also, unrelated to this PR, but I just noticed this:

https://github.com/oxc-project/oxc/blob/fd4b0c797467782714221ef6d6db0a1ce3b639c5/crates/oxc_transformer/src/proposals/explicit_resource_management.rs#L629-L631

Seems odd that it's `ctx.current_scope_id()` in one call and `current_scope_id` in the other. Shouldn't they be the same?

File: crates/oxc_traverse/src/context/scoping.rs (hunk 1 above)
Comment (overlookmotel) [reply crates/oxc_traverse/src/context/scoping.rs:226]: Also the call to `remove_child_scopes` can be gated with `if self.scoping.has_scope_child_ids() { ... }`.

Comment (camc314) [reply crates/oxc_traverse/src/context/scoping.rs:226]: yep this makes sense to me, will fix, thanks

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs (hunk 2 above)
Comment (camc314) [reply crates/oxc_transformer/src/proposals/explicit_resource_management.rs:172]: yep this is the same, will update

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs (hunk 3 above)
Comment (camc314) [reply crates/oxc_transformer/src/proposals/explicit_resource_management.rs:185]: in the switch stmt, they are the same - let me fix in a different PR.

i'll move the try logic to a fn

Comment (overlookmotel) [reply crates/oxc_transformer/src/proposals/explicit_resource_management.rs]: Thanks. #9966 is merged. Please let me know when this is ready for review again. I'll make it "draft" in meantime.

Comment (camc314) [reply crates/oxc_transformer/src/proposals/explicit_resource_management.rs]: i added it in here > https://github.com/oxc-project/oxc/blob/7dffe96703842d513e741f00ff23b5f9e645e174/crates/oxc_transformer/src/proposals/explicit_resource_management.rs#L724-L731

File: crates/oxc_semantic/src/scoping.rs [hunk 4]
```diff
@@ -677,6 +677,12 @@ impl Scoping {
         });
     }
 
+    pub fn remove_child_scope(&mut self, scope_id: ScopeId, child_scope_ids: ScopeId) {
```
Comment (overlookmotel) [inline crates/oxc_semantic/src/scoping.rs:680]:
```suggestion
    pub fn remove_child_scope(&mut self, scope_id: ScopeId, child_scope_id: ScopeId) {
```

File: crates/oxc_semantic/src/scoping.rs [hunk 5]
```diff
@@ -677,6 +677,12 @@ impl Scoping {
...
+        self.cell.with_dependent_mut(|_allocator, cell| {
+            cell.scope_child_ids[scope_id.index()].retain(|scope_id| *scope_id != child_scope_ids);
+        });
```
Comment (overlookmotel) [inline crates/oxc_semantic/src/scoping.rs:683]: What I was trying to say in previous comment is that this can be more efficient than `remove_child_scopes`, because you're only removing a single ID.

```rs
let child_ids = &mut cell.scope_child_ids[scope_id.index()];
let index = child_ids.iter().position(|&scope_id| scope_id == child_scope_id).unwrap();
child_ids.swap_remove(index);
```

Note that `retain` shifts up all following entries in the `Vec` (slow if there's lots of them), whereas `swap_remove` just moves 1 entry (same cheap cost, no matter how many entries in the `Vec`).

Warning: The `unwrap()` will panic if the `ScopeId` isn't found. That means this method must not be called unless the option to record child scope IDs is enabled. Method needs a comment to that effect.

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs [hunk 6]
```diff
@@ -700,21 +722,16 @@ impl<'a> ExplicitResourceManagement<'a, '_> {
...
+    }
 
-        Some(ctx.ast.statement_try(SPAN, block, Some(catch), Some(finally)))
+    fn create_try_stmt(
+        body: BlockStatement<'a>,
+        catch: ArenaBox<'a, CatchClause<'a>>,
+        finally: ArenaBox<'a, BlockStatement<'a>>,
+        ctx: &TraverseCtx<'a>,
+    ) -> Statement<'a> {
+        ctx.ast.statement_try(SPAN, body, Some(catch), Some(finally))
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/proposals/explicit_resource_management.rs:734]: I think more logic could be moved into this method - like generating the `CatchClause` and `finally` `BlockStatement` too. Unless I'm missing something, that logic looks identical across all the call sites too.

File: crates/oxc_semantic/src/scoping.rs (hunk 5 above)
Comment (camc314) [reply crates/oxc_semantic/src/scoping.rs:683]: ahhh i see, thanks for explaining

File: crates/oxc_transformer/src/proposals/explicit_resource_management.rs (hunk 6 above)
Comment (camc314) [reply crates/oxc_transformer/src/proposals/explicit_resource_management.rs]: yeah you're right. when i origannally looked, i thought there'd end up being a ton of args, but since the catch/finalizer are basically have the same args, it's not bad

**Review by Dunqing — APPROVED** [review]

**Comment by Dunqing** [comment]
I am merging this to unblock fixer from https://github.com/oxc-project/oxc/pull/10211, so without @overlookmotel further review.
