### PR TITLE
fix: don't lint files in .gitignore and .eslintignore

### LINKED ISSUE #1752: VSCode: don't lint files in .gitignore
i do not need my auto-generated build files to be linted.
if somebody wants to lint files in git-ignored files, they can use the CLI.

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed https://github.com/oxc-project/oxc/issues/1752

[录屏 2023年12月21日 18时14分38秒.webm](https://github.com/oxc-project/oxc/assets/17974631/8bbdddce-1d2b-4b37-9fbd-c36a4b626a13)

### CODE REVIEW

File: editors/vscode/server/src/main.rs [hunk 1]
```diff
@@ -236,20 +249,45 @@ impl LanguageServer for Backend {
...
+        let walk = ignore::WalkBuilder::new(uri.path()).ignore(true).hidden(false).git_global(false).build();
+        for item in walk.into_iter() {
+            if let Ok(entry) = item {
+                if ignore_file_glob_set.is_match(entry.path()) {
+                    gitignore_builder.add(entry.path());
+                }
+            }
+        }
+
+        *self.gitignore_glob.lock().await = gitignore_builder.build().ok();
```
Comment (Boshen) [inline editors/vscode/server/src/main.rs:284]: Let's move these new code to a function `init_file_ignore` into a function instead of dumping them here.

File: editors/vscode/server/src/main.rs [hunk 2]
```diff
@@ -236,20 +249,45 @@ impl LanguageServer for Backend {
...
+
+        let mut gitignore_builder = ignore::gitignore::GitignoreBuilder::new(uri.path());
+        let walk = ignore::WalkBuilder::new(uri.path()).ignore(true).hidden(false).git_global(false).build();
+        for item in walk.into_iter() {
+            if let Ok(entry) = item {
+                if ignore_file_glob_set.is_match(entry.path()) {
+                    gitignore_builder.add(entry.path());
+                }
+            }
+        }
```
Comment (Boshen) [inline editors/vscode/server/src/main.rs:282]: Take a look at https://github.com/oxc-project/oxc/blob/82dc4035ebc15fcbd898381392423197bbcd00ea/crates/oxc_cli/src/walk.rs#L71-L89

It feels like they are the same thing? 

Can you double check whether your code can be simplified to what's written in `walk.rs`?

**Review by Boshen — CHANGES_REQUESTED** [review]

File: editors/vscode/server/src/main.rs [hunk 3]
```diff
@@ -276,6 +314,16 @@ impl Backend {
             }
         }
     }
+
+    async fn is_ignored(&self, uri: &Url) -> bool {
+        // TODO: cache the result, for now it only cost a few us to calculate if the file is ignored by gitignore or .eslintignore
```
[the remark this answers is not in the document]
Comment (IWANABETHATGUY) [reply editors/vscode/server/src/main.rs:319]: the copilot adds it, I don't find the `match` is slow actually.

File: editors/vscode/server/src/main.rs (hunk 2 above)
Comment (IWANABETHATGUY) [reply editors/vscode/server/src/main.rs:290]: No,  two function usages are different, the `walk` function will traverse the whole file tree for every lint action, we can't get all ignore patterns from `Walk` which provided by `ignore` crate.  `init_ignore_blob` wants to collect all the `ignore` patterns only once when the server is initialized,

**Review by Boshen — APPROVED** [review]
