### PR TITLE
fix(linter): warning `eslint/no-throw-literal` rule to be deprecated, better use `typescript/only-throw-error`

### LINKED ISSUE #19537: linter: Difference in `eslint/no-throw-literal` violations vs. ESLint
### What version of Oxlint are you using?

1.48.0

### What command did you run?

`oxlint`

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "categories": {
    "correctness": "off",
  },
  "rules": {
    "no-throw-literal": "error"
  }
}
```

### What happened?

I discovered this difference with ESLint in the VS Code repo: https://github.com/microsoft/vscode/blob/fff291c416589b6c64585b595a05fc5046f9ce1d/extensions/terminal-suggest/src/fig/autocomplete-parser/parseArguments.ts#L1035-L1037

`extensions/terminal-suggest/src/fig/autocomplete-parser/parseArguments.ts:1036:10  no-throw-literal`

```ts
const parseArgumentsCached = async (): Promise<ArgumentParserState> => {
	// Route to cp.exec instead, we don't need to deal with ipc
	const exec = getExecuteShellCommandFunction(isParsingHistory, executeExternals);

	let currentCommand = command;
	let tokens = currentCommand.tokens.slice(startIndex);

	let aliasError: Error | undefined;

	for (let i = 1; i < tokens.length; i += 1) {
		if (aliasError) {
			throw aliasError;
		}
	}

	return state;
};
```

[ESLint Playground](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgcGFyc2VBcmd1bWVudHNDYWNoZWQgPSBhc3luYyAoXG4pOiBQcm9taXNlPEFyZ3VtZW50UGFyc2VyU3RhdGU+ID0+IHtcblx0Ly8gUm91dGUgdG8gY3AuZXhlYyBpbnN0ZWFkLCB3ZSBkb24ndCBuZWVkIHRvIGRlYWwgd2l0aCBpcGNcblx0Y29uc3QgZXhlYyA9IGdldEV4ZWN1dGVTaGVsbENvbW1hbmRGdW5jdGlvbihpc1BhcnNpbmdIaXN0b3J5LCBleGVjdXRlRXh0ZXJuYWxzKTtcblxuXHRsZXQgY3VycmVudENvbW1hbmQgPSBjb21tYW5kO1xuXHRsZXQgdG9rZW5zID0gY3VycmVudENvbW1hbmQudG9rZW5zLnNsaWNlKHN0YXJ0SW5kZXgpO1xuXG5cdGxldCBhbGlhc0Vycm9yOiBFcnJvciB8IHVuZGVmaW5lZDtcblxuXHRmb3IgKGxldCBpID0gMTsgaSA8IHRva2Vucy5sZW5ndGg7IGkgKz0gMSkge1xuXHRcdGlmIChhbGlhc0Vycm9yKSB7XG5cdFx0XHR0aHJvdyBhbGlhc0Vycm9yO1xuXHRcdH1cblx0fVxuXG5cdHJldHVybiBzdGF0ZTtcbn07Iiwib3B0aW9ucyI6eyJydWxlcyI6eyJuby10aHJvdy1saXRlcmFsIjpbImVycm9yIl19LCJsYW5ndWFnZU9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfSwic291cmNlVHlwZSI6Im1vZHVsZSJ9LCJlY21hVmVyc2lvbiI6MjAyNiwicGFyc2VyIjoiQHR5cGVzY3JpcHQtZXNsaW50L3BhcnNlciJ9fX0=)

[Oxc Playground](https://playground.oxc.rs/?lintRules=eslint%2Fno-throw-literal&code=const+parseArgumentsCached+%3D+async+%28%0A%29%3A+Promise%3CArgumentParserState%3E+%3D%3E+%7B%0A%09%2F%2F+Route+to+cp.exec+instead%2C+we+don%27t+need+to+deal+with+ipc%0A%09const+exec+%3D+getExecuteShellCommandFunction%28isParsingHistory%2C+executeExternals%29%3B%0A%0A%09let+currentCommand+%3D+command%3B%0A%09let+tokens+%3D+currentCommand.tokens.slice%28startIndex%29%3B%0A%0A%09let+aliasError%3A+Error+%7C+undefined%3B%0A%0A%09for+%28let+i+%3D+1%3B+i+%3C+tokens.length%3B+i+%2B%3D+1%29+%7B%0A%09%09if+%28aliasError%29+%7B%0A%09%09%09throw+aliasError%3B%0A%09%09%7D%0A%09%7D%0A%0A%09return+state%3B%0A%7D%3B)

### PR DESCRIPTION
**Pull request by Afsoon**
Fixes https://github.com/oxc-project/oxc/issues/19537

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/no_throw_literal.rs [hunk 1]
```diff
@@ -22,6 +22,9 @@ declare_oxc_lint!(
     ///
     /// Disallows throwing literals or non-Error objects as exceptions.
     ///
+    /// WARNING: This rule has been deprecated, please instead use [typescript/only-throw-error](https://oxc.rs/docs/guide/usage/linter/rules/typescript/only-throw-error.html).
+    /// The typescript rule is more reliable than the Javascript version, as it has less false positive, and can catch more cases.
```
Comment (camc314) [inline crates/oxc_linter/src/rules/eslint/no_throw_literal.rs]:
```suggestion
    /// ::: warning
    /// This rule has been deprecated, please instead use [typescript/only-throw-error](https://oxc.rs/docs/guide/usage/linter/rules/typescript/only-throw-error.html).
    /// The typescript rule is more reliable than the Javascript version, as it has less false positive, and can catch more cases.

**Review by camc314 — APPROVED** [review]
Thanks!

File: crates/oxc_linter/src/rules/eslint/no_throw_literal.rs [hunk 2]
```diff
@@ -22,6 +22,10 @@ declare_oxc_lint!(
     ///
     /// Disallows throwing literals or non-Error objects as exceptions.
     ///
+    /// ::: warning
+    /// This rule has been deprecated, please instead use [typescript/only-throw-error](https://oxc.rs/docs/guide/usage/linter/rules/typescript/only-throw-error.html).
+    /// The typescript rule is more reliable than the Javascript version, as it has less false positive, and can catch more cases.
+    ///
```
Comment (connorshea) [inline crates/oxc_linter/src/rules/eslint/no_throw_literal.rs:28]: Isn't this missing the closing `:::`?

Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_throw_literal.rs:28]: yep you're right - my fault

Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_throw_literal.rs:28]: Screenshot 2026-02-21 at 18 29 32

oops
