### PR TITLE
fix(linter): turn oxc/no-redundant-constructor-init into typescript/no-unnecessary-parameter-property-assignment

### LINKED ISSUE #9599: linter: redundant rule name
### What version of Oxlint are you using?

0.15.13

### What command did you run?

oxlint --rules

### What does your `.oxlintrc.json` config file look like?

None

### What happened?

A new rule was introduced in this version: no-redundant-constructor-init. The author thought it was something new, but in fact it is exactly what [`@typescript-eslint/no-unnecessary-parameter-property-assignment`](https://typescript-eslint.io/rules/no-unnecessary-parameter-property-assignment) does.

Ideally the new rule should be renamed.

### PR DESCRIPTION
**Pull request by ulrichstark**
Closes #9599

I switched the category to nursery because in a followup PR I will import all tests from typescript-eslint and attempt to fix all of them. This separation into two PRs makes the changes easier to review and preserves the history and original author of the lint rule.

### CODE REVIEW

File: crates/oxc_linter/src/rules/typescript/no_unnecessary_parameter_property_assignment.rs [hunk 1]
```diff
@@ -44,13 +45,13 @@ declare_oxc_lint!(
     ///   constructor(public name: unknown) {}
     /// }
     /// ```
-    NoRedundantConstructorInit,
-    oxc,
-    correctness,
+    NoUnnecessaryParameterPropertyAssignment,
+    typescript,
+    nursery, // TODO: import tests from typescript-eslint, fix them and change back to correctness
```
Comment (Boshen) [inline crates/oxc_linter/src/rules/typescript/no_unnecessary_parameter_property_assignment.rs:50]: Shall we try and get everything in and fixed before merging this PR?

Comment (ulrichstark) [reply crates/oxc_linter/src/rules/typescript/no_unnecessary_parameter_property_assignment.rs:50]: @Boshen Yes I can try, but there are two disadvantages when doing everything in one PR:

1. Git history and @BenShelton as author of the original lint rule are probably not preserved when squash merging this PR back into master. Before force pushing to remove the second commit, I had two commits (first renaming and second fixing basic tests from typescript-eslint) in this PR. When both were in this PR, even GitHub in the "Files changed" tab didn't detect the renaming of the file because it was substantially changed over some threshold mainly by the amount of new tests.
2. The new tests from typescript-eslint surfaced multiple issues of the current rule implementation. I already prepared some fixes to fix most tests. To fix all tests I need some more time as these are some more advanced test cases I don't yet know how to fix because I'm not (yet) very familiar with OXC's internals or AST.

That's why I prefer to keep the changes separated into two PRs. If you are fine with both possible disadvantages (loss of git history and this PR taking some more time until merge), I can continue working on this PR.

**Comment by Boshen** [comment]
Ok, let's do this in 2 PRs.
