### PR TITLE
fix(transformer/legacy-decorator): emit correct metadata types for enum

### LINKED ISSUE #13319: transformer: include inferred type for enums in the same module for `emitDecoratorMetadata`
For enums in the same module, TypeScript outputs the types in `__metadata` ([TS playground](https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&isolatedModules=true&verbatimModuleSyntax=true&useDefineForClassFields=true&noEmitHelpers=true#code/KYOwrgtgBA8gDgFwJYHsQGcoG8BQUoBmKKUAvFAOToIBOSIA5hTgL447AAecKNCUAYwA2AQ3SYAYsWx4oAAQAmwAbxEJgACgCUsoig0pEqDAC5YRtOi1n4yS9jazFy1eu2yARiJo2LGVjhAA), in this case `String`) even for `isolatedModules: true`.
```ts
enum Options {
  foo = 'string'
}

export class Foo {
  @decorate()
  foo(options: Options): Options {}

  @decorate()
  bar: Options
}
```
But Oxc does not output the types and falls back to the generic `typeof (_ref = typeof Options !== "undefined" && Options) === "function" ? _ref : Object` ([reproduction using transform function exposed from rolldown](https://stackblitz.com/edit/github-xv4yss-fvqn9tsn?file=package.json,build.mjs)).

### PR DESCRIPTION
**Pull request by Dunqing**
* close:  #13319

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#13346** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13346?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#13327** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13327?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13327?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=13327).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 1]
```diff
@@ -201,6 +224,74 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
...
 impl<'a> LegacyDecoratorMetadata<'a, '_> {
+    /// Collects enum type information for decorator metadata generation.
+    fn collect_enum_type(&mut self, decl: &TSEnumDeclaration<'a>, ctx: &TraverseCtx<'a>) {
+        let symbol_id = decl.id.symbol_id();
+
+        // Optimization:
+        // If the enum doesn't have any type references, it is said that no decorator will
+        // refer to this enum, so there is no need to infer its type.
+        let has_type_reference =
+            ctx.scoping().get_resolved_references(symbol_id).any(Reference::is_type);
```
[the remark this answers is not in the document]
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs:241]: We can't cache it, and we only look it up once for each enum.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 2]
```diff
@@ -111,15 +123,26 @@ pub enum MethodMetadata<'a> {
...
+        }
     }
 }
 
 impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
+    fn enter_statement(&mut self, node: &mut Statement<'a>, ctx: &mut TraverseCtx<'a>) {
+        if let Statement::TSEnumDeclaration(decl) = node {
+            self.collect_enum_type(decl, ctx);
+        }
+    }
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Any reason not to use `enter_ts_enum_declaration` here?

```suggestion
    fn enter_ts_enum_declaration(&mut self, decl: &mut TSEnumDeclaration<'a>, ctx: &mut TraverseCtx<'a>) {
        self.collect_enum_type(decl, ctx);
    }
```

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 3]
```diff
@@ -201,6 +224,71 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
 }
 
 impl<'a> LegacyDecoratorMetadata<'a, '_> {
+    /// Collects enum type information for decorator metadata generation.
+    fn collect_enum_type(&mut self, decl: &TSEnumDeclaration<'a>, ctx: &TraverseCtx<'a>) {
+        let symbol_id = decl.id.symbol_id();
+
+        // Optimization:
+        // If the enum doesn't have any type references, it is said that no decorator will
+        // refer to this enum, so there is no need to infer its type.
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]:
```suggestion
        // If the enum doesn't have any type references, that implies that no decorators
        // refer to this enum, so there is no need to infer its type.
```

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 4]
```diff
@@ -201,6 +224,71 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
...
+            ctx.scoping().get_resolved_references(symbol_id).any(Reference::is_type);
+        if has_type_reference {
+            let enum_type = Self::infer_enum_type(&decl.body.members);
+            self.add_enum_type(symbol_id, enum_type);
+        }
+    }
+
+    fn add_enum_type(&mut self, symbol_id: SymbolId, enum_type: EnumType) {
+        self.enum_types.insert(symbol_id, enum_type);
+    }
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Style nit: This function is only 1 line. You could inline it into `collect_enum_type`.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 5]
```diff
@@ -201,6 +224,71 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
...
+                        has_number = true;
+                    }
+                    // For other expressions, we can't determine the type statically
+                    _ => {
+                        return EnumType::Object;
+                    }
+                }
+            } else {
+                // No initializer means numeric (auto-incrementing from previous member)
+                has_number = true;
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: You could bail out early and return `EnumType::Object` here if `has_string == true`.

Then the whole function could be simplified, replacing `has_string` and `has_number` with just `enum_type`:

```rs
let mut enum_type = EnumType::Object;
for member in members {
    if let Some(init) = &member.initializer {
        match init {
            Expression::StringLiteral(_) if enum_type != EnumType::Number => {
                enum_type = EnumType::String;
            }
            // ...
            _ => return EnumType::Object,
        }
    } else {
        // No initializer means numeric (auto-incrementing from previous member)
        if enum_type == EnumType::String {
            return EnumType::Object;
        }
        enum_type = EnumType::Number;
    }
}
enum_type
```

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 6]
```diff
@@ -201,6 +224,71 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
...
+                match init {
+                    Expression::StringLiteral(_) if !has_number => {
+                        has_string = true;
+                    }
+                    Expression::TemplateLiteral(literal)
+                        if !has_number
+                            && literal
+                                .expressions
+                                .iter()
+                                .all(|expr| matches!(expr, Expression::StringLiteral(_))) =>
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Is it relevant what type the `expressions` are? All `TemplateLiteral`s evaluate to a string, no matter what the expressions are.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 7]
```diff
@@ -350,6 +438,20 @@ impl<'a> LegacyDecoratorMetadata<'a, '_> {
         name: &TSTypeName<'a>,
         ctx: &mut TraverseCtx<'a>,
     ) -> Expression<'a> {
+        // Check if this is an enum type reference - if so, return the primitive type directly
+        if let TSTypeName::IdentifierReference(ident) = name {
+            let binding = MaybeBoundIdentifier::from_identifier_reference(ident, ctx);
+            if let Some(symbol_id) = binding.symbol_id {
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: `MaybeBoundIdentifier` is overkill here.

```suggestion
            let symbol_id = ctx.scoping().get_reference(ident.reference_id()).symbol_id();
            if let Some(symbol_id) = symbol_id {
```

If `MaybeBoundIdentifier::from_identifier_reference` is inlined, it will make no difference, but I'm not sure if it will be inlined.

File: crates/oxc_transformer/src/decorator/mod.rs [hunk 8]
```diff
@@ -81,6 +87,17 @@ impl<'a> Traverse<'a, TransformState<'a>> for Decorator<'a, '_> {
...
+    #[inline]
+    fn enter_ts_enum_declaration(
+        &mut self,
+        node: &mut TSEnumDeclaration<'a>,
+        ctx: &mut TraverseCtx<'a>,
+    ) {
+        if self.options.legacy {
+            self.legacy_decorator.enter_ts_enum_declaration(node, ctx);
+        }
+    }
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/mod.rs]: This code is extraneous. There is no `enter_ts_enum_declaration` method on `LegacyDecorator` (though I suggest switching `enter_statement` for `enter_ts_enum_declaration` - see comment above).

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs [hunk 9]
```diff
@@ -201,6 +224,71 @@ impl<'a> Traverse<'a, TransformState<'a>> for LegacyDecoratorMetadata<'a, '_> {
...
+                        has_string = true;
+                    }
+                    Expression::NumericLiteral(_) | Expression::BigIntLiteral(_) if !has_string => {
+                        has_number = true;
+                    }
+                    Expression::UnaryExpression(expr)
+                        if expr.argument.is_number_literal() && !has_string =>
+                    {
+                        has_number = true;
+                    }
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Not all `UnaryExpression`s evaluate to a number. It depends on the operator:

* `!123` -> boolean
* `typeof 123` -> string
* `void 123` -> undefined
* `delete 123` -> boolean

The first one is not entirely stupid - `!0` and `!1` are sometimes used as shortcuts for `true` / `false`.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 2 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: The TypeScript plugin transforms enums in `enter_statement`, but we need to collect enum types before the transformation occurs.

https://github.com/oxc-project/oxc/blob/6ff27b4d31ff2520836d3c046df90b01c1f68c4f/crates/oxc_transformer/src/typescript/enum.rs#L38-L40

File: crates/oxc_transformer/src/decorator/mod.rs (hunk 8 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/mod.rs:100]: See https://github.com/oxc-project/oxc/pull/13327#discussion_r2307026118

Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/mod.rs]: I forgot to remove this.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 2 above)
Comment (overlookmotel) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Ah ha! Makes sense. Maybe add a comment explaining that?

Comment (overlookmotel) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: It may be a benefit to add `#[inline]`. Most statements aren't `TSEnumDeclaration`s, so want to handle the common case without a function call. (compiler may have chosen to inline it already, but probably best to make sure)

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 9 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Good catch, I forgot the importance of the operator. In this case, we only care about `+`, `-` and `~`. For the `typeof 123`, it isn't allowed. See [TypeScript Playground](https://www.typescriptlang.org/play/?strict=false&useDefineForClassFields=true&noEmitHelpers=true&experimentalDecorators=true&emitDecoratorMetadata=true&isolatedModules=false&verbatimModuleSyntax=false#code/KYOwrgtgBA8gDgFwJYHsQGcoG8BQUoBmKKUAvFAgJ5zAoFQCCOOAvs8AB5woBOCUAYwA2AQ3SYAYsWx4oAAQAmwAbxEJgACgCUsoig0pEqDAC5YRtOi1n4yS9jazFy1eu2yARiJ42LGVjhAA)

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 5 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Wow, sounds good!

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 6 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: Yes, you are right, I misunderstood this.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 2 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: I added a comment and marked it as `#[inline]`.

File: crates/oxc_transformer/src/decorator/legacy/metadata.rs (hunk 9 above)
Comment (overlookmotel) [reply crates/oxc_transformer/src/decorator/legacy/metadata.rs]: > For the `typeof 123`, it isn't allowed. See [TypeScript Playground](https://www.typescriptlang.org/play/?strict=false&useDefineForClassFields=true&noEmitHelpers=true&experimentalDecorators=true&emitDecoratorMetadata=true&isolatedModules=false&verbatimModuleSyntax=false#code/KYOwrgtgBA8gDgFwJYHsQGcoG8BQUoBmKKUAvFAgJ5zAoFQCCOOAvs8AB5woBOCUAYwA2AQ3SYAYsWx4oAAQAmwAbxEJgACgCUsoig0pEqDAC5YRtOi1n4yS9jazFy1eu2yARiJ42LGVjhAA)

Ah ha. Does this mean we can assume any computed expression (e.g. `foo()`) evaluates to a number?

But maybe the gain of that is not worth the trouble. Some more complex expressions that evaluate to strings seem to be allowed e.g. `enum E { X = 'foo' + 'bar' + 'qux' }`. So we'd need to handle those to accurately determine whether string or number.

**Review by overlookmotel — APPROVED** [review]
Pushed a commit just to update the comment about `#[inline]` - hope you don't mind, I thought it'd save time vs another round of review. Will merge as soon as CI passes.
