### PR TITLE
fix(cli): fix `oxlint --format json` yields 0 files to lint

### LINKED ISSUE #2930: No output when passing `--format json`
Hey hey, great job on oxlint! I was testing it out and I noticed that when I pass `--format json`, I don't get any output even though I do get some without the flag. I.e.

```
> npx oxlint -D all
Finished in 6ms on 15 files with 232 rules using 8 threads.
Found 119 warnings and 0 errors.
```

vs

```
> npx oxlint -D all --format json
Finished in 0ms on 0 files with 232 rules using 8 threads.
Found 0 warnings and 0 errors.
```

Here's a [repro](https://github.com/NicholasLYang/oxlint-repro), try running `npm run oxlint` vs `npm run oxlint:json`.

Thanks in advance!

### PR DESCRIPTION
**Pull request by Boshen**
closes #2930

### CODE REVIEW

**Comment by Boshen** [comment]
* **#2940** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2940?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Boshen and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_cli/src/command/lint.rs [hunk 1]
```diff
@@ -147,6 +146,16 @@ pub enum OutputFormat {
     Json,
 }
 
+impl FromStr for OutputFormat {
+    type Err = String;
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        Ok(match s {
+            "json" => Self::Json,
+            _ => Self::Default,
```
Comment (pacak) [inline crates/oxc_cli/src/command/lint.rs:154]: I'd do something like
```rust
Ok(match s {
    "json" => Self::Json,
    "default" => Self::Default,
    _ => return Err(format!("{s:?} is not a known format")),
})
```

This would make it so `--format json` and `--format default` are accepted but `--format pancake` is rejected.

Comment (Boshen) [reply crates/oxc_cli/src/command/lint.rs:154]: Thank you! I totally missed it. Landed in c250b28.
