### PR TITLE
fix(transformer/typescript): typescript syntax within `SimpleAssignmentTarget` with `MemberExpressions` is not stripped

### LINKED ISSUE #4870: transformer: typescript syntax inside `SimpleAssignmentTarget` is not stripped
```rust
pub enum SimpleAssignmentTarget<'a> {
    AssignmentTargetIdentifier(Box<'a, IdentifierReference<'a>>) = 0,
    TSAsExpression(Box<'a, TSAsExpression<'a>>) = 1,
    TSSatisfiesExpression(Box<'a, TSSatisfiesExpression<'a>>) = 2,
    TSNonNullExpression(Box<'a, TSNonNullExpression<'a>>) = 3,
    TSTypeAssertion(Box<'a, TSTypeAssertion<'a>>) = 4,
    TSInstantiationExpression(Box<'a, TSInstantiationExpression<'a>>) = 5,
    // `MemberExpression` variants added here by `inherit_variants!` macro
    @inherit MemberExpression
}
```

There is not `Expression` here, it's not covered in the transformer visiter.

Test case would be for example `x!++`.

or transformer typescript case:
```
Mismatch: "compiler/incrementOnNullAssertion.ts"
```

### PR DESCRIPTION
**Pull request by Dunqing**
close: #4870

I added the `move_identifier_reference` and `move_member_expression` methods used to take ownership in `ast_builder_impl`.  This way can let us get rid of `ast.copy`.

Another possible approach is to add `get_expression_owner` to `SimpleAssignmentTarget` and a `get_inner_expression_owner` method to `Expression`. And add an `into_xxxxx` method for `inherit_variants` macro

The implementation looks like this
```rs
let Some(expression) = self.get_expression_owner() else { return; }
match expr.get_inner_expression_owner() {
    Expression::Identifier(ident) => {
        *target = self.ctx.ast.simple_assignment_target_from_identifier_reference(ident);
    }
    inner_expr @ match_member_expression!(Expression) => {
        *target = SimpleAssignmentTarget::from(
            inner_expr.into_member_expression()
        );
    }
    _ => (),
}
```

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#4920** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4920?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_transformer/src/typescript/annotations.rs [hunk 1]
```diff
@@ -222,11 +222,23 @@ impl<'a> TypeScriptAnnotations<'a> {
...
+                        self.ctx.ast.move_identifier_reference(ident),
+                    );
+                }
+                // `foo.bar!++` to `foo.bar++`
+                inner_expr @ match_member_expression!(Expression) => {
+                    *target = SimpleAssignmentTarget::from(
+                        self.ctx.ast.move_member_expression(inner_expr.to_member_expression_mut()),
+                    );
+                }
+                _ => unreachable!(
```
Comment (Boshen) [inline crates/oxc_transformer/src/typescript/annotations.rs:239]: It's probably better to push an error and bail, the AST may be dirty here :-/

Comment (Dunqing) [reply crates/oxc_transformer/src/typescript/annotations.rs:239]: Sounds reasonable
