### PR TITLE
fix(transformer/typescript): correctly resolve references to non-constant enum members

### LINKED ISSUE #8342: transformer: tsc vs babel on enum transformation
### Discussed in https://github.com/oxc-project/oxc/discussions/8341

<div type='discussions-op-text'>

<sup>Originally posted by **branchseer** January  8, 2025</sup>
oxc-transform currently follows babel's rules on enum transformation. IMHO it's a little bit weird about whether an identifier should be resolved to the enum member:

https://playground.oxc.rs/#eNqNkcFqwzAMhl9F+NIEwroOdunooD0Udhh7gVycREkNjlRsp11X8u6Tk6UbXRk7+Zcs/f+HfValWqqckiSF1TOccwI4aAdrWMFsh9by7Cn2kLoWtszjBAz3i2zUG9HrDOZz6RoPDj3bA1YQGMIOx9UW2wIdmBpMmHkomXzQFKJBn1OfJqnE/BNjIxc/MF512N05TRW3SfoL6U0Q3NF4zGRYiK7puAvC5Uveo3AVhipDzTVWTl/BH2Pw7djv0Jc6ervoSHw7IhsfQjfa0F9PJhQ5qUyxWp6V6yge/kRBv6tlcB1myhoKkx5CLsWpLdhOVRBWX7Nrx0afqb12Hp0Yio4mk75MDg0VtGtQEhT6h/vFo5KJkitsMLJI0RoytZmW5WeDY7u1fIzLB3QFe0GqtfXY9/0nDIDKdw==

In contrast, tsc has a simpler rule:

https://www.typescriptlang.org/play/?#code/PTAEEFQSwZ1BDANgd3gTzgJwKYwPaIBu2AJqAC54UAW2o2AdgK4C2oL2LARtpgHQAoIQAphASlABeAHygA3gNChC8TBCmgA5AHNEeLkk0BuRfWZsAYnioKlSyJNABGADSmlAIQ3gXoUwF8BfzFxEwFRCRl5UxU1By1dfUMTJUZWUA9VaLt1RwBZeHJqPkx4BhI8FnE3HK9HHwCgkLEwgTS2TIAvbNzQAqKSsoqqsRqM7zdAoA

Would it be better to switch to tsc's rule?

</div>

### PR DESCRIPTION
**Pull request by wan9chi**
fixes #8342

### CODE REVIEW

File: crates/oxc_transformer/src/typescript/enum.rs [hunk 1]
```diff
@@ -199,44 +205,34 @@ impl<'a> TypeScriptEnum<'a> {
...
-                        if !has_binding {
-                            IdentifierReferenceRename::new(
-                                param_binding.name.clone(),
-                                previous_enum_members.clone(),
-                                ctx,
-                            )
-                            .visit_expression(&mut new_initializer);
-                        }
+                        IdentifierReferenceRename::new(
+                            param_binding.name.clone(),
```
Comment (branchseer) [inline crates/oxc_transformer/src/typescript/enum.rs:217]: Question: any reason not making `Atom` implements `Copy`? `.clone()` always makes me feel the operation is somewhat expensive.

Comment (overlookmotel) [reply crates/oxc_transformer/src/typescript/enum.rs:217]: I agree. https://github.com/oxc-project/backlog/issues/155

Originally we were considering some form of interning and reference-counting, so we didn't make it `Copy` to leave the door open for that. But now all strings are stored in the arena anyway, so even if we did decide to intern strings, reference-counting would be irrelevant.

**Comment by overlookmotel** [comment]
@Dunqing You wrote this transform and are more familiar with it. Would you be able to review please?

File: crates/oxc_transformer/src/typescript/enum.rs (hunk 1 above)
Comment (overlookmotel) [reply crates/oxc_transformer/src/typescript/enum.rs:217]: A PR would be very welcome. But it'd be boring as hell to do! *So many* `.clone()`s to remove!

Comment (branchseer) [reply crates/oxc_transformer/src/typescript/enum.rs:217]: Thanks for both the answer and the backlog link! There are lots of interesting readings over there:)

Comment (overlookmotel) [reply crates/oxc_transformer/src/typescript/enum.rs:217]: Yeah, it's kind of our "brain dump". We try to keep main issue tracker just for stuff which is being worked on currently, to keep things manageable. But if there's anything in backlog that interests you, please ping me on our [Discord](https://discord.gg/9uXCAwqQZW) and I'll transfer the issue over to main repo so we can discuss.

File: crates/oxc_transformer/src/typescript/enum.rs [hunk 2]
```diff
@@ -527,56 +525,68 @@ impl<'a> TypeScriptEnum<'a> {
...
+            enum Foo {
+                A,
+                B = (() => {
+                    const A = 1;
+                    return A;
+                })())
+            } */
+            return false;
+        }
+        true
```
[the remark this answers is not in the document]
Comment (Dunqing) [reply crates/oxc_transformer/src/typescript/enum.rs:575]: It looks like as long as the identifier reference refers to an enum member, then we need to transform it, do I understand correctly? If so we only need to check the symbol flags if it is an `EnumMember`.  Please see [OXC Playground]( https://playground.oxc.rs/#eNo9TzFuwzAM/ArByQY8JAW6uEgBZ8grvCguHRiQyYCS2waG/h7KiaxBujvxjuSKA7ZIvMxwEYG1Z4CuyfcZTlBVNZy+X2o+g3CI0NnP8atoSnFRhm4TUl3VPSfouect9Oz0HWqmwx6cWyRsULBdURfOT3hwdP/YRl2oQT9xLDgMcqedPOar+MKiOg6j6PwSUoN3p4HUAg3nkIL3yk3A6PRG1gEpfByOn2gVg/zQjfIsRuaJp3EqZls8qviLl79s/iW9SrCRRucDpZSe7xBo8w==), and switch to the `Symbol` panel, you will see `Foo`'s flag is `EnumMember`.

File: crates/oxc_transformer/src/typescript/enum.rs [hunk 3]
```diff
@@ -527,56 +525,68 @@ impl<'a> TypeScriptEnum<'a> {
...
+            return true;
+        }
+        if ancestors.any(|scope_id| scope_id == self.enum_scope_id) {
+            /* The symbol is declared inside enum:
+            enum Foo {
+                A,
+                B = (() => {
+                    const A = 1;
+                    return A;
+                })())
```
Comment (Dunqing) [inline crates/oxc_transformer/src/typescript/enum.rs:571]:
```suggestion
                })()
```

**Review by Dunqing — CHANGES_REQUESTED** [review]
It looks great overall, we can make further improvements after https://github.com/oxc-project/oxc/issues/8350 is done!

File: crates/oxc_transformer/src/typescript/enum.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (branchseer) [reply crates/oxc_transformer/src/typescript/enum.rs]: > It looks like as long as the identifier reference refers to an enum member, then we need to transform it, do I understand correctly?

Yes that's the rule I want to implement. 

> If so we only need to check the symbol flags if it is an EnumMember.

The `EnumMember` flag seems not sufficient if there's a nested enum ([playground](https://playground.oxc.rs/#eNo9jtFqwzAMRX9F6GUJhHUt7CXQQfrQryijbqq0AVsqsrOtBP/77ATXL7pXPlfSjD22SDw5OIrAfGKADvawbbI6JFVVNey/1h+AhTwYLX6ldwudX050DRS72QB8g7/LZK/8FkCJjSMI99FDEDinne/deaVjLrGu6hMniQ0KtjPqxLn4Jwfzh23QiRq0I4eifS8Pepmnu4gtLqhhP4i6tREbfBj1pGlg0nlI0S9yaWAweqO0AcnvPrafmIhernSjfEsybuRxGEu4Fw4q9mjlN4d/SC/i00mDsZ5ijP8qY3AG)).

But you remind me that it's the symbol's scope we're checking with, not the reference's, so no need to go through the ancestors (I was confused with the [fix for babel](https://github.com/babel/babel/blob/4b2608b4fc240038a731428b249d3ab53acda735/packages/babel-plugin-transform-typescript/src/enum.ts#L178-L181)). A 
 simple comparison with the enum's scope id should suffice.

[the remark this answers is not in the document]
Comment (Dunqing) [reply crates/oxc_transformer/src/typescript/enum.rs]: > The `EnumMember` flag seems not sufficient if there's a nested enum ([playground](https://playground.oxc.rs/#eNo9jtFqwzAMRX9F6GUJhHUt7CXQQfrQryijbqq0AVsqsrOtBP/77ATXL7pXPlfSjD22SDw5OIrAfGKADvawbbI6JFVVNey/1h+AhTwYLX6ldwudX050DRS72QB8g7/LZK/8FkCJjSMI99FDEDinne/deaVjLrGu6hMniQ0KtjPqxLn4Jwfzh23QiRq0I4eifS8Pepmnu4gtLqhhP4i6tREbfBj1pGlg0nlI0S9yaWAweqO0AcnvPrafmIhernSjfEsybuRxGEu4Fw4q9mjlN4d/SC/i00mDsZ5ijP8qY3AG)).
>

It still will work, you can see 
https://github.com/oxc-project/oxc/blob/8dd0013e7220ac9460cb99f1d6ce864da77502a4/crates/oxc_transformer/src/typescript/enum.rs#L547-L556

Here can cover `A` to  `Foo.A`. So I prefer to check symbol flags over scope id because you don't need to pass `enum_scope_id` to here, and using `SymbolFlags` will be clear than scope id.


> But you remind me that it's the symbol's scope we're checking with, not the reference's, so no need to go through the ancestors (I was confused with the [fix for babel](https://github.com/babel/babel/blob/4b2608b4fc240038a731428b249d3ab53acda735/packages/babel-plugin-transform-typescript/src/enum.ts#L178-L181)). A simple comparison with the enum's scope id should suffice.
> 
> Updated in [aec2efc](https://github.com/oxc-project/oxc/commit/aec2efc1c1eb77e1c1dfa0ffdceb6444867ae437) (I assume all symbols declared in a enum's scope are `EnumMember`. Is that correct?)

That's correct!

[the remark this answers is not in the document]
Comment (branchseer) [reply crates/oxc_transformer/src/typescript/enum.rs]: Just to be clear about that nested enum [example](https://playground.oxc.rs/#eNo9jtFqwzAMRX9F6GUJhHUt7CXQQfrQryijbqq0AVsqsrOtBP/77ATXL7pXPlfSjD22SDw5OIrAfGKADvawbbI6JFVVNey/1h+AhTwYLX6ldwudX050DRS72QB8g7/LZK/8FkCJjSMI99FDEDinne/deaVjLrGu6hMniQ0KtjPqxLn4Jwfzh23QiRq0I4eifS8Pepmnu4gtLqhhP4i6tREbfBj1pGlg0nlI0S9yaWAweqO0AcnvPrafmIhernSjfEsybuRxGEu4Fw4q9mjlN4d/SC/i00mDsZ5ijP8qY3AG), `A` at line 6 should refer to `Bar.A`. If I only check its `EnumMember` flag while transforming enum `Foo`, I would incorrectly resolve it to `Foo.A` because I can't tell which enum it belongs to without the enum's scope id. The `match_member_expression` arm can't solve this, can it?

[the remark this answers is not in the document]
Comment (Dunqing) [reply crates/oxc_transformer/src/typescript/enum.rs]: Oh, I got it, you are right!

**Review by Dunqing — APPROVED** [review]
Thanks for working on this!
