### PR TITLE
fix(transformer/styled-components): preserve spaces between consecutive interpolations in CSS minification

### LINKED ISSUE #13312: Styled components minifier issues
Reproduced in vite-rolldown@7.1.5, which seems to be the first version sending down `oxc.plugins.styledComponents.minify` to oxc.

### Reproduction

In the vite.config file you can try enabling the babel transformer. Unfortunately I didn't have time to make the bug visual, but you can inspect the generated index-x.js file after running `pnpm build`.

https://stackblitz.com/edit/github-1mwpshrf-seqaur7l?file=vite.config.ts,src%2Fmain.tsx,index.html

### Input

Some styled components using code like this:

```css
  @media (hover: hover) {
    &:hover ${SidebarDragHandle} {
      display: inline-block;
    }

    &:hover ${RightSideWrapper} ${StyledRemoveButton} {
      opacity: 0;
    }

    &:hover ${StyledRemoveButton}, & ${RightSideWrapper}:hover ${StyledRemoveButton} {
      opacity: 1;
    }
  }
```

### Expected (babel output)
```ts
  i(`div`).withConfig({ displayName: `main__Wrapper` })(
    [
      `position:relative;display:block;`,
      `{opacity:0;}border:1px black solid;@media (hover:hover){&:hover `,
      `{display:inline-block;}&:hover `,
      ` `,
      `{opacity:0;}&:hover `,
      `,& `,
      `:hover `,
      `{opacity:1;}}`,
    ],
```

This ends up runtime as `  "@media (hover: hover) {\n  .bpotXz:hover .main__SidebarDragHandle-ipuvAi { display: inline-block; }\n  .bpotXz:hover .main__RightSideWrapper-lfvplS .main__StyledRemoveButton-kTrOxN { opacity: 0; }\n  .bpotXz:hover .main__StyledRemoveButton-kTrOxN, .bpotXz .main__RightSideWrapper-lfvplS:hover .main__StyledRemoveButton-kTrOxN { opacity: 1; }\n}",
`

### Actual (oxc output)
```ts
  i(`div`).withConfig({ displayName: `main__Wrapper` })(
    [
      `position:relative;display:block;`,
      `{opacity:0;}border:1px black solid;@media (hover:hover){&:hover `,
      `{display:inline-block;}&:hover `,
      ``, // NOTE: the missing space
      `{opacity:0;}&:hover `,
      `,& `,
      `:hover `,
      `{opacity:1;}}`,
    ],
```

Runtime this break with `  "@media (hover: hover) {\n  .jGDmYv:hover .main__SidebarDragHandle-ipuvAi { display: inline-block; }\n  .jGDmYv:hover .main__RightSideWrapper-lfvplS.main__StyledRemoveButton-kTrOxN { opacity: 0; }\n  .jGDmYv:hover .main__StyledRemoveButton-kTrOxN, .jGDmYv .main__RightSideWrapper-lfvplS:hover .main__StyledRemoveButton-kTrOxN { opacity: 1; }\n}",
`

Notice the missing space between `lfvplS` and `.main`

### PR DESCRIPTION
**Pull request by Dunqing**
Fixes #13312

When minifying CSS in styled-components, spaces between consecutive interpolations were incorrectly removed, breaking CSS selectors.

**Before:** `&:hover ${A}${B}` (incorrect - space removed)
**After:** `&:hover ${A} ${B}` (correct - space preserved)

The fix modifies the whitespace handling logic to preserve spaces between consecutive interpolations while still removing unnecessary spaces elsewhere.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#13346** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13346?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13346?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#13327** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/13327?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=13346).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_transformer/src/plugins/styled_components.rs [hunk 1]
```diff
@@ -1062,20 +1062,36 @@ fn minify_template_literal<'a>(lit: &mut TemplateLiteral<'a>, ast: AstBuilder<'a
...
+                    )
+                    // AND check what comes after this whitespace:
+                    // - If we're at the end of the quasi (i == bytes.len()), preserve the space
+                    //   to avoid joining with the next interpolation
+                    // - Otherwise, only preserve if the next char is NOT one of: { } , ;
+                    //   Note: We intentionally DON'T include ':' here because spaces before colons
+                    //   are significant in CSS. ` :hover` (descendant pseudo-selector) is different
+                    //   from `:hover` (direct pseudo-selector). Example: `.parent :hover` selects any
+                    //   hovered descendant, while `.parent:hover` selects the parent when hovered.
+                    && (i == bytes.len() || !matches!(bytes[i], b'{' | b'}' | b',' | b';'))
```
Comment (overlookmotel) [inline crates/oxc_transformer/src/plugins/styled_components.rs]: I'm not completely sure, but could we omit this whitespace character if next char is whitespace too?

```suggestion
                    && bytes.get(i).is_none_or(|&b| {
                        !b.is_ascii_whitespace() && !matches!(b, b'{' | b'}' | b',' | b';')
                    })
```

It would make a difference in a case like `something:     {`. All those spaces can be removed, but currently we leave 1 space I think.

**Review by overlookmotel — APPROVED** [review]

File: crates/oxc_transformer/src/plugins/styled_components.rs (hunk 1 above)
Comment (Dunqing) [reply crates/oxc_transformer/src/plugins/styled_components.rs]: I applied the suggestion, and it is clearer now! For `something:    {`, is there an example that has this syntax? I can't remember.

Comment (overlookmotel) [reply crates/oxc_transformer/src/plugins/styled_components.rs]: Updated version doesn't handle whitespace after. But I'm also not sure what patterns this would cover exactly. I'll try it out and do a follow-up PR.

**Comment by overlookmotel** [comment]
### Merge activity

* **Aug 28, 5:09 PM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Aug 28, 5:09 PM UTC**: `overlookmotel` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
* **Aug 28, 5:15 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
