### PR TITLE
fix(linter): output right file line and column for `.vue`, `.astro` and `.svelte` files

### LINKED ISSUE #9333: linter: Mismatched line numbers for `<script>` content
### What version of Oxlint are you using?

0.15.12

### What command did you run?

`oxlint-win32-x64.exe t.vue`

### What does your `.oxlintrc.json` config file look like?

N/A

### What happened?

Given this `t.vue` file:

```vue
<template>
    <h1>Hello, Vue!</h1>
    <slot />
</template>

<script>
defineProps({
    title: {
        type: String,
        default: "Test Page"
    }
})
debugger;
</script>
```

Oxlint reports wrong line number:
```
  ⚠ eslint(no-debugger): `debugger` statement is not allowed
   ╭─[t.vue:8:1]
 7 │ })
 8 │ debugger;
   · ─────────
   ╰────
```

It should report this issue for line `13` instead. Now it treats `<script>` tag as the starting point.

Same issue applies for `<script>` tags in astro and svelte files.

### PR DESCRIPTION
**Pull request by Sysix**
closes #9333

### CODE REVIEW

**Comment by Sysix** [comment]
* **#9484** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9484?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9484?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=9484).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_diagnostics/src/service.rs [hunk 1]
```diff
@@ -140,8 +143,23 @@ impl DiagnosticService {
...
+                    LabeledSpan::new(
+                        labeled_span.label().map(std::string::ToString::to_string),
+                        labeled_span.offset() + source_start as usize,
+                        labeled_span.len(),
+                    )
+                });
+
+                diagnostic.clone().with_labels(new_labels).with_source_code(Arc::clone(&source))
+            })
             .collect();
```
Comment (camchenry) [inline crates/oxc_diagnostics/src/service.rs:163]: we should probably try to avoid cloning the diagnostic, we can stay more true to the original code:

```rs
let diagnostics = diagnostics
            .into_iter()
            .map(|diagnostic| {
                if source_start == 0 {
                    return diagnostic.with_source_code(Arc::clone(&source));
                }

                match &diagnostic.labels {
                    None => diagnostic.with_source_code(Arc::clone(&source)),
                    Some(labels) => {
                        let new_labels = labels
                            .into_iter()
                            .map(|labeled_span| {
                                LabeledSpan::new(
                                    labeled_span.label().map(std::string::ToString::to_string),
                                    labeled_span.offset() + source_start as usize,
                                    labeled_span.len(),
                                )
                            })
                            .collect::<Vec<_>>();

                        diagnostic.with_labels(new_labels).with_source_code(Arc::clone(&source))
                    }
                }
            })
            .collect();
```

**Review by camchenry — APPROVED** [review]
