### PR TITLE
fix(linter): improve prefer_namespace_keyword rule

### LINKED ISSUE #4651: Panic `byte index 15 is out of bounds` in `oxc_span/src/span.rs`
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
module A.B {
}
```

command
```
timeout -v 100 oxlint -D all -D nursery --import-plugin --jsdoc-plugin --jest-plugin --vitest-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin TEST___FILE.ts --fix
```

App was compiled with nightly rust compiler to be able to use address sanitizer
On Ubuntu 24.04, the commands to compile were:
```
rustup default nightly
rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

export RUST_BACKTRACE=1
export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
export ASAN_OPTIONS=symbolize=1
RUSTFLAGS="-Zsanitizer=address" cargo +nightly build --target x86_64-unknown-linux-gnu
```

cause this
```
thread '<unnamed>' panicked at crates/oxc_span/src/span.rs:300:21:
byte index 15 is out of bounds of `module A.B {
}`
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/16490296/compressed.zip)

### PR DESCRIPTION
**Pull request by cblh**
fix: #4651
This commit enhances the `prefer_namespace_keyword` rule in the TypeScript linter: Add support for detecting and fixing nested module declarations (e.g., module A.B {})

- Introduce helper functions `is_nest_module`, `is_valid_module`, and `is_invalid_module` to improve code readability and maintainability
- Refactor the main `run` function to use these new helper functions
- Update test cases to cover nested module scenarios
- Improve error reporting for nested modules

### CODE REVIEW

**Review by rzvxa — CHANGES_REQUESTED** [review]

File: crates/oxc_linter/src/rules/typescript/prefer_namespace_keyword.rs [hunk 1]
```diff
@@ -88,18 +105,32 @@ fn test() {
...
         ("module foo {}", "namespace foo {}", None),
-        ("declare module foo {}", "declare namespace foo {}", None),
+        ("module A.B {}", "namespace A.B {}", None),
         (
             "
-			declare module foo {
-			  declare module bar {}
+            module A {
+              module B {}
 			}
```
Comment (rzvxa) [inline crates/oxc_linter/src/rules/typescript/prefer_namespace_keyword.rs:113]: Your string formatting is still wrong, I guess you are using tabs over spaces - which is something I do as well - If you are using Vim write `:retab` to convert all of them to spaces.
On VSCode there is a built-in command called `Convert Indentations to Spaces` which you can use.

File: crates/oxc_linter/src/rules/typescript/prefer_namespace_keyword.rs [hunk 2]
```diff
@@ -34,13 +34,29 @@ declare_oxc_lint!(
...
+
 impl Rule for PreferNamespaceKeyword {
     fn run<'a>(&self, node: &AstNode<'a>, ctx: &LintContext<'a>) {
         let AstKind::TSModuleDeclaration(module) = node.kind() else { return };
-        if module.id.is_string_literal()
-            || !matches!(module.id, TSModuleDeclarationName::Identifier(_))
-            || module.kind != TSModuleDeclarationKind::Module
-        {
+
+        if is_invalid_module(module) {
```
Comment (rzvxa) [inline crates/oxc_linter/src/rules/typescript/prefer_namespace_keyword.rs:55]: It would be super cool if we merge these 2 conditions together, However, if you like it this way feel free to ignore my comment. It is mostly a matter of taste.

**Review by rzvxa — APPROVED** [review]
I've pushed a commit doing a small formatting unrelated to your changes(it was from an old test case).

Thanks for putting up with my nits❤️

**Comment by cblh** [comment]
> I've pushed a commit doing a small formatting unrelated to your changes(it was from an old test case).我已经推送了一个提交，进行了与您的更改无关的小格式设置（它来自旧的测试用例）。
> 
> Thanks for putting up with my nits❤️谢谢你忍受我的烦恼❤️

Entirely understandable, and thank you for slogging through it with me!

**Comment by cblh** [comment]
> I've pushed a commit doing a small formatting unrelated to your changes(it was from an old test case).
> 
> Thanks for putting up with my nits❤️

Entirely understandable, and thank you for slogging through it with me!
