### PR TITLE
fix(formatter,oxfmt): Handle CRLF with embedded formatting

### LINKED ISSUE #18663: oxfmt: adding one extra line after each line inside `@Component({ template, styles })`
#18324 added support for angular inline template and styles,
but now it is adding one extra line after each line inside inline template and styles block.
and same behavior with vs code extension and cli.

.oxfmtrc.json
```json
{
    "$schema": "./node_modules/oxfmt/configuration_schema.json",
    "singleQuote": true,
    "tabWidth": 4,
    "printWidth": 120,
    "bracketSameLine": true,
    "endOfLine": "crlf",
    "trailingComma": "es5",
    "arrowParens": "avoid",
    "ignorePatterns": ["**/assets/**"],
    "experimentalSortImports": {
        "internalPattern": ["@ccure-iq/"]
    }
}
```

Image

Image

### PR DESCRIPTION
**Pull request by leaysgur**
Fixes #18663 , but not related to Angular.

Actually, before this fix, when performing embedded formatting with `endOfLine: crlf` specified, it seemed to panic in debug builds.

https://github.com/oxc-project/oxc/blob/e440b78fd4a925c06547815406d45eb02e0aa370/crates/oxc_formatter/src/formatter/builders.rs#L342

`Text` can not contain `\r`.

Since this check is disabled in release builds, it simply resulted in extra line breaks.

### CODE REVIEW

**Comment by leaysgur** [comment]
* **#18689** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18689?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18686** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18686?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18686?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#18684** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18684?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=18686).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_formatter/src/print/template.rs [hunk 1]
```diff
@@ -821,7 +821,8 @@ fn format_embedded_template<'a>(
     // - Closing backtick
     let format_content = format_with(|f: &mut Formatter<'_, 'a>| {
         let content = f.context().allocator().alloc_str(&formatted);
-        for line in content.split('\n') {
+        // Use `lines()` to handle both LF and CRLF line endings
+        for line in content.lines() {
```
Comment (Dunqing) [inline crates/oxc_formatter/src/print/template.rs]: Let's use `LineTerminatorSplitter` here, which we use in other places in the Formatter to handle the same cases.

https://github.com/oxc-project/oxc/blob/e440b78fd4a925c06547815406d45eb02e0aa370/crates/oxc_formatter/src/formatter/trivia.rs#L423-L424

Comment (Dunqing) [reply crates/oxc_formatter/src/print/template.rs]: I don't mind changing it in a follow-up PR.

**Review by Dunqing — APPROVED** [review]

File: crates/oxc_formatter/src/print/template.rs (hunk 1 above)
Comment (leaysgur) [reply crates/oxc_formatter/src/print/template.rs]: Thanks for pointing that out! It has been updated.
