### PR TITLE
fix(minifier): remove continue in for-in / for-of

### LINKED ISSUE #14063: minifier: Remove `continue` statements
Input (extract from Oxlint code):

```js
for (const ruleName in rules) {
  if (!Object.hasOwn(rules, ruleName)) continue;
  rules[ruleName] = defineRule(rules[ruleName]);
}
```

Currently minified to:

```js
for (let ruleName in rules) {
  if (!Object.hasOwn(rules, ruleName)) continue;
  rules[ruleName] = defineRule(rules[ruleName]);
}
```

The `continue` statement could be removed by negating the `if` condition:

```js
for (let ruleName in rules) {
  if (Object.hasOwn(rules, ruleName)) {
    rules[ruleName] = defineRule(rules[ruleName]);
  }
}
```

Which existing optimizations would then further reduce to:

```js
for (let ruleName in rules)
  Object.hasOwn(rules, ruleName) && (rules[ruleName] = defineRule(rules[ruleName]));
```

I imagine this is not an uncommon code pattern.

[Playground](https://playground.oxc.rs/#eNptU8GO0zAQ/ZXgUytVCJCQUBEnlkorAUV74MJycJ1J1oszjmYmbVGUf2fs1u6BPdV+r2/85s1kNs5sTRepWbmILA1NAb7bARqP+czrZn7EpvFds3q1PzyDk9dPlvcnXGV6UxXrdaMlxOMEH5Mi078K+7v51LTQeYQHRS7aG7lWxfKIZmOi2c6GJkw/waOYbWcDwyZ5HKwI0P/I/Q0TssiJqIjnGKxAewcuWLLitc1Knp68AI/WQYUGi324XV0cRgJWidCkd3ZxVPZ6+TscYig31/VX2bIxoyVOXmcDZwFkfVaDFj5rjzaEeHoAmQj3k7BvYTehS85KqfQk0BF+WFJtQbPu54d7FPJa0d1MgboW774QRbqi6iHllz3ouQZzMSWWetBwDfC7N2/fq6mJ4S7PZxfpc7DMOw+hrU/AeQTyA6DYoFFGTbI+pezgpaLfQGxrxVYfL49gNqx9jNoNEFpNsUTnYgs95A3ANOIa8DO3Udf1GgZilFyrIAH68t9cpQwutV+mqp3H8SscoRb9AzCmHSxLkaWacAw7TTspjkCHyGUlUj+YPoNE1dOi8GW9E1xPS8JTzKWn5R+0uDxL)

### PR DESCRIPTION
**Pull request by daflyinbed**
fix: #14063

### CODE REVIEW

**Comment by overlookmotel** [comment]
Thanks for tackling this.

Quick note: Run `just allocs` and `just minsize` locally to update the snapshot files, which will fix the CI fails.

**Comment by overlookmotel** [comment]
We've recently merged changes to the `allocs` snapshot. Could you please rebase on latest main and re-run `just allocs` and `just minsize` again? That should fix merge conflicts.

Sorry! Oxc moves pretty fast and it's hard to avoid merge conflicts.

**Comment by daflyinbed** [comment]
updated

File: crates/oxc_minifier/src/peephole/minimize_statements.rs [hunk 1]
```diff
@@ -1808,4 +1809,10 @@ mod test {
             "function _() { for (var x = j, i = 0; i < 10; i++) { let j = k; console.log(i, j, j) } }",
         );
     }
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/peephole/minimize_statements.rs:1811]:
```suggestion
    }

```

**Review by sapphi-red — APPROVED** [review]
Looks good to me, thank you!
