### PR TITLE
fix(linter): correctly inherit categories when plugins are enabled

### LINKED ISSUE #9649: linter: Overrides property is not working with "Vitest" plugin
### What version of Oxlint are you using?

0.15.13

### What command did you run?

yarn oxlint -c .oxlintrc.json index.test.ts

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "categories": {
    "style": "error"
  },
  "overrides": [
    {
      "files": ["./index.test.ts"],
      "plugins": ["vitest"]
    }
  ]
}
```

### What happened?

The linter only works when the `plugins` property is set in the root of the config file, when the `plugins` property is set in the `overrides` property, the linter does not work.

This is the config file that works:

```json
{
  "plugins": ["vitest"]
 "categories": {
   "style": "error"
 },
 "overrides": [
 ]
}

```

But this one doesn't work:

```json
{
  "categories": {
    "style": "error"
  },
  "overrides": [
    {
      "files": ["./index.test.ts"],
      "plugins": ["vitest"]
    }
  ]
}
```

https://github.com/user-attachments/assets/cf8386db-2bf2-47ab-a693-0044890843dd

### LINKED ISSUE #10394: linter: `plugins` inside `overrides` don't get applied
### What version of Oxlint are you using?

0.16.6

### What command did you run?

`oxlint .`, vsc extension does the same

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "extends": ["../packages/oxlint-config/index.json"],
  "overrides": [
    {
      "files": ["__tests__/**"],
      "plugins": ["jest", "vitest"],
      "rules": {
        // "no-unused-vars": "off"
      }
    }
  ]
}

```

The contents of the `oxlint-config/index.json` don't matter in this case but here you go:

```json
{
  "ignorePatterns": ["node_modules", "dist", "coverage", "build"],
  "categories": {
    "correctness": "error",
    "suspicious": "error",
    "perf": "error"
  },
  "plugins": ["typescript", "unicorn", "oxc", "import", "node", "promise"],
  "rules": {
    "no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^(_|e|event)",
        "caughtErrorsIgnorePattern": "^(_|e|error)",
        "varsIgnorePattern": "^_"
      }
    ],
    "no-await-in-loop": "allow",
    "consistent-function-scoping": "off",
    "prefer-add-event-listener": "off",
    "no-unsafe-optional-chaining": "off",
    "no-new": "off",
    "no-new-array": "off",
    "no-useless-spread": "off",
    "no-unneeded-ternary": "off",
    "no-async-endpoint-handlers": "off",
    "no-this-alias": "off"
  }
}
```

### What happened?

When trying to setup overrides for my test files, i wanted to enable the `jest` and `vitest` plugins for test files. I noticed that adding `plugins` inside `overrides` does nothing - it only works when added to the root of the config file. I verified the override is being applied correctly by disabling the `no-unused-vars` rule as a quick test.

Plugins in overrides, not working
Image

Verified override is being applied by disabling `no-unused-vars`
Image

`jest` plugin working when added to the root 
Image

### PR DESCRIPTION
**Pull request by camc314**
fixes #10394
fixes #9649

### CODE REVIEW

**Comment by camc314** [comment]
* **#11353** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/11353?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/11353?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=11353).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_linter/src/config/rules.rs [hunk 1]
```diff
@@ -61,7 +61,6 @@ impl OxlintRules {
     pub(crate) fn override_rules(&self, rules_for_override: &mut RuleSet, all_rules: &[RuleEnum]) {
```
Comment (camc314) [inline crates/oxc_linter/src/config/rules.rs:61]: TODO(camc314): simplify this (there's a bunch or repeated logic

File: crates/oxc_linter/src/config/config_store.rs [hunk 2]
```diff
@@ -110,6 +129,18 @@ impl Config {
...
+                    for (rule, severity) in all_rules.iter().filter_map(|rule| {
+                        self.categories
+                            .get(&rule.category())
+                            .map(|severity| (rule.clone(), severity))
+                    }) {
+                        rules.entry(rule).or_insert(*severity);
+                    }
+                }
+            }
+
```
Comment (camc314) [inline crates/oxc_linter/src/config/config_store.rs:143]: before applying any rules in the override, we need to check if the plugins have changed

if the plugins have changed, we need to re-apply the rules based on the categories at the root of the config

**Comment by camc314** [comment]
@Sysix this should be ready, mind taking a quick look over it please 🙏

**Review by Sysix — COMMENTED** [review]
Looks like we are now storing categories which are allowed. I guess this is not really needed? 
The Store + Builder is an area which I need to understand it better

**Review by Sysix — APPROVED** [review]

**Comment by camc314** [comment]
> Looks like we are now storing categories which are allowed. I guess this is not really needed?

yes unfortunately we do need to store it. e.g.

```
{
    "categories": { 
        "style": "true",
        "correctness": "true"
    },
    "overrides": [
        {
            "plugins": ["jest"]
            // we need to store root categories so we can enable jest/style + jest/correctness
        }
    ]
}
```

**Comment by Sysix** [comment]
@camc314 I was talking about "style/correctness": "off"
