### PR TITLE
fix(linter): add considerDefaultExhaustiveForUnions option to switch-exhaustiveness-check

### LINKED ISSUE #16182: @typescript-eslint/switch-exhaustiveness-check doesn't support considerDefaultExhaustiveForUnions
test.ts:

```ts
type Day = 'Monday' | 'Tuesday'

declare const day: Day
let result = 0

switch (day) {
  case 'Monday':
    result = 1
    break
  default:
    result = 3
    break
}
```

.oxlintrc.json:

```json
    "@typescript-eslint/switch-exhaustiveness-check": [
      "error",
      {
        "considerDefaultExhaustiveForUnions": true,
      },
    ],
```

```sh
❯ bunx oxlint --type-aware src/test.ts 

  × typescript-eslint(switch-exhaustiveness-check): Switch is not exhaustive
    ╭─[src/test.ts:38:9]
 37 │ 
 38 │ switch (day) {
    ·         ───
 39 │   case 'Monday':
    ╰────
```

oxlint 1.30.0, oxlint-tsgolint 0.8.2

### PR DESCRIPTION
**Pull request by camc314**
Fixes https://github.com/oxc-project/oxc/issues/16182

### CODE REVIEW

**Comment by camc314** [comment]
* **#16204** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16204?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16204?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=16204).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: apps/oxlint/src/lint.rs [hunk 1]
```diff
@@ -1412,4 +1412,13 @@ mod test {
             .with_cwd("fixtures/tsgolint_tsconfig_extends_config_err".into())
             .test_and_snapshot(args);
     }
+
+    #[test]
+    #[cfg(not(target_endian = "big"))]
```
Comment (camc314) [inline apps/oxlint/src/lint.rs]:
```suggestion
    #[cfg(all(not(target_os = "windows"), not(target_endian = "big")))]

```

**Comment by camc314** [comment]
### Merge activity

* **Nov 27, 8:17 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Nov 27, 8:24 AM UTC**: `camc314` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Nov 27, 8:29 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
