### PR TITLE
fix(linter): false positive in `eslint/no-redeclare`

### LINKED ISSUE #10396: linter: `no-redeclare` triggers for function overloads
### What version of Oxlint are you using?

0.16.6

### What command did you run?

cli and vsc extension

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "ignorePatterns": ["node_modules", "dist", "coverage", "build"],
  "categories": {
    "correctness": "error",
    "suspicious": "error",
    "perf": "error"
  },
  "plugins": ["typescript", "unicorn", "oxc", "import", "node", "promise"],
  "rules": {
    "no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^(_|e|event)",
        "caughtErrorsIgnorePattern": "^(_|e|error)",
        "varsIgnorePattern": "^_"
      }
    ],
    "no-await-in-loop": "allow",
    "consistent-function-scoping": "off",
    "prefer-add-event-listener": "off",
    "no-unsafe-optional-chaining": "off",
    "no-new": "off",
    "no-new-array": "off",
    "no-useless-spread": "off",
    "no-unneeded-ternary": "off",
    "no-async-endpoint-handlers": "off",
    "no-this-alias": "off",
    "no-var": "error",

    "no-non-null-assertion": "error",
    "no-non-null-asserted-nullish-coalescing": "error",
    "no-explicit-any": "error",
    "no-empty-object-type": "error",
    "explicit-function-return-type": [
      "error",
      {
        "allowExpressions": true
      }
    ],
    "no-unused-expressions": [
      "error",
      {
        "allowTernary": true
      }
    ],
    "no-unsafe-function-type": "error",
    "prefer-for-of": "error",
    "consistent-type-definitions": ["error", "type"],
    "no-var-requires": "error",
    "no-named-as-default": "error",
    "no-named-as-default-member": "error",
    "no-array-constructor": "error",
    "no-dynamic-delete": "error",
    "no-extraneous-class": "error",
    "no-require-imports": "error",
    "no-empty-function": "error",
    "no-redeclare": "error",
    "no-empty": [
      "error",
      {
        "allowEmptyCatch": true
      }
    ],
    "no-self-compare": "error",
    "no-throw-literal": "error",
    "no-constant-condition": "error",
    "no-constant-binary-expression": "error",
    "no-unnecessary-type-constraint": "error",
    "no-useless-constructor": "error",
    "prefer-literal-enum-member": "error",
    "prefer-namespace-keyword": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "no-duplicates": "error",
    "no-case-declarations": "error",
    "no-fallthrough": "error",
    "no-inner-declarations": "error",
    "no-prototype-builtins": "error",
    "no-regex-spaces": "error",

    "todo-lowerthis": "off",
    "max-depth": [
      "error",
      {
        "max": 9
      }
    ],

    "todo": "off",
    "ban-ts-comment": "off",
    "no-array-for-each": "off",
    "eqeqeq": "off",
    "prefer-ts-expect-error": "off",

    "consider": "off",
    "no-cycle": "off",
    "no-nested-ternary": "off"
  }
}

```

### What happened?

I assume this is because oxlint doesn't fully support typescript rules yet, but i thought i would report this in case there is some temporary hack/workaround that could be implemented here (or if i should just do a `disable-next-line` for now)

Image

### PR DESCRIPTION
**Pull request by shulaoda**
closes #10396 

- Fix the false positive in `typescript`
- Align with `eslint` -- set the default value of `builtinGlobals` to `true`

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/no_redeclare.rs [hunk 1]
```diff
@@ -122,6 +146,8 @@ fn test() {
         ("var self = 1", Some(serde_json::json!([{ "builtinGlobals": false }]))),
         ("var globalThis = foo", Some(serde_json::json!([{ "builtinGlobals": false }]))),
         ("var globalThis = foo", Some(serde_json::json!([{ "builtinGlobals": false }]))),
+        // Issue: <https://github.com/oxc-project/oxc/issues/10396>
+        ("export function get(): void; export function get() { }", None),
```
Comment (camchenry) [inline crates/oxc_linter/src/rules/eslint/no_redeclare.rs:150]: should we include a test for a non-export? like:

```
function foo(arg: string): void; function foo(arg: number): any {}
```

Comment (shulaoda) [reply crates/oxc_linter/src/rules/eslint/no_redeclare.rs]: Yes, added it.

**Review by camchenry — APPROVED** [review]
