### PR TITLE
fix(linter): false positive in `import/no-empty-named-blocks`

### LINKED ISSUE #9914: Panic `byte index 13 is not a char boundary` in `no_empty_named_blocks` rule
File content(at the bottom should be attached raw, not formatted file - github removes some non-printable characters, so copying from here may not work):
```
import{}from ""
```

command
```
timeout -v 150 oxlint -D all -D nursery --import-plugin --jsdoc-plugin --jest-plugin --vitest-plugin --jsx-a11y-plugin --nextjs-plugin --react-perf-plugin TEST___FILE.ts --fix --fix-suggestions --fix-dangerously
```

cause this
```
thread '<unnamed>' panicked at crates/oxc_span/src/span.rs:394:21:
byte index 13 is not a char boundary; it is inside '\u{a0}' (bytes 12..14) of `import{}from ""`
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/75530e9f72a1990ed2305e16fd51d02f47048f12/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/75530e9f72a1990ed2305e16fd51d02f47048f12/library/core/src/panicking.rs:75:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/75530e9f72a1990ed2305e16fd51d02f47048f12/library/core/src/str/mod.rs:68:5
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/traits.rs:240:21
   5: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/traits.rs:60:15
   6: oxc_span::span::Span::source_text
             at ./oxc-main/crates/oxc_span/src/span.rs:394:21
   7: <oxc_linter::rules::import::no_empty_named_blocks::NoEmptyNamedBlocks as oxc_linter::rule::Rule>::run
             at ./oxc-main/crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:62:32
   8: oxc_linter::Linter::run
             at ./oxc-main/crates/oxc_linter/src/lib.rs:204:21
   9: oxc_linter::service::runtime::Runtime::run::{{closure}}::{{closure}}::{{closure}}
             at ./oxc-main/crates/oxc_linter/src/service/runtime.rs:455:50
  10: oxc_linter::service::runtime::ModuleContent::with_dependent_mut
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/self_cell-1.1.0/src/lib.rs:540:13
  11: oxc_linter::service::runtime::Runtime::run::{{closure}}::{{closure}}
             at ./oxc-main/crates/oxc_linter/src/service/runtime.rs:438:17
  12: oxc_linter::service::runtime::Runtime::resolve_modules::{{closure}}
             at ./oxc-main/crates/oxc_linter/src/service/runtime.rs:426:21
  13: rayon_core::scope::Scope::spawn::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:526:57
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  15: std::panicking::try::do_call
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  16: std::panicking::try
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
  17: std::panic::catch_unwind
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  18: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/unwind.rs:17:5
  19: rayon_core::scope::ScopeBase::execute_job_closure
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:689:28
  20: rayon_core::scope::ScopeBase::execute_job
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:679:29
  21: rayon_core::scope::Scope::spawn::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:526:13
  22: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/job.rs:169:9
  23: rayon_core::job::JobRef::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/job.rs:64:9
  24: rayon_core::registry::WorkerThread::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:860:13
  25: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:786:22
  26: rayon_core::scope::ScopeBase::complete
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:668:9
  27: rayon_core::scope::scope::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:291:9
  28: rayon_core::registry::in_worker
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:951:13
  29: rayon_core::scope::scope
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/scope/mod.rs:289:5
  30: oxc_linter::service::runtime::Runtime::run
             at ./oxc-main/crates/oxc_linter/src/service/runtime.rs:436:9
  31: oxc_linter::service::LintService::run
             at ./oxc-main/crates/oxc_linter/src/service/mod.rs:86:9
  32: <oxlint::lint::LintRunner as oxlint::runner::Runner>::run::{{closure}}
             at ./oxc-main/apps/oxlint/src/lint.rs:380:17
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
  34: std::panicking::try::do_call
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:589:40
  35: std::panicking::try
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:19
  36: std::panic::catch_unwind
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:359:14
  37: rayon_core::unwind::halt_unwinding
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/unwind.rs:17:5
  38: rayon_core::registry::Registry::catch_unwind
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:367:27
  39: rayon_core::spawn::spawn_job::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/spawn/mod.rs:97:13
  40: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/job.rs:169:9
  41: rayon_core::job::JobRef::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/job.rs:64:9
  42: rayon_core::registry::WorkerThread::execute
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:860:13
  43: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:794:26
  44: rayon_core::registry::WorkerThread::wait_until
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:769:13
  45: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:818:9
  46: rayon_core::registry::main_loop
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:923:5
  47: rayon_core::registry::ThreadBuilder::run
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:53:18
  48: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rayon-core-1.12.1/src/registry.rs:98:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/19360077/compressed.zip)

### PR DESCRIPTION
**Pull request by shulaoda**
closes #9914

### CODE REVIEW

File: crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs [hunk 1]
```diff
@@ -48,40 +47,41 @@ impl Rule for NoEmptyNamedBlocks {
...
+        else {
+            return;
+        };
+
+        let span = Span::new(specifier.span.end, import_decl.source.span.start);
+        let source_token_str = ctx.source_range(span);
+
+        // import Default, {} from 'mod'
+        if let Some(start) = source_token_str.find(',') {
+            let end = source_token_str[start..].find("from").unwrap();
```
Comment (camchenry) [inline crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:73]: Could we early return instead of unwrap? I know it's almost guaranteed it'll be there, but seems better to be safe

**Review by camchenry — APPROVED** [review]

File: crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs (hunk 1 above)
Comment (shulaoda) [reply crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:73]: If it does not meet expectations, an error should be reported, and users should provide feedback to us. We need to investigate the issue and add it as a test case.

Comment (shulaoda) [reply crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:73]: I hope to discover some edge cases in real-world scenarios.

Comment (shulaoda) [reply crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:73]: Because I find it difficult to imagine other possible failure scenarios, this behavior is unexpected.

Comment (shulaoda) [reply crates/oxc_linter/src/rules/import/no_empty_named_blocks.rs:73]: However, you make a good point—unexpected behavior shouldn't be within our scope of consideration.

**Review by Sysix — APPROVED** [review]

**Comment by Sysix** [comment]
### Merge activity

* **Mar 22, 9:24 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
