### PR TITLE
perf(minifier): fix O(n²) perf on very many var decls

### LINKED ISSUE #17369: minifier: Performance regression: 2.5x slower minification with minor input size increase
## Description

I've encountered a significant performance regression in `oxc-minify` where a file that is only ~6% larger takes 2.5x longer to minify.

## Benchmark Results

| File | Input Size | Output Size | Compression Ratio | Time |
|------|------------|-------------|-------------------|------|
| good.js | 10176.62 KB | 6781.65 KB | 33.36% | **282.31 ms** |
| bad.js | 10820.12 KB | 6937.99 KB | 35.88% | **704.10 ms** |

## Environment

- `oxc-minify` version: 0.105.0
- Platform: Windows (win32-x64-msvc)

## Reproduction
1. git clone https://github.com/IWANABETHATGUY/oxc-minify-performance-issue
2. pnpm install

Files attached: `good.js` and `bad.js`

```bash
node minify-with-oxc.mjs ./good.js  # ~282ms
node minify-with-oxc.mjs ./bad.js   # ~704ms
```

## Expected Behavior

Similar input sizes should result in similar minification times.

## Actual Behavior

A 6% increase in input size causes a 150% increase in processing time, suggesting possible algorithmic complexity issues with certain code patterns.

---

Would you like me to adjust anything (add more details, change the title, etc.)?

### PR DESCRIPTION
**Pull request by gthb**
What
---

Fix two O(n²) bottlenecks in the compressor that cause severe slowdowns on bundler output (esbuild, webpack CJS) containing thousands of root-level `var import_X = __toESM(require_Y())` declarations, the pattern reported in #17369, where a file only 6% larger took 2.5x longer to minify.

Fixes #17369

Specifically:

Batch reference retention in `exit_program`
---

After each compressor iteration, stale references are cleaned up by diffing live references against the symbol table. The per-reference `delete_resolved_reference` method uses `.position()` internally, and that's a linear scan of the symbol's reference list, so repeated deletions are O(n²) when many references to the same symbol are removed.

Replace with a new `Scoping::retain_resolved_references` method that iterates each symbol's reference list once, retaining only references present in the live set. Total cost: O(total_refs).

Cached `is_symbol_mutated` helper
---

`Scoping::symbol_is_mutated(symbol_id)` scans all resolved references for the symbol looking for a write. For heavily-referenced symbols like `__toESM` (10k+ refs in the issue's bad.js) each call is O(num_refs), and when it is called repeatedly during compression the total becomes O(n²).

Add `PeepholeOptimizations::is_symbol_mutated`, which reads the `write_references_count` already cached in `SymbolValue` (populated during `exit_variable_declarator` → `init_symbol_value`). This is O(1). It falls back to the full scan for symbols without cached values (function declarations and other non-variable bindings).

Use this helper instead of `Scoping::symbol_is_mutated` in two places:

- Directly in `substitute_single_use_symbol_in_expression`, which walks target expressions looking for single-use symbols to inline. When it encounters an identifier it checks whether reordering the replacement past that identifier is safe. With ~10k substitution attempts per iteration on bad.js, this was the dominant O(n²) contributor.

- Via `is_expression_that_reference_may_change`, which checks whether the base object of a member-expression assignment target can be mutated. It is called from:
  - `substitute_single_use_symbol_in_expression`, when the assignment target is `foo.bar = …`
  - `member_object_may_be_mutated`, which is called from `minimize_logical_expression` and `remove_unused_expression`

Performance
---

On the real-world files from #17369, on my machine, the time taken by
```
Compressor::new(&allocator).build_with_scoping(
    &mut program,
    scoping,
    CompressOptions::smallest(),
)
```
changes thus:

```
good.js (10.4 MB):  48.61 → 47.56 ms  (2.2% faster, or maybe that's just noise)
bad.js  (11.1 MB): 389.18 → 57.18 ms  (6.8x faster)
ratio bad/good:      8.0x →  1.2x
```

The total minification time (parse + compress + mangle) changes thus:
```
good.js (10.4 MB):  91.50 → 91.04 ms  (0.5% faster, probably mostly noise!)
bad.js  (11.1 MB): 436.28 → 104.40 ms  (4.2x faster)
ratio bad/good:      4.8x →  1.15x
```

For both compress and total, the bad/good ratio is now much closer to the ratio between the file sizes.

### CODE REVIEW

**Comment by gthb** [comment]
I used Claude for the investigation and fixes, then reviewed and iterated.

File: crates/oxc_minifier/src/peephole/minimize_statements.rs [hunk 1]
```diff
@@ -1287,6 +1288,21 @@ impl<'a> PeepholeOptimizations {
...
     }
 
+    /// Check if a symbol is mutated, using the O(1) cached `write_references_count`
+    /// from `SymbolValue` when available, falling back to the O(num_refs) scan in
+    /// `Scoping::symbol_is_mutated` for symbols without cached values.
+    ///
+    /// Only variable declarators have cached values (populated during
+    /// `exit_variable_declarator` → `init_symbol_value`); function declarations
+    /// and other binding kinds still take the fallback path.
+    fn is_symbol_mutated(symbol_id: SymbolId, ctx: &TraverseCtx<'a>) -> bool {
```
Comment (armano2) [inline crates/oxc_minifier/src/peephole/minimize_statements.rs]: should we also use it in `is_expression_that_reference_may_change`?

Comment (gthb) [reply crates/oxc_minifier/src/peephole/minimize_statements.rs]: Yeah, probably! And given the general “O(n²) perf” scope, I guess it's fine to just add that in.

**Comment by Brooooooklyn** [comment]
@codex review

File: crates/oxc_minifier/src/peephole/minimize_statements.rs (hunk 1 above)
Comment (gthb) [reply crates/oxc_minifier/src/peephole/minimize_statements.rs]: Done in https://github.com/oxc-project/oxc/pull/21062/commits/6fc05eeb9750bf34ccf6b81f60ffbc2050a286b8

**Comment by gthb** [comment]
Updated PR description to account for the addition https://github.com/oxc-project/oxc/pull/21062/commits/6fc05eeb9750bf34ccf6b81f60ffbc2050a286b8 and updated performance measurements.
