### PR TITLE
fix: improve span for no accumulating spread

### LINKED ISSUE #1643: feat(linter): improve the span for no-accumulating-spread
image

I think we should highlight the span on `reduce` as well, what do you think @camc314?

### PR DESCRIPTION
**Pull request by camc314**
Closes #1643

### CODE REVIEW

**Comment by camc314** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1644** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1644?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1644?utm_source=stack-comment).

File: crates/oxc_linter/src/rules/oxc/no_accumulating_spread.rs [hunk 1]
```diff
@@ -10,19 +10,33 @@ use oxc_macros::declare_oxc_lint;
...
+    AstNode,
+};
 
 #[derive(Debug, Error, Diagnostic)]
 enum NoAccumulatingSpreadDiagnostic {
     #[error("oxc(no-accumulating-spread): Do not spread accumulators in Array.prototype.reduce()")]
     #[diagnostic(severity(warning), help("It looks like you're spreading an `Array`. Consider using the `Array.push` or `Array.concat` methods to mutate the accumulator instead.\nUsing spreads within accumulators leads to `O(n^2)` time complexity."))]
-    LikelyArray(#[label] Span),
+    LikelyArray(
+        #[label("Accululator is spread here.")] Span,
```
Comment (Boshen) [inline crates/oxc_linter/src/rules/oxc/no_accumulating_spread.rs:25]: `Accumulating spread is here`? What's a `Accululator` 🤔

**Review by Boshen — CHANGES_REQUESTED** [review]

File: crates/oxc_linter/src/rules/oxc/no_accumulating_spread.rs (hunk 1 above)
Comment (camc314) [reply crates/oxc_linter/src/rules/oxc/no_accumulating_spread.rs]: oops good catch

**Review by Boshen — APPROVED** [review]
