### PR TITLE
fix(codegen): avoid unsafe code search original name

### LINKED ISSUE #716: ci: crash on windows
Here is error.
```
process didn't exit successfully: `D:\a\rolldown\rolldown\target\debug\deps\esbuild-1ce2e539eae6e9f7.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

https://github.com/rolldown/rolldown/actions/runs/8505493287/job/23294065477

### PR DESCRIPTION
**Pull request by underfin**
close https://github.com/rolldown/rolldown/issues/716

### CODE REVIEW

File: crates/oxc_codegen/src/sourcemap_builder.rs [hunk 1]
```diff
@@ -62,12 +62,12 @@ impl SourcemapBuilder {
     }
 
     pub fn add_source_mapping_for_name(&mut self, output: &[u8], span: Span, name: &str) {
-        // SAFETY: search original string by span.
-        let original_name =
-            unsafe { self.original_source.get_unchecked(span.start as usize..span.end as usize) };
+        // Here using `get_unchecked` happened crash at windows. See https://github.com/rolldown/rolldown/issues/716
```
Comment (Boshen) [inline crates/oxc_codegen/src/sourcemap_builder.rs:65]:
```suggestion
```

**Review by Boshen — APPROVED** [review]

File: crates/oxc_codegen/src/sourcemap_builder.rs (hunk 1 above)
Comment (hyf0) [inline crates/oxc_codegen/src/sourcemap_builder.rs]: Maybe we could add a `debug_assert!(span.end < self.original_source.len())` to deny all possiable invalid span in debug build. And and silent the error in release build because nothing we could do in that time.

File: crates/oxc_codegen/src/sourcemap_builder.rs [hunk 2]
```diff
@@ -62,12 +62,11 @@ impl SourcemapBuilder {
     }
 
     pub fn add_source_mapping_for_name(&mut self, output: &[u8], span: Span, name: &str) {
-        // SAFETY: search original string by span.
-        let original_name =
-            unsafe { self.original_source.get_unchecked(span.start as usize..span.end as usize) };
+        let original_name = self.original_source.get(span.start as usize..span.end as usize);
```
Comment (hyf0) [inline crates/oxc_codegen/src/sourcemap_builder.rs:65]: Maybe we should add a `debug_assert` to deny all invalid span as many as possible in debug build. For release build, we just ignore it because nothing we could do there.
