### PR TITLE
fix(formatter): classes will be stripped out when both `experimentalTailwindcss` and `experimentalSortImports` are enabled

### LINKED ISSUE #17725: oxfmt/tailwind: Unexpected behavior with `experimentalTailwindcss` + `experimentalSortImports`
> I am seeing something related with classnames, but different. 
> 
> I have `"experimentalTailwindcss": {
>     "functions": ["clsx"]
>   }` in `.oxfmtrc.json` and all is well. 
> 
> But when I add just `"experimentalSortImports": {},
> ` and then run `oxfmt`, it strips Tailwind classes across many, but not all, React components. 

 _Originally posted by @kevinashworth in [#17690](https://github.com/oxc-project/oxc/issues/17690#issuecomment-3716078879)_

### PR DESCRIPTION
**Pull request by Dunqing**
close: #17725

This is caused by our use of `Document::from` for sorted elements when `experimentalSortImports` is enabled. This method will use `Vec::default()` for `sorted_tailwind_classes`, which causes classes to be stripped.

In this PR,

I removed `Document::from` and used `Document::new` everywhere that needs to pass `sorted_tailwind_classes` explicitly, so that we can ensure it is passed correctly. 

And for the `experimentalSortImports`, it will replace sorted elements directly instead of constructing a new `Document`, so that the `sorted_tailwind_classes` remains as is.

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#17726** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/17726?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/17726?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=17726).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_formatter/src/ir_transform/sort_imports/mod.rs [hunk 1]
```diff
@@ -32,14 +34,17 @@ impl SortImportsTransform {
...
     // - There is no redundant spaces, no consecutive line breaks, etc...
     // - Last element is always `FormatElement::Line(Hard)`.
-    pub fn transform<'a>(
-        document: &Document<'a>,
-        options: &SortImportsOptions,
-        allocator: &'a Allocator,
-    ) -> Option<Document<'a>> {
+    pub fn transform<'a>(formatted: &mut Formatted<'a>, allocator: &'a Allocator) {
+        // Early return if sort-imports is not enabled
+        let Some(options) = &formatted.context().options().experimental_sort_imports else {
```
Comment (leaysgur) [inline crates/oxc_formatter/src/ir_transform/sort_imports/mod.rs]: This check can be done at the caller's side?

**Review by leaysgur — APPROVED** [review]

File: crates/oxc_formatter/src/ir_transform/sort_imports/mod.rs (hunk 1 above)
Comment (Dunqing) [reply crates/oxc_formatter/src/ir_transform/sort_imports/mod.rs]: I think so! Previously, it caused a borrow check problem, but now I know how to fix it.

Comment (Dunqing) [reply crates/oxc_formatter/src/ir_transform/sort_imports/mod.rs]: Done!

**Comment by leaysgur** [comment]
### Merge activity

* **Jan 7, 1:24 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Jan 7, 1:24 AM UTC**: `leaysgur` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Jan 7, 1:31 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
