### PR TITLE
fix(parser,semantic): make semantic own `Trivias`

### LINKED ISSUE #708: Replace `Rc<T>` with `Lrc<T>` for convientnet parallel programing
rustc use `Lrc<T>` to control whether to enable the parallel context.

See https://rustc-dev-guide.rust-lang.org/parallel-rustc.html#data-structures for details.

Currently, oxc uses `Rc<T>` everywhere

https://github.com/web-infra-dev/oxc/blob/909d037f0da2b0d8830465e02205f6f082f1f190/crates/oxc_parser/src/lib.rs#L97

This prevents the usage of applying rayon on these data structures. rayon requires data to be `Send`.

### PR DESCRIPTION
**Pull request by Boshen**
closes #708

Making the parser return Rc<Trivias> is not a good API, and ideally `Semantic` should just own `Trivias` so it can process or mutate it.

### CODE REVIEW

File: crates/oxc_semantic/src/builder.rs [hunk 1]
```diff
@@ -106,9 +106,10 @@ impl<'a> SemanticBuilder<'a> {
     }
 
     #[must_use]
-    pub fn with_trivias(mut self, trivias: &Rc<Trivias>) -> Self {
-        self.trivias = Rc::clone(trivias);
-        self.jsdoc = JSDocBuilder::new(self.source_text, trivias);
+    pub fn with_trivias(mut self, trivias: Trivias) -> Self {
+        let trivias = Rc::new(trivias);
+        self.trivias = Rc::clone(&trivias);
+        self.jsdoc = JSDocBuilder::new(self.source_text, &trivias);
```
Comment (hyf0) [inline crates/oxc_semantic/src/builder.rs:112]: I'm not sure this PR fixes #708 eventually. The `Rc` still lives on `Semantic`, which makes `Semantic` not `Send`.

If you have a bunch of `Semantic`s and want to apply `rayon` on them, the rustc would still complain that `Semantic` is not `Send` or `Sync`.
