### PR TITLE
fix(semantic): use correct scope flags for using declarations

### LINKED ISSUE #9666: Bindings declared with `using` should be block scoped and const
[Explicit resource management proposal](https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#using-declarations) describes `using` as describing "a synchronously-disposed, block-scoped resource". The intent of `using` is that the resource is automatically disposed of at the end of the enclosing block, so block scoping makes sense.

Additionally, [the proposal shows](https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#using-declarations-with-explicit-local-bindings) equivalent transpiled code as using a `const` binding.

Currently Oxc generates a binding with symbol flags `FunctionScopedVariable`, and hoists the binding to scope of enclosing function (like `var`). I believe it should behave like `const` - flags `BlockScopedVariable | ConstVariable`, and the binding should not be hoisted.

```js
function f() {
  {
    using x = 123;
  }
}
```

[Playground](https://playground.oxc.rs/#eNpFkMFOwzAMhl8l8gmkCbEhLkXc0K4g4LhLlrlTUOpUtjM2VX13nHYdUpTE8W//nzNAgAbaQkFjJtfe3bthR27enCsS6ejO7tWtN08v9W3ckS1YQYZmAC5UD7mQ+jM0ygVXkCIpNK1PYoGE3OOSkUu3z2mJlD1Jm7m7iscV9J4Fubb0KeXfT9TC9F5U4gG3V8ilvGc07Qk/PCPJzSIXDriNCcl3ZgyKog8/YsRz6vtSeYyLY69gnhV38rT7DWmGUM9HtFkAZfO4frYeUXLyioc3DMmzrzxmveCHfMAjTl9i9vuEX5Nl5/t/TRcptnExDJmUc9rasLXqhLzPYnyzehz/ADwcklA=)

In the above example, the binding `x` should not be hoisted to top level of function `f`.

### PR DESCRIPTION
**Pull request by camc314**
fixes https://github.com/oxc-project/oxc/issues/9666

### CODE REVIEW

**Comment by camc314** [comment]
* **#9751** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9751?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9751?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=9751).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by Dunqing — DISMISSED** [review]

**Review by Dunqing — DISMISSED** [review]

File: crates/oxc_ast/src/ast_impl/js.rs [hunk 1]
```diff
@@ -1069,9 +1069,9 @@ impl VariableDeclarationKind {
         matches!(self, Self::Const)
     }
 
-    /// Returns `true` if declared using `let` or `const` (such as `let x` or `const x`)
+    /// Returns `true` if declared using `let`, `const` or `using` (such as `let x` or `const x`)
     pub fn is_lexical(&self) -> bool {
-        matches!(self, Self::Const | Self::Let)
+        matches!(self, Self::Const | Self::Let | Self::Using | Self::AwaitUsing)
     }
```
[the remark this answers is not in the document]
Comment (camc314) [reply crates/oxc_ast/src/ast_impl/js.rs:1075]: fixed. i updated the comments as well.

the span for this lint rule for `await using` points to the whole stmt, as there could be a commment inside `await using`

[the remark this answers is not in the document]
Comment (Dunqing) [reply crates/oxc_ast/src/ast_impl/js.rs:1075]: I am not sure if changing this method will affect other places where this method is being used. Can you double-check this?

File: crates/oxc_linter/src/rules/eslint/no_case_declarations.rs [hunk 2]
```diff
@@ -65,9 +65,10 @@ impl Rule for NoCaseDeclarations {
                     Statement::VariableDeclaration(var) if var.kind.is_lexical() => {
                         let start = var.span.start;
                         let end = match var.kind {
-                            VariableDeclarationKind::Const => 5,
+                            VariableDeclarationKind::Const | VariableDeclarationKind::Using => 5,
                             VariableDeclarationKind::Let => 3,
-                            _ => unreachable!(),
+                            VariableDeclarationKind::AwaitUsing => var.span.size(),
```
Comment (overlookmotel) [inline crates/oxc_linter/src/rules/eslint/no_case_declarations.rs:70]: This line doesn't look quite right. `var.span.size()` will be the length of the entire `VariableDeclaration`, whereas the other arms are just returning the length of the `const` / `let` / `using` keyword.

Maybe that doesn't matter!

But if it does, something like `source_text[var.span.start as usize..var.declarations[0].span.start as usize].trim_end().len() as u32` might do it? Pretty ugly!

File: crates/oxc_semantic/src/binder.rs [hunk 3]
```diff
@@ -20,16 +20,16 @@ pub trait Binder<'a> {
 impl<'a> Binder<'a> for VariableDeclarator<'a> {
     fn bind(&self, builder: &mut SemanticBuilder<'a>) {
         let (includes, excludes) = match self.kind {
-            VariableDeclarationKind::Const => (
+            VariableDeclarationKind::Using
+            | VariableDeclarationKind::AwaitUsing
+            | VariableDeclarationKind::Const => (
```
Comment (overlookmotel) [inline crates/oxc_semantic/src/binder.rs:25]: Complete nit, but I suggest listing `Const` first is preferable - the others are pretty obscure.

```suggestion
            VariableDeclarationKind::Const
            | VariableDeclarationKind::Using
            | VariableDeclarationKind::AwaitUsing => (
```

File: crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js [hunk 4]
```diff
@@ -0,0 +1,10 @@
+{
```
Comment (overlookmotel) [inline crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js:1]: Could you add `await using` to this test?

**Review by overlookmotel — COMMENTED** [review]
Nice job. A few small comments below.

Also, judging by the names of the conformance tests (`transform-sync`), it looks like this change only causes semantic errors in tests relating to `using`, but not `await using`. Seems odd.

Maybe the tests don't contain any cases where `await using` is in a nested block, and that explains it. But I think worth checking, if you didn't already.

File: crates/oxc_linter/src/rules/eslint/no_case_declarations.rs (hunk 2 above)
Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_case_declarations.rs]: i added a test for this case. the problem with `await using` is that it could be any length, and trying to workout the exact span probably isn't work it right now.

Instead i changed it's span to be from the start of the `await using` to the start of the span of the first var decl. this should guarentee that. the span is in valid unicode, while still pointing to `await using` keywords in most cases.

File: crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js (hunk 4 above)
Comment (camc314) [reply crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js:1]: done, let me know if that's what you had in mind

File: crates/oxc_ast/src/ast_impl/js.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (camc314) [reply crates/oxc_ast/src/ast_impl/js.rs:1075]: i looked at all the other uses, and it looks correct

File: crates/oxc_semantic/src/binder.rs (hunk 3 above)
Comment (overlookmotel) [reply crates/oxc_semantic/src/binder.rs]: It would assume it will compile down to exactly same assembly, so 0 perf impact. My suggestion was purely on "code style" grounds.

File: crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js (hunk 4 above)
Comment (overlookmotel) [reply crates/oxc_semantic/tests/fixtures/oxc/js/declarations/using.js:1]: Thanks. Yes, that's exactly what I meant.

**Review by overlookmotel — APPROVED** [review]

**Comment by overlookmotel** [comment]
### Merge activity

* **Mar 18, 2:58 AM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Mar 18, 2:58 AM EDT**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
