### PR TITLE
fix(linter/no-empty-function): respect allow options for functions and arrow functions

### LINKED ISSUE #12161: linter: no-empty-function does not respect the `allow` option
### What version of Oxlint are you using?

1.6.0

### What command did you run?

`oxlint src/index.js`

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",  
   "categories": {
    "correctness": "off"
  },
  "rules": {
    "no-empty-function": [
      "error",
      {
        "allow": ["arrowFunctions", "functions", "methods"]
      }
    ],
    "no-unused-vars": "off"
  },
  "env": {
    "builtin": true
  },
  "globals": {},
  "ignorePatterns": []
}
```

### What happened?

Oxlint is reporting false positives:
```
× eslint(no-empty-function): Unexpected empty function `foo`
   ╭─[src/index.js:1:19]
 1 │ const foo = () => {}
   ·                   ──
 2 │ function bar() {}
   ╰────
  help: Consider removing this function or adding logic to it.

  × eslint(no-empty-function): Unexpected empty function `bar`
   ╭─[src/index.js:2:16]
 1 │ const foo = () => {}
 2 │ function bar() {}
   ·                ──
   ╰────
  help: Consider removing this function or adding logic to it.
```

The config specifies that empty functions and arrow functions are allowed, so there should be no errors.

The options have allegedly been implemented in https://github.com/oxc-project/oxc/issues/10529
The docs list the `allow` option for this rule as available: https://oxc.rs/docs/guide/usage/linter/rules/eslint/no-empty-function.html

### PR DESCRIPTION
**Pull request by camc314**
fixes #12161

### CODE REVIEW

**Comment by camc314** [comment]
* **#12815** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12815?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12814** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12814?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12814?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=12814).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_linter/src/rules/eslint/no_empty_function.rs [hunk 1]
```diff
@@ -85,6 +85,8 @@ impl TryFrom<&str> for Allowed {
             "getters" | "getter" => Ok(Self::Getters),
             "setters" | "setter" => Ok(Self::Setters),
             "constructors" | "constructor" => Ok(Self::Constructors),
+            "asyncFunctions" | "async-functions" => Ok(Self::AsyncFunctions),
```
Comment (Sysix) [inline crates/oxc_linter/src/rules/eslint/no_empty_function.rs:88]: We do not need to support `async-*` option.

`private-constructors` and `protected-constructors` are only there, because `typescript-eslint` implemented them before, ESLint did with `protectedConstructors`.

https://typescript-eslint.io/rules/no-empty-function/#allow-protected-constructors
https://eslint.org/docs/latest/rules/no-empty-function#allow-protectedconstructors

https://github.com/eslint/eslint/pull/19551
https://github.com/typescript-eslint/typescript-eslint/pull/1267
