### PR TITLE
fix(linter) bug in fixer for `func-names` when function name is shadowed

### LINKED ISSUE #5229: bug(linter) bug in fixer for `func-names`
```ts
const setState = Component.prototype.setState;
Component.prototype.setState = function (update, callback) {
	return setState.call(this, update, callback);
};
```

is being fixed to
```
const setState = Component.prototype.setState;
Component.prototype.setState = function  setState(update, callback) {
	return setState.call(this, update, callback);
};
```

which is incorrect as now the `return setState.call` will now call itself rather than the `setState` from the outer scope

### PR DESCRIPTION
**Pull request by camc314**
closes #5229

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/func_names.rs [hunk 1]
```diff
@@ -455,7 +455,30 @@ impl Rule for FuncNames {
...
+                            |name| {
+                                // if this name shadows a variable in the outer scope **and** that name is referenced
+                                // inside the function body, it is unsafe to add a name to this function
+                                if ctx
+                                    .scopes()
+                                    .find_binding(func.scope_id.get().unwrap(), &name)
+                                    .map_or(false, |shadowed_var| {
+                                        ctx.semantic().symbol_references(shadowed_var).any(
+                                            |reference| {
+                                                func.span.contains_inclusive(
```
Comment (camc314) [inline crates/oxc_linter/src/rules/eslint/func_names.rs:467]: let me know if there's a better way than checking the span, but this felt easiest rather than collecting up all child scope ids of the function, and checking whether the reference is inside one of those ids

**Review by DonIsaac — APPROVED** [review]
