### PR TITLE
fix(formatter): avoid breaking generic call assignments

### LINKED ISSUE #17804: formatter: Diff with Prettier on Long generic function call
### Input

```tsx
const fooRef =
        useRef<Record<string, LazyFooThingFD<T, TError> | null | undefined>>(cache);
```

### Config

```jsonc
{
"semi": true,
"printWidth": 100,
"tabWidth": 2,
"useTabs": true,
"singleQuote": true,
"trailingComma": "all",
"bracketSpacing": true,
"bracketSameLine": false,
"proseWrap": "always",
}
```

### Oxfmt output

Oxfmt version: `X.Y.Z`
```tsx
const fooRef = useRef<
  Record<string, LazyFooThingFD<T, TError> | null | undefined>
>(cache);
```

### Oxfmt playground link

https://playground.oxc.rs/#eNptU8Fu2zAM/RVDpw3IgK7AgCLrCgztAgzo1q4N1ssutEQ7amXRk+gmXZZ/L+VYSg7NJdajSD4+Pm2VVnOlyUeuGqI7bKovf3w1/YaIgpzfoaZgziMH69tZdQ3/XhZEy5WcFlfny1m1/BYChYvqf+UH5+Rv8AYb69FcXLzToFf4/rOaKVLzrQqDT3/OelbzBlzEmWoodMCMQc05DAJwAB8TWq7YSA4YzRVqBwHYCuUSXK8sY+xBY4E68K07HDV1fcB4SImaegnv28WXriaXT7ppp2u7meohxMRrq3DD6KP0FcE4bmQecI7Wd8hD8DcDR2twMXidqOVSqSeGZ7yFILkZHfN+n333SdBodQlEFNps9SjnhAqHpNXIQb6PpNoq2c8S6sNQDPWDNbxS89OZQm9ummtZgvB1jdDtpRtP8bMT6Sb7c/hrID7o9Bg392/Af9PpNlAvvRTEDx7RoJGasigr9NpL6jpIMecElTlsGVZmWef5Jb6GlyhX6gD6Cflelibp+XJGocM986k/1Y+o+SFALzWyqKnRyPUri5D1IAwxHKWJWsVHe70YQotiO4Xx9OTjJykgCl6NTl1QuHQQ48KiM2UhuOkx2A49gxPnkRivLEaineWC/kAGAywiTFt727FblZ5RL7vH4EE8l6lqMtji+DZ82nGx42M0JI90UtN74rFWRhy2+e5YJfs8mSU/Apmc+mt8xlL0CbH/KSpn74yp4kdyC/FmynjGUFM80tL6tIMUKl87gfcPPcHla5fwJPPBrLtXVWSQ/g==

### Prettier output

Prettier version: `3.7.4`
```tsx
const fooRef =
	useRef<Record<string, LazyFoo<T, TError> | null | undefined>>(cache);
```

### Prettier playground link

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCEBKc2mAvADpSZXVUCuach2APIZAE4AmzG7AllADmAGkwAZAIYAvAJ4AxPMwAqopQFF27COwB8mAD6YotADYmDmWlE5EBcTjp0AKMBLAALOAEoA3CGEgEAAOMHzoyKASmhAA7gAKUQhoyCASJjESMskBAEbsbgDWcDAAyhIAtnBidsjYaQwBEDkAVnBgMADq+UEpQexwDOwAbnD+IHmFxSVBbgKCyDDstHABDOV8C0srIHAAHkFw-JWwaQDyB-kw2nEQaHyh0CkInGN7F3zHMGlKh1BRfANavVtnchCY4ABFWgQeCbZYBZpoXYlObgqEw0ZIOomBogACO0PgcS0QWSKAkaAAtFA4PZ7GNFhI+CY5gBhCDlcoSFJpExjUGCcEAQRgiz4OVoRMO1RpQJx23cMHKJg67nuAxmYDgJSS9z4Q3uMhSYDQ2RAQ2WAElrAhSmB+CEhdYSjAZOC5bi+rc4F0JD1yelMmbnqdsDLMSATNgxgJBjBiRJBFyPdsZuxBilXQc0Pa+CExn0BJ0+JwYO5kAAOAAMAX6BL4-QTSe5WOBAS+OQ6JbLyAATAF6HAlBIcmTFvCduUcvYbJxJEJaIm4Ap2FzRXMeZKICAAL47oA

### Additional notes

I tried to minimise the example but went slightly insane in doing so :D 
Couldn't find a relevant issue with the label of difference, but please close if already known!

### PR DESCRIPTION
**Pull request by Dunqing**
close: #17804 
close: #18927

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#18935** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18935?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18933** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18933?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18933?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=18933).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_formatter/src/formatter/source_text.rs [hunk 1]
```diff
@@ -113,6 +113,43 @@ impl<'a> SourceText<'a> {
         false
     }
 
+    /// Check for a newline after an opening brace `{`.
+    /// Unlike `has_newline_after`, this method scans through comments to find newlines.
```
Comment (leaysgur) [inline crates/oxc_formatter/src/formatter/source_text.rs:117]: 🙈

**Review by leaysgur — APPROVED** [review]
