### PR TITLE
fix(linter): fix eslint/sort-imports allowSeparatedGroups not working with single empty line

### LINKED ISSUE #15990: linter: `eslint/sort-imports/allowSeparatedGroups` does not work with single empty line
### What version of Oxlint are you using?

1.29.0

### What command did you run?

`oxlint --type-aware --config linter/eslint/sort-imports/allowSeparatedGroups/.oxlintrc.json linter/eslint/sort-imports/allowSeparatedGroups`

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "plugins": [
    "eslint"
  ],
  "rules": {
    "eslint/sort-imports": [
      "error",
      {
        "allowSeparatedGroups": true
      }
    ],
  }
}
```

### What happened?

Checkout this file or visit this repo <https://github.com/ryansuhartanto/oxc-issues/blob/main/linter/eslint/sort-imports/allowSeparatedGroups/fail.ts>:

```ts
// oxlint-disable no-unused-vars
import { format } from "oxfmt";

import { defineRule } from "oxlint";
```

This snippet will throw this error:
```
> oxc-issues@ lint /home/nexus/Dokumen/suhartanto/VCS/oxc-issues
> oxlint --type-aware --config linter/eslint/sort-imports/allowSeparatedGroups/.oxlintrc.json linter/eslint/sort-imports/allowSeparatedGroups


  × eslint(sort-imports): Imports should be sorted alphabetically.
   ╭─[linter/eslint/sort-imports/allowSeparatedGroups/fail.ts:4:1]
 3 │ 
 4 │ import { defineRule } from "oxlint";
   · ────────────────────────────────────
   ╰────

Found 0 warnings and 1 error.
Finished in 105ms on 2 files with 53 rules using 8 threads.
 ELIFECYCLE  Command failed with exit code 1.
```

Whereas this file will pass (note the extra empty line):
```ts
// oxlint-disable no-unused-vars
import { format } from "oxfmt";


import { defineRule } from "oxlint";
```

### PR DESCRIPTION
**Pull request by xuanduc987**
This fixes #15990

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/sort_imports.rs [hunk 1]
```diff
@@ -581,7 +580,7 @@ fn test() {
         (
             "import b from 'b';
 
-            import a from 'a';",
+import a from 'a';",
```
Comment (connorshea) [inline crates/oxc_linter/src/rules/eslint/sort_imports.rs:591]: Hmm, this code should pass the rule even if this import has spaces in front of it. It does in ESLint: https://eslint.org/play/#eyJ0ZXh0IjoiaW1wb3J0IHsgZm9ybWF0IH0gZnJvbSBcIm94Zm10XCI7XG5cbiAgICAgICAgIGltcG9ydCB7IGRlZmluZVJ1bGUgfSBmcm9tIFwib3hsaW50XCI7XG4iLCJvcHRpb25zIjp7InJ1bGVzIjp7InNvcnQtaW1wb3J0cyI6WyJlcnJvciIseyJhbGxvd1NlcGFyYXRlZEdyb3VwcyI6dHJ1ZX1dfSwibGFuZ3VhZ2VPcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fX0sImVjbWFWZXJzaW9uIjoyMDI2fX19

Comment (xuanduc987) [reply crates/oxc_linter/src/rules/eslint/sort_imports.rs:591]: Yes, the change in this test is to fail the previous implementation

Comment (connorshea) [reply crates/oxc_linter/src/rules/eslint/sort_imports.rs:591]: Ah, can we include both still?

Comment (xuanduc987) [reply crates/oxc_linter/src/rules/eslint/sort_imports.rs:591]: Thank you, I added a new test case instead of modifying the existing one.

**Review by camc314 — APPROVED** [review]
Thank you!
