### PR TITLE
fix(semantic): bind `TSImportEqualsDeclaration`s

### LINKED ISSUE #4091: bug(semantic): `TSImportEqualsDeclaration` does not create a symbol
```ts
import foo = require('./foo') // `foo` is not added to the symbol table
const bar = require('./bar')  // but `bar` is
```
[Playground Link](https://oxc-project.github.io/oxc/playground/?code=3YCAAIC6gICAgICAgIC0G8rnONK881UOMhQe0DpPTER984qKiS5%2F6hUUcj4033g4LUHKh5RPzqSm3ZQEfyZEIIA%3D)

This causes a false positive in `jsx-no-undef` ([example](https://oxc-project.github.io/oxc/playground/?code=3YCAAIC%2BgICAgICAgIC0G8rnONK88wEEqZ%2F5VIczOSgc6%2BPeK1FjseOeECpGxVxbCXZTvGMZ9beVDbp35khuOGcHwr6%2BebswOrdVWn89eMCA))

```tsx
import Foo = require('./bar')

const Component = () => <Foo />
```

### PR DESCRIPTION
**Pull request by DonIsaac**
Closes #4091

### CODE REVIEW

File: crates/oxc_semantic/tests/integration/modules.rs [hunk 1]
```diff
@@ -202,3 +202,25 @@ fn test_export_in_invalid_scope() {
     assert!(!errors.is_empty(), "expected an export within a function to produce a check error, but no errors were produced");
     assert!(semantic.module_record().exported_bindings.is_empty());
 }
+
+#[test]
+fn test_import_assignment() {
+    SemanticTester::ts(
+        "
```
Comment (rzvxa) [inline crates/oxc_semantic/tests/integration/modules.rs:209]: Small nitpick, You've missed formatting strings in the tests.

File: crates/oxc_linter/src/rules/react/jsx_no_undef.rs [hunk 2]
```diff
@@ -112,6 +112,16 @@ fn test() {
         ),
         ("var App; var React; enum A { App };  React.render(<App />);", None),
         ("var React; enum A { App }; var App; React.render(<App />);", None),
+        ("var React; import App = require('./app'); React.render(<App />);", None),
+        (
+            "
+        var React;
```
Comment (rzvxa) [inline crates/oxc_linter/src/rules/react/jsx_no_undef.rs:118]: Seems like this one also have the same issue.

**Review by Dunqing — APPROVED** [review]
