### PR TITLE
fix(transformer/typescript): should remove `abstract` field early

### LINKED ISSUE #5326: [Bug]: `strictExecutionOrder` breaks code with decorators on `beta.27` (works on `beta.26`)
### Reproduction link or steps

https://stackblitz.com/edit/rolldown-rolldown-starter-stackblitz-cm7zjem1?file=dist-compare%2Fentry-27.js

I just installed version 26, ran build, and then repeated that for version 27.

There are two files in `dist-compare`, one from "beta.26" and one from "beta.27". As you can see they differ quite a bit, especially with all the missing `init` function calls. You can use this to see the [diff](https://www.diffchecker.com/u16SbxU6/)

Image

### What is expected?

The build outputs should be the same. 

### What is actually happening?

Build outputs are different.

### System Info

```Shell
System:
    OS: macOS 15.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 123.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - ~/.proto/shims/node
    Yarn: 4.6.0 - ~/.proto/shims/yarn
    npm: 10.9.2 - ~/.proto/shims/npm
    pnpm: 10.9.0 - ~/.proto/shims/pnpm
```

### Any additional comments?

This is a minimal reproduction of a larger codebase. Going to version 27 breaks the code, as many of the decorate calls are missing. Also, this is probably not related to just decorators.

It might be related to this https://github.com/rolldown/rolldown/pull/5240, as it is the only thing from the changelog that is relevant.

### PR DESCRIPTION
**Pull request by Dunqing**
* close https://github.com/rolldown/rolldown/issues/5326

Regression introduced by #12212. The transform execution shift causes the bug because the `class-properties` plugin always assumes that all fields accessed can be transformed. However, the prior change breaks the assumption.

This PR reverts some changes to remove the ts-only field early, which respects that `class-properties` assumption

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#12418** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12418?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#12417** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12417?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12417?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=12417).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Boshen** [comment]
### Merge activity

* **Jul 21, 6:29 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Jul 21, 6:29 AM UTC**: `Boshen` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
* **Jul 21, 6:48 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

File: crates/oxc_transformer/src/es2022/class_properties/class.rs [hunk 1]
```diff
@@ -84,6 +84,12 @@ impl<'a> ClassProperties<'a, '_> {
         for element in &mut body.body {
             match element {
                 ClassElement::PropertyDefinition(prop) => {
+                    // // `abstract class A { abstract prop; }` or `class A extends B { override prop; }`
+                    // dbg!(prop.r#override);
+                    // if prop.r#type.is_abstract() || prop.r#override {
+                    //     continue;
+                    // }
```
Comment (Boshen) [inline crates/oxc_transformer/src/es2022/class_properties/class.rs]: Remove?

Comment (Dunqing) [reply crates/oxc_transformer/src/es2022/class_properties/class.rs]: Oops!
