### PR TITLE
fix(oxc_linter): Make linter file paths clickable within JetBrains terminals

### LINKED ISSUE #8444: Make links in Jetbrains products clickable
When using oxlint in terminal, I see that links are not clickable

[Screencast from 2025-01-12 10-25-44.webm](https://github.com/user-attachments/assets/e8acb59a-442b-4a7f-8c68-ae847442a1e4)

Same problem have biome, but they have PR that seems to fix issue https://github.com/biomejs/biome/pull/4876

### PR DESCRIPTION
**Pull request by nrayburn-tech**
JetBrains terminals don't work reliably with relative paths to hyperlink to the file. Outputting the full file URL instead works consistently.

Fixes #8444.

This seems to work, but there is some cleanup that probably needs to be done by somebody more experienced. Left some inline comments for this.

Current
image

With this change in a JetBrains terminal (IntelliJ in this case)
image

With this change in a regular macOS terminal
image

### CODE REVIEW

File: crates/oxc_diagnostics/src/service.rs [hunk 1]
```diff
@@ -128,17 +128,28 @@ impl DiagnosticService {
...
         diagnostics: Vec<OxcDiagnostic>,
-    ) -> (PathBuf, Vec<Error>) {
-        let path = path.as_ref();
-        let path_display = path.to_string_lossy();
-        // replace windows \ path separator with posix style one
-        // reflects what eslint is outputting
-        let path_display = path_display.cow_replace('\\', "/");
+    ) -> Vec<Error> {
+        #[cfg(test)]
+        let is_jetbrains_terminal = false;
```
Comment (nrayburn-tech) [inline crates/oxc_diagnostics/src/service.rs]: When running the tests through a JetBrains terminal locally, the snapshots use full file URLs instead of the relative ones. This was my attempt at fixing it, but it doesn't seem to work.

File: crates/oxc_diagnostics/src/service.rs [hunk 2]
```diff
@@ -128,17 +128,28 @@ impl DiagnosticService {
...
+        #[cfg(not(test))]
+        let is_jetbrains_terminal =
+            std::env::var("TERMINAL_EMULATOR").is_ok_and(|x| x.eq("JetBrains-JediTerm"));
+
+        let file_url = Url::from_file_path(path.as_ref());
```
Comment (nrayburn-tech) [inline crates/oxc_diagnostics/src/service.rs]: If there's a way to get the file URL without this dependency, it would probably be better to do it that way.

File: crates/oxc_diagnostics/src/service.rs [hunk 3]
```diff
@@ -128,20 +129,38 @@ impl DiagnosticService {
...
+        #[cfg(test)]
+        let is_jetbrains_terminal = false;
+        #[cfg(not(test))]
+        let is_jetbrains_terminal =
+            std::env::var("TERMINAL_EMULATOR").is_ok_and(|x| x.eq("JetBrains-JediTerm"));
+
         // replace windows \ path separator with posix style one
         // reflects what eslint is outputting
-        let path_display = path_display.cow_replace('\\', "/");
+        let default_path = path
```
Comment (nrayburn-tech) [inline crates/oxc_diagnostics/src/service.rs]: I couldn't figure out how to keep this in the `else` block below without breaking some clippy rules. I'm sure there's a better way to do it, but I reached my limits of Rust if and match statements trying to figure it out.

**Comment by nrayburn-tech** [comment]
@camc314 this isn't very high priority, but it would be a pretty good improvement for JetBrains IDEs if it was resolved. Gave it my best attempt, but I don't know very much Rust.

File: crates/oxc_diagnostics/src/service.rs [hunk 4]
```diff
@@ -128,20 +129,38 @@ impl DiagnosticService {
...
         diagnostics: Vec<OxcDiagnostic>,
-    ) -> (PathBuf, Vec<Error>) {
-        let path = path.as_ref();
-        let path_display = path.to_string_lossy();
+    ) -> Vec<Error> {
+        #[cfg(test)]
+        let is_jetbrains_terminal = false;
+        #[cfg(not(test))]
+        let is_jetbrains_terminal =
+            std::env::var("TERMINAL_EMULATOR").is_ok_and(|x| x.eq("JetBrains-JediTerm"));
```
Comment (camc314) [inline crates/oxc_diagnostics/src/service.rs]: https://github.com/biomejs/biome/blob/adaa65ce06b7882accd60a97207ad4403bde23cf/crates/biome_diagnostics/src/display.rs#L684

do we need to check `TERM_PROGRAM` as well?

File: crates/oxc_diagnostics/src/service.rs (hunk 1 above)
Comment (camc314) [reply crates/oxc_diagnostics/src/service.rs]: we could use debug assertions instead

effectivly
```
        #[cfg(debug_assertions)]
```

not 100% sure if this would work though

**Review by camc314 — APPROVED** [review]
> @camc314 this isn't very high priority, but it would be a pretty good improvement for JetBrains IDEs if it was resolved. Gave it my best attempt, but I don't know very much Rust.

thank you for working on this, this is great!
I pushed a new commit removing the `url` dependency, and the output appears to be the same?

do you mind testing this and letting me know if it still looks ok?

File: crates/oxc_diagnostics/src/service.rs (hunk 4 above)
Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: I don’t think so. I believe that is for detecting VS Code in their use case.

**Comment by nrayburn-tech** [comment]
I should be able to test later this morning and let you know.

File: crates/oxc_diagnostics/src/service.rs [hunk 5]
```diff
@@ -128,20 +128,30 @@ impl DiagnosticService {
...
+    ) -> Vec<Error> {
+        #[cfg(test)]
+        let is_jetbrains = false;
+        #[cfg(not(test))]
+        let is_jetbrains =
+            std::env::var("TERMINAL_EMULATOR").is_ok_and(|x| x.eq("JetBrains-JediTerm"));
+
+        let path_ref = path.as_ref();
+        let path_display = if is_jetbrains {
+            format!("file://{}", path_ref.to_string_lossy())
```
Comment (Sysix) [inline crates/oxc_diagnostics/src/service.rs]: JetBrains requires a URI instead of a path?

I think this will not work in windows. 
The path is `C:\Users\` and you want `file:///C:/Users/`. Notice the extra slash before the driver letter.

And it probably will not work for files with special characters, too. They need to be percent encoded.
See: https://github.com/tower-lsp-community/tower-lsp-server/pull/53/files

Comment (camc314) [reply crates/oxc_diagnostics/src/service.rs]: oh 🤦 windows machines 😞

Comment (camc314) [reply crates/oxc_diagnostics/src/service.rs]: i don't understand how biome works then?

https://github.com/biomejs/biome/blob/adaa65ce06b7882accd60a97207ad4403bde23cf/crates/biome_diagnostics/src/display.rs#L112-L146

Comment (Sysix) [reply crates/oxc_diagnostics/src/service.rs]: Looks like biome will not output a URI for JetBrains?

https://github.com/biomejs/biome/blob/adaa65ce06b7882accd60a97207ad4403bde23cf/crates/biome_diagnostics/src/display.rs#L120-L121

I guess for non VSCode/JetBrains terminal, biome has a bug in there. Will double-check and create an issue on their side.

EDIT: This is not the right code part? I get for non JetBrains terminal, I still get a path (could not test it with JetBrains):
```
C:\Users\sysix\Desktop\biome-uri-test\hallöchenWelt.ts:1:1 lint/suspicious/noDebugger  FIXABLE  ━━━━━━━━━━

  × This is an unexpected use of the debugger statement.

  > 1 │ debugger;
      │ ^^^^^^^^^

  i Unsafe fix: Remove debugger statement

    1 │ debugger;
      │ ---------

C:\Users\sysix\Desktop\biome-uri-test\helloWorld.ts:1:1 lint/suspicious/noDebugger  FIXABLE  ━━━━━━━━━━

  × This is an unexpected use of the debugger statement.

  > 1 │ debugger;
      │ ^^^^^^^^^
```

Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: Ya Biome uses the "at {relativePath}" format which works in some cases (maybe all?). It relies on the IntelliJ tooling that converts a Java stacktrace into a clickable URL. It seems to work, but it seems odd to rely on a Java feature to make something for JavaScript work which is why I chose the absolute file URI. I didn't realize it would be problematic though.

Maybe just using "at {relativePath}" is the way to go.

**Comment by nrayburn-tech** [comment]
> do you mind testing this and letting me know if it still looks ok?

On macOS the tests still fail when running through a JetBrains terminal. The tests pass through a regular macOS terminal. The output from the CLI looks fine when running through a JetBrains terminal.
I don't have anything "weird" with my file paths and I'm not using Windows though, so none of what Sysix mentioned as concerns was tested.

File: crates/oxc_diagnostics/src/service.rs (hunk 1 above)
Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: This doesn't seem to make a difference. Both cfg settings (mine and your suggestion) are failing. I'm not doing anything different when I run the test though and maybe that's a problem?

1. Running `cargo build -p oxlint`.
2. Running `just test` in a terminal within IntelliJ.
3. Running `just test` in a regular macOS terminal.

File: crates/oxc_diagnostics/src/service.rs (hunk 5 above)
Comment (camc314) [reply crates/oxc_diagnostics/src/service.rs]: > Ya Biome uses the "at {relativePath}" format which works in some cases (maybe all?). It relies on the IntelliJ tooling that converts a Java stacktrace into a clickable URL. I

oh this sounds horrible lol.

@Sysix what do you think? I'm leaning to just reverting my commit and using the url dependency?

Comment (Sysix) [reply crates/oxc_diagnostics/src/service.rs]: I am not sure if `urlencode` is the right dependency, see the [pull request](https://github.com/tower-lsp-community/tower-lsp-server/pull/53#issuecomment-2954241543) for LSP.
URL != URI. Another package should fit better. Probably just copy the `from_file_path` from the PR.
Do not know if we need to skip the encoding of `:` for the driver letter. I would have guess no, because `/C` is the path in the encoding part of a URI.

Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: Some testing notes.

git bash within IntelliJ on windows
- file URI always worked. Requires percent encoding characters such as ñ. Requires the third slash before the drive letter. Does not require percent encoding the “:” as part of the drive letter, but works if it is encoded.
- The “ at {path}” format only worked if a line and column were also supplied. Did not seem to require percent encoding characters such as ñ.

command prompt within IntelliJ on windows
- file URI works with paths that do not contain special characters. Special characters break it regardless of encoding or not. Percent encoding the “:” from the drive name seemed to break it.
- The “ at {path}” format didn’t seem to work at all.

Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: I’m going to mark this as draft until the PR that Sysix references has been merged in. Once that is done, I’ll just copy the code that we need from there.

Waiting for the PR to merge, so that I can copy it with a specific commit and put the right license info inline.

File: crates/oxc_diagnostics/src/service.rs (hunk 1 above)
Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: If anybody has any idea how to ignore the env check during tests, I still need a working solution so that testing within IntelliJ terminals don’t fail the snapshots.

File: crates/oxc_diagnostics/src/service.rs (hunk 5 above)
Comment (Sysix) [reply crates/oxc_diagnostics/src/service.rs]: The referenced PR is merged. 🎉

File: crates/oxc_diagnostics/src/service.rs (hunk 1 above)
Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: I pulled the if statement out and left a todo since I can't get it working. If anybody has suggestions, feel free to let me know.

File: crates/oxc_diagnostics/src/service.rs (hunk 5 above)
Comment (nrayburn-tech) [reply crates/oxc_diagnostics/src/service.rs]: Updated with the code from the PR. One change is that we need the `C:` not the encoded version.

**Comment by nrayburn-tech** [comment]
I don't have a Windows device to test on until a release is made, but the macOS changes still look fine to me.

**Review by Sysix — APPROVED** [review]
Could not test it, LGTM

**Review by camc314 — APPROVED** [review]
thank you!
