### PR TITLE
fix(linter): Fix the path used in the gitlab format output

### LINKED ISSUE #17999: linter: gitlab format should output repo-relative paths
### What version of Oxlint are you using?

1.39.0

### What command did you run?

`oxlint --format gitlab`

### What does your `.oxlintrc.json` config file look like?

No `.oxlintrc.json`.

### What happened?

The `location.path` in gitlab formatted output should be relative to the closest git repo root, not the CWD (see [docs](https://docs.gitlab.com/ci/testing/code_quality/#code-quality-report-format)).

> The file containing the code quality violation, expressed as a relative path **in the repository**. Do not prefix with ./.

Steps to reproduce:
```bash
# Create temp folder and git repo:
cd $(mktemp -d)
git init .

# Create subfolder and install oxlint:
mkdir pathFromRepoRoot && cd pathFromRepoRoot
yarn add -DE oxlint

# Create and lint example file:
echo "const unused = 2;" > example.js
yarn oxlint --format gitlab
```

Actual output:
```json
[
  {
    "description": "Variable 'unused' is declared but never used. Unused variables should start with a '_'.",
    "check_name": "eslint(no-unused-vars)",
    "fingerprint": "92988ecf75890d1d",
    "severity": "major",
    "location": {
      "path": "example.js",
      "lines": {
        "begin": 1,
        "end": 1
      }
    }
  }
]
```

Expected output:
```json
[
  {
    "description": "Variable 'unused' is declared but never used. Unused variables should start with a '_'.",
    "check_name": "eslint(no-unused-vars)",
    "fingerprint": "92988ecf75890d1d",
    "severity": "major",
    "location": {
      "path": "pathFromRepoRoot/example.js",
      "lines": {
        "begin": 1,
        "end": 1
      }
    }
  }
]
```

### PR DESCRIPTION
**Pull request by connorshea**
Fix #17999.

The path for diagnostics emitted in the GitLab Code Quality report is supposed to be relative to the repository root. This is a problem for the previous implementation, as the path was relative to the current working directory.

If you have a monorepo or some other setup where you aren't running oxlint from the repo root, (e.g. a repo where all JS frontend code is in a `client/` directory), then the paths will be incorrect in the GitLab report generated by Oxlint.

This PR updates the formatter logic so we append 

AI Disclosure: This change was mainly made via AI (Copilot + Claude Opus 4.5) and can probably be made better/more performant. The code feels rather cursed because of needing to deal with finding the repository root and handling windows paths as well, feel free to suggest improvements. I have confirmed it works by building and running oxlint on a repo which has nesting and one which does not, and it fixes the problem while not changing the output behavior for users in a "normal" setup.

Also, this adds a Windows-only test but I can't trigger the Windows test job, so I have no idea if it passes :D

### CODE REVIEW

File: apps/oxlint/src/output_formatter/gitlab.rs [hunk 1]
```diff
@@ -85,7 +142,12 @@ fn format_gitlab(diagnostics: &mut Vec<Error>) -> String {
             description: message,
             check_name: rule_id.unwrap_or_default(),
             location: GitlabErrorLocationJson {
-                path: filename,
+                // GitLab expects file paths to be relative to the repository
+                // root, so adjust accordingly.
+                path: match repo_path_prefix {
+                    Some(prefix) => format!("{prefix}/{filename}"),
```
[the remark this answers is not in the document]
Comment (connorshea) [reply apps/oxlint/src/output_formatter/gitlab.rs]: I think we can safely ignore that case

File: apps/oxlint/src/output_formatter/gitlab.rs
Comment (connorshea) [inline apps/oxlint/src/output_formatter/gitlab.rs:127]: This should maybe be updated to the `path` value? In some cases it'd break existing hashes for projects using this, but *shrug*

File: apps/oxlint/src/output_formatter/gitlab.rs [hunk 2]
```diff
@@ -85,7 +141,23 @@ fn format_gitlab(diagnostics: &mut Vec<Error>) -> String {
...
+                        #[cfg(windows)]
+                        {
+                            let combined = prefix.join(&filename);
+                            combined.to_string_lossy().cow_replace('\\', "/").into_owned()
+                        }
+                        #[cfg(not(windows))]
+                        {
+                            prefix.join(&filename).to_string_lossy().to_string()
+                        }
+                    }
```
Comment (connorshea) [inline apps/oxlint/src/output_formatter/gitlab.rs:152]: We could handle this the same way for both if we want to, but I didn't really want to do the extra work of splitting and joining the paths or doing a replacement for no reason on macOS/Linux.

**Comment by Boshen** [comment]
### Merge activity

* **Jan 23, 5:20 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Jan 23, 5:37 AM UTC**: `Boshen` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Jan 23, 5:42 AM UTC**: The [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) couldn't merge this PR because **it was not satisfying all requirements** (Failed CI: 'Test Linux').
* **Jan 23, 7:29 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Jan 23, 7:34 AM UTC**: `connorshea` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Jan 23, 7:41 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
