### PR TITLE
fix(playground): pass transform target to minifier

### LINKED ISSUE #16889: playgrdoun: minifier does not respect set transform target
[REPL](https://playground.oxc.rs/#eNptVE1v2zAM/SuaTkmRrcUwDEWGbBjaBRjQrt1arJdcZJlJ1MqSJ9H5gOH/vifHHz30kkiPIvn4SLqWWs7lyq0rp9l4J4rj0k18mc5RLETdTEW9cis+P3snngxvfcWCtyaKnCKHSnMVjNvMhGGxN9aKjLZqR0L7EEizPQpxdr5yAoCLLGrh3a2HvUHsLsuX0ewQk/Klg3FCU7H4esp9yv6YskYQsLlwnpFJcFAurn0oKBfswYu6oMoKvVXGgRoQCop96IiInsJiIVwFxt/EzptcXIh5Z5mUPpoU5cNO2YpmgqYtxwa/K+45TqYr1wBwrWK4yJn0cl7LULn0Z41jOV8rG2kmE0fFTGFABupyDhkBmOitQuRr0laBcJJmeL3fGqZYKk0DVCi3seNV+6IMFOFyChc16h4uxyLztr/p9aZza2ayVCEmWrWkA5OLSIuB4HhAOcpav/9DaLG7qzianJbdmPShUkoKO7pXAb492vr9vfzpGLMRjR5JEViz0T9C8KFDwSFJ1XLA+ZVStawiPapslIFV9mRy3sr5x5kkl9+tb4xDldKuQbdENu7slxfIhu5b+l15HmV6joeHN+B/6XYffIlcUsX3jiinHDHRJgN6mytfFCrZrAWKOsxQLGrZ9/XDvlfHiCdZUPqF+AE9g3v/uEdVQSfmXX6fPWNbnoIqEaMXNSVquX5nCJlVYEjhlRvUGheg1YtV2BCmTupt8AV9/oQQ0PCa1vBa+nBlVYxLQzYfWkIHrIcpyLGyGD3frspoLQwP6C2xyhVDhq5vb49sLfFhMCW6TwGLOJLVPqcNtcvhUpeHgXyOucdnqNPTYbnbWD1iadO/baP0g57Gpd8C1O7LG9pRn28mX4jKXxC6H5/WFyPp7RLjmVx2FDIfX8lpXGpDMg2nBnDe6pfg4dQkvFW6K6r5D4oG4FY=) with all information.

---

### Details

```ts
function myFn(options = {}) {
	/*! Without this destructuring, it will behave correctly  */
  const { onMove } = options;
  const nestedFn = (e) => {
		/*! This should not be transformed to the optional chaining operator */
    onMove == null ? void 0 : onMove(position.value, e);
  };
	nestedFn()
}

myFn()
```

**Setup**

1. Set the target to `chrome64` (or any other target that doesn't support nullish coalescing operator)
2. Run the code through the minifier

**Expected**: No nullish coalescing operator in the output
**Actual**: Nullish coalescing operator is part of the end code due to an optimization

```ts
// OPTIMIZED CODE
function myFn(options = {}) {
	/*! Without this destructuring, it will behave correctly  */
	let { onMove } = options;
	((e) => {
		/*! This should not be transformed to the optional chaining operator */
		onMove?.(position.value, e);
	})();
}
myFn();
```

---

The same might happen for other optimizations that should not be applied for certain targets that do not support them.

Originally reported in https://github.com/vitejs/rolldown-vite/issues/556

### PR DESCRIPTION
**Pull request by camc314**
The playground minifier was not respecting the transform target option, causing ES features like optional chaining to be used even when targeting older browsers that do not support them.

Closes #16889

### CODE REVIEW

**Comment by camc314** [comment]
* **#16910** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16910?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16910?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=16910).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: napi/playground/src/lib.rs [hunk 1]
```diff
@@ -318,7 +318,16 @@ impl Oxc {
             return None;
         }
         let compress = if options.run.compress {
-            options.compress.map(|_| CompressOptions::smallest())
+            options.compress.map(|_| {
+                let mut compress_options = CompressOptions::smallest();
+                if let Some(transform_options) = &options.transformer
+                    && let Some(target) = &transform_options.target
+                    && let Ok(targets) = oxc_compat::EngineTargets::from_target(target)
```
Comment (sapphi-red) [inline napi/playground/src/lib.rs]: I think we should call `.map_err(|err| self.diagnostics.push(OxcDiagnostic::error(err)))` like the code above here.

**Review by sapphi-red — COMMENTED** [review]
It feels a bit off to respect the options in `transform` section, but I guess that's fine for now.

File: napi/playground/src/lib.rs (hunk 1 above)
Comment (camc314) [reply napi/playground/src/lib.rs]: good call

**Comment by camc314** [comment]
> It feels a bit off to respect the options in `transform` section, but I guess that's fine for now.

I don't think a separate option makes sense? i.e. why would i want to transform to chrome64, but minify to chrome 80?

**Review by sapphi-red — APPROVED** [review]

**Comment by sapphi-red** [comment]
> > It feels a bit off to respect the options in `transform` section, but I guess that's fine for now.
> 
> I don't think a separate option makes sense? i.e. why would i want to transform to chrome64, but minify to chrome 80?

It's more of a UI problem than the behavior.
