### PR TITLE
fix(ast)!: add `TSGlobalDeclaration` type

### LINKED ISSUE #14860: ast: remove `BindingIdentifer` `TSModuleDeclaration` when `ModuleDeclarationKind` is global
# What's the problem?

Given the following code:
```
declare global {}
```

We produce an ast, `global` is an `BindingIdentifier`.
However, we currently have an escapt hatch in semantic that does not assign is a SymbolId:

https://github.com/Boshen/oxc/blob/ae2003c656fd6c89f8f77a8079addf1d59990c1b/crates/oxc_semantic/src/binder.rs#L369-L372

This breaks the invariant, that states that `SymbolId`s are always defined once an AST bas been processed through semantic

https://github.com/Boshen/oxc/blob/bec7a7da62fd01164880193e89c849c25c33740b/crates/oxc_ast/src/generated/get_id.rs#L49

We have this escape hatch to avoid the following problem:
```
declare global {}

type T = global
```

Without the escape hatch, `global` on line 3 is resolved to `declare global`. This is incorrect as `global` is a special case.

# How should we fix it?

This should be fixed by doing something like:

(I attempted it, but the current ast tools implementation lacks some of the features I need and I don't know it well enough to change.)

```diff
diff --git a/crates/oxc_ast/src/ast/ts.rs b/crates/oxc_ast/src/ast/ts.rs
index 02da05921..40ad16ce9 100644
--- a/crates/oxc_ast/src/ast/ts.rs
+++ b/crates/oxc_ast/src/ast/ts.rs
@@ -1206,38 +1206,24 @@ pub struct TSModuleDeclaration<'a> {
     ///
     /// Note that for `declare global {}`, no symbol will be created for the module name.
     #[estree(ts_type = "BindingIdentifier | StringLiteral | TSQualifiedName")]
-    pub id: TSModuleDeclarationName<'a>,
+    pub id: TSModuleDeclarationKind<'a>,
     #[scope(enter_before)]
     #[estree(ts_type = "TSModuleBlock | null")]
     pub body: Option<TSModuleDeclarationBody<'a>>,
-    /// The keyword used to define this module declaration.
-    ///
-    /// Helps discriminate between global overrides vs module declarations vs namespace
-    /// declarations.
-    ///
-    /// ```ts
-    /// namespace Foo {}
-    /// ^^^^^^^^^
-    /// module 'foo' {}
-    /// ^^^^^^
-    /// declare global {}
-    ///         ^^^^^^
-    /// ```
-    pub kind: TSModuleDeclarationKind,
     pub declare: bool,
     pub scope_id: Cell<Option<ScopeId>>,
 }
 
-#[ast]
-#[derive(Debug, Clone, Copy, PartialEq, Eq)]
+#[ast(visit)]
+#[derive(Debug)]
 #[generate_derive(CloneIn, Dummy, ContentEq, ESTree)]
-pub enum TSModuleDeclarationKind {
+pub enum TSModuleDeclarationKind<'a> {
     /// `declare global {}`
     Global = 0,
     /// `declare module 'foo' {}`
-    Module = 1,
+    Module(Box<'a, TSModuleDeclarationName<'a>>) = 1,
     /// `namespace Foo {}`
-    Namespace = 2,
+    Namespace(Box<'a, BindingIdentifier<'a>>) = 2,
 }
 
 /// The name of a TypeScript [namespace or module declaration](TSModuleDeclaration).
```

This improves the tightness of our ast, by making it impossible for:
 - the `kind` to be `Namespace` and the `id` to be a `StringLiteral`
 - the `kind` to be `Global` and the `id` to have a SymbolId
 - the `kind` to be global and the `id` to be a `StringLiteral`

### PR DESCRIPTION
**Pull request by overlookmotel**
Fix #14860.

### The problem

`TSModuleDeclaration` type was used to represent 4 different syntaxes:

* `namespace X {}`
* `module X {}`
* `module "x" {}`
* `global {}`

(and all the above prefixed with `declare`)

`global {}` is quite different from the others in a few ways:

* It has no identifier (`global` is a keyword, not an identifier).
* It has no symbol.
* The `body` block is not optional.
* Directives are not allowed in the `body` block.
* It is always ambient context (regardless of whether it has `declare` modifier).

In particular, it was causing panics because `symbol_id` field for `TSModuleDeclaration`s representing `global {}` was `None`.

### Solution

Rather than trying to make `TSModuleDeclaration` type encode all these differences, and make Oxc's code reason about them, split `global {}` into a new type `TSGlobalDeclaration`.

The rest of the diff is just adjusting code to also handle `TSGlobalDeclaration` where it was dealing with `TSModuleDeclaration`s.

This change simplifies the parser quite a bit.

`oxc_semantic`'s `SymbolDeclarationTest` tester now tests that all `TSModuleDeclaration`s with `id: BindingIdentifier` do have a symbol:

https://github.com/oxc-project/oxc/pull/15712/files#diff-ce544d71b839faa898887ac920237e563e59a708e7fca86b53023498ab67a611L101-R110

### CODE REVIEW

**Comment by overlookmotel** [comment]
* **#15712** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15712?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#15720](https://github.com/oxc-project/oxc/pull/15720) <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15720?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#15722](https://github.com/oxc-project/oxc/pull/15722) <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15722?utm_source=stack-comment-icon" target="_blank">Graphite</a>) 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15712?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#15711** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15711?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=15712).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_transformer/src/typescript/namespace.rs [hunk 1]
```diff
@@ -55,8 +55,15 @@ impl<'a> Traverse<'a, TransformState<'a>> for TypeScriptNamespace<'a, '_> {
...
                 }
+                Statement::TSGlobalDeclaration(decl) => {
+                    if !self.allow_namespaces {
+                        self.ctx.error(namespace_not_supported(decl.span));
+                    }
+                    continue;
+                }
                 Statement::ExportNamedDeclaration(export_decl)
                     if export_decl.declaration.as_ref().is_some_and(|declaration| {
+                        // Note: No need to check for `TSGlobalDeclaration` here, as it can't be exported
```
Comment (camc314) [inline crates/oxc_transformer/src/typescript/namespace.rs:66]: maybe add a debug assertion?

**Review by camc314 — APPROVED** [review]

File: crates/oxc_transformer/src/typescript/namespace.rs (hunk 1 above)
Comment (overlookmotel) [reply crates/oxc_transformer/src/typescript/namespace.rs:66]: Good idea! Done in 3f85660b073767dfc9722b282f2b6f7f63a48dbf.

**Comment by overlookmotel** [comment]
https://github.com/oxc-project/monitor-oxc/actions/runs/19389800278

**Comment by overlookmotel** [comment]
I assume this'll break Rolldown, but probably not too hard to fix.

**Comment by overlookmotel** [comment]
> https://github.com/oxc-project/monitor-oxc/actions/runs/19389800278

I don't know how to interpret these results. Everything is also broken on main, right?

**Comment by camc314** [comment]
> > https://github.com/oxc-project/monitor-oxc/actions/runs/19389800278
> 
> I don't know how to interpret these results. Everything is also broken on main, right?

I tested rolldown, and updated my oxc update PR - all looks OK.

Unfortunayly, some of the packages in ecysostem CI contain invalid JS which makes it hard to tell what's correct/not. Nothing paniced which is a good sign

**Review by Boshen — DISMISSED** [review]
Already queued a few breaking changes in today's release, so block merge until tomorrow.

**Review by Dunqing — APPROVED** [review]
I've fixed the formatter issue; feel free to merge it!

**Comment by overlookmotel** [comment]
> I've fixed the formatter issue; feel free to merge it!

Ah ha. Smart!

File: crates/oxc_transformer/src/typescript/namespace.rs [hunk 2]
```diff
@@ -198,6 +206,10 @@ impl<'a> TypeScriptNamespace<'a, '_> {
                 Statement::TSModuleDeclaration(decl) => {
                     self.handle_nested(decl, /* is_export */ false, &mut new_stmts, None, ctx);
                 }
+                Statement::TSGlobalDeclaration(_) => {
+                    // Remove it
+                    // TODO: Is it even possible for a`TSGlobalDeclaration` to be nested within a `TSModuleDeclaration`?
+                }
```
[the remark this answers is not in the document]
Comment (overlookmotel) [reply crates/oxc_transformer/src/typescript/namespace.rs:212]: You're right. But I want to get this merged, so I'll address it in a follow-up PR.
