### PR TITLE
fix(linter/plugins): align `RuleMeta.replacedBy` type with ESLint

### LINKED ISSUE #21539: linter: Wrong type annotation for JS plugin `rule.meta.replacedBy`
Oxlint has type `rule.meta.replacedBy?: RuleReplacedByInfo[]` for JS plugin.
But ESLint has `rule.meta.replacedBy?: readonly string[] | undefined;` defined [here](https://github.com/eslint/rewrite/blob/e8ec3dfe3c5d4c1f23856f04239feb4650fb0033/packages/core/src/types.ts#L184).

The below screenshot shows the type error when I'm trying to pass down `eslintCompatPlugin({ ... })` into the type of `import('@eslint/core').Plugin`

Image

### PR DESCRIPTION
**Pull request by babu-ch**
Closes #21539

### CODE REVIEW

File: apps/oxlint/src-js/plugins/rule_meta.ts [hunk 1]
```diff
@@ -51,11 +51,10 @@ export interface RuleMeta {
    */
   deprecated?: boolean | RuleDeprecatedInfo;
   /**
-   * Information about available replacements for the rule.
-   * This may be an empty array to explicitly state there is no replacement.
+   * Name of the rule(s) this rule was replaced by, if it was deprecated.
    * @deprecated Use `deprecated.replacedBy` instead.
    */
-  replacedBy?: RuleReplacedByInfo[];
```
Comment (camc314) [inline apps/oxlint/src-js/plugins/rule_meta.ts:58]: do we need to remove this type now?

Comment (babu-ch) [reply apps/oxlint/src-js/plugins/rule_meta.ts:58]: Wow, thank you for the quick review!
no, it's still used by `RuleDeprecatedInfo.replacedBy`

**Review by camc314 — COMMENTED** [review]
thank yoU!

**Review by camc314 — APPROVED** [review]
Thank you!


upstream type for reference:

https://github.com/eslint/rewrite/blob/10a31e86f35d9ac56804ba610139c637a2bf44f2/packages/core/src/types.ts#L177-L181
