### PR TITLE
fix(parser): validate inner expression of type assertions in assignment targets

### LINKED ISSUE #12612: parser/semantic: missing error when LHS of an assignment expression cannot be assigned to inside a TS expression
https://playground.oxc.rs/#eNo9j8Fqw0AMRH/F6JRAKE1KLy69lVxb2msv8loOC+uVkeQ0IeTfq7Vjn1azSPNmbhCghk3HvNlWqJUP2+q92h9e3n7z/Dsr2AFDfQMZc3n0mg0vUHeYlHaQYrZVaOCBoDYZi7j2DadFmWDWjqV/LN93MKAoSfHElPjvm2yU/DmaxpaOYw4W2Ynz+SDku2f6QqGsK4JHCXSMiTL2DgYjtSfTC7h9STbZ+7zSZ56hnMhjA+nhef/qDaNyQqP2g0JCwYJ2ypI0cEsnmuo7qUn0M4F7HOYkvtLHHLu48AJnE05Hr1WOziQNqwecDUsgh0eB+z9k9YdH

An error should be reported

```
(foo() as bar) = 123
```

### PR DESCRIPTION
**Pull request by camc314**
fixes #12612

### CODE REVIEW

**Comment by camc314** [comment]
* **#12614** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12614?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/12614?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=12614).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_parser/src/js/grammar.rs [hunk 1]
```diff
@@ -27,6 +27,18 @@ impl<'a> CoverGrammar<'a, Expression<'a>> for AssignmentTarget<'a> {
 
 impl<'a> CoverGrammar<'a, Expression<'a>> for SimpleAssignmentTarget<'a> {
     fn cover(expr: Expression<'a>, p: &mut ParserImpl<'a>) -> Self {
+        macro_rules! cover_ts_expr {
```
Comment (Boshen) [inline crates/oxc_parser/src/js/grammar.rs]: no macros please 🙇

Comment (camc314) [reply crates/oxc_parser/src/js/grammar.rs]: fixed, it's a little more verbose, but no macros 🎉

**Comment by Boshen** [comment]
### Merge activity

* **Aug 1, 4:42 AM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Aug 1, 4:42 AM UTC**: `Boshen` added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
* **Aug 1, 4:50 AM UTC**: Merged by the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
