### PR TITLE
fix(linter): can't disable `no-nested-ternary` rule anymore

### LINKED ISSUE #8485: linter: cannot disable no-nested-ternary rule anymore
### What version of Oxlint are you using?

0.15.6

### What command did you run?

oxlint -c .oxlintrc.json src

### What does your `.oxlint.json` config file look like?

{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "env": {
    "browser": true,
    "es2024": true
  },
  "settings": {},
  "plugins": ["oxc", "typescript", "unicorn"],
  "categories": {
    "correctness": "error",
    "perf": "error",
    "suspicious": "error",
    "restriction": "error",
    "style": "warn",
    "pedantic": "warn",
    "nursery": "off"
  },
  "rules": {
    "no-nested-ternary": "off",
    "eslint/no-nested-ternary": "off",
    "unicorn/no-nested-ternary": "off"
  }
}

### What happened?

Since the new 'eslint/no-nested-ternary' rule appeared in 0.15.x (duplicating/replacing the previous unicorn/no-nested-ternary rule?), it seems it cannot be deactivated anymore. With the above setup the rule is still active and generates warning.
It was not the case in 0.14.x

### PR DESCRIPTION
**Pull request by shulaoda**
closes #8485 

Since we currently support two rules with the same `rule_name` but different `plugin_names`, some of the original logic is no longer applicable. As a result, I have made some adjustments.

### CODE REVIEW

File: crates/oxc_linter/src/config/rules.rs [hunk 1]
```diff
@@ -131,8 +131,10 @@ impl OxlintRules {
                             ));
                         }
                     } else if rule_configs.iter().all(|r| r.severity.is_allow()) {
-                        if let Some(rule) = rules_for_override.iter().find(|r| r.name() == *name) {
```
Comment (shulaoda) [inline crates/oxc_linter/src/config/rules.rs:134]: Currently, we support multiple identical rules with different plugins, which may introduce potential issues. However, I am only addressing the related issues at the moment, without making further changes to avoid introducing other problems.

https://github.com/oxc-project/oxc/blob/c390fdf332e7e0cbb519b3cb352ccee2fc6a687a/crates/oxc_linter/src/config/rules.rs#L121-L123

File: crates/oxc_linter/src/config/rules.rs [hunk 2]
```diff
@@ -465,9 +469,8 @@ mod test {
     fn test_override_plugin_prefix_duplicates() {
         let configs = [
             // FIXME: this should be valid
-            // json!({ "@typescript-eslint/no-unused-vars": "error" }),
-            json!({ "no-unused-vars": "off", "typescript/no-unused-vars": "error" }),
-            json!({ "no-unused-vars": "off", "@typescript-eslint/no-unused-vars": "error" }),
```
Comment (shulaoda) [inline crates/oxc_linter/src/config/rules.rs:470]: `@typescript-eslint/no-unused-vars` does not exist.

File: crates/oxc_linter/src/config/rules.rs [hunk 3]
```diff
@@ -465,9 +469,8 @@ mod test {
...
+            // json!({ "@unicorn-eslint/no-nested-ternary": "error" }),
+            json!({ "no-nested-ternary": "off", "unicorn/no-nested-ternary": "error" }),
```
Comment (shulaoda) [inline crates/oxc_linter/src/config/rules.rs:473]: `"no-nested-ternary"` => `"eslint/no-nested-ternary"`

Currently, we do not support rules without an explicit plugin_name, which would automatically match all rules:
`"no-nested-ternary"` => `"eslint/no-nested-ternary"` and  `"unicorn/no-nested-ternary"`

File: crates/oxc_linter/src/config/rules.rs (hunk 2 above)
Comment (Sysix) [reply crates/oxc_linter/src/config/rules.rs:470]: here is the rule: https://typescript-eslint.io/rules/no-unused-vars/

Internally we are remapping some eslint rules to typescript here:
https://github.com/oxc-project/oxc/blob/d966e0addafc4e0160ea27bf2d65e8b97ef299cb/crates/oxc_linter/src/utils/mod.rs#L55-L74

Comment (shulaoda) [reply crates/oxc_linter/src/config/rules.rs:470]: > Internally we are remapping some eslint rules to typescript here:

Got it.

**Review by Sysix — COMMENTED** [review]
Thanks you for your work 🫶 
Could you please create a CLI snapshot test for it too? 
Then we can be sure that the implementation from start to end is correct.

**Review by Sysix — APPROVED** [review]
