### PR TITLE
fix(linter): find disabled directives using the message's `Span`.

### LINKED ISSUE #4005: linter: `no-empty-file` does not respect disable directive comments
When `oxlint -D no-empty-file` is run on a file like this:
```js
/* eslint-disable no-empty-file */
```

`no-empty-file`'s reported error is not filtered out by `DisableDirectives`.

### PR DESCRIPTION
**Pull request by rzvxa**
fixes #4005

### CODE REVIEW

**Comment by rzvxa** [comment]
* **#4010** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4010?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by DonIsaac — APPROVED** [review]

File: crates/oxc_linter/src/rules/unicorn/no_empty_file.rs [hunk 1]
```diff
@@ -58,7 +58,7 @@ impl Rule for NoEmptyFile {
             return;
         }
 
-        ctx.diagnostic(no_empty_file_diagnostic(Span::new(0, 0)));
+        ctx.diagnostic(no_empty_file_diagnostic(program.span));
```
Comment (Boshen) [inline crates/oxc_linter/src/rules/unicorn/no_empty_file.rs:61]: This will spit out a huge diagnostic if the file has lots of commented code. Pointing to the first line should be fine here?

**Review by Boshen — CHANGES_REQUESTED** [review]
Also need a test case.

File: crates/oxc_linter/src/rules/unicorn/no_empty_file.rs (hunk 1 above)
Comment (rzvxa) [reply crates/oxc_linter/src/rules/unicorn/no_empty_file.rs]: I've limited it to the first 100 characters to avoid searching for the new line.
Disable comments without any leading or trailing spaces and with only a single rule(`no-empty-file`) is 34 characters, So a hundred should be plenty for multi-rule comments or weirdly formatted ones.

Let me know if this doesn't work for you or if you insist on limiting it to exactly the first line.

**Review by Boshen — APPROVED** [review]
