### PR TITLE
fix(minifier): skip inlining constant in scopes with eval

### LINKED ISSUE #7846: [Bug]: Rolldown optimizes out scope variable assigned by `eval`
### Reproduction link or steps

https://repl.rolldown.rs/#eNptTssKgzAQ/JVlL1oqtr0q9tRL/0EQ0aSkxI1oYiOSf28SsaeedufBzGzIsdhwUlL26kN5p4iLV/6eA0tY/FMy7LzA7KgmDT3jrZEatpoABI1GF5DkF0E9s96cZIFXRkchmoJNCmKPldpBdM8h5MwF6Mmw6AYYBAm+7lRgXE0OXYZH6jHuh/dJMV4yDQoquJYHauLHllamScC2upVNlZ6quz2r5BTVJg3X96DzPYsPk61ms0b3BTSOXiI=

### What is expected?

```js
{let o=0,_;eval(`let x=1;_=()=>x+o`),_()}
```

### What is actually happening?

```js
{let o=0,_;eval(`let x=1;_=()=>x+o`),(void 0)()}
```

### System Info

```Shell
System:
    OS: Linux 6.17 EndeavourOS
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 10.06 GB / 15.36 GB
    Container: Yes
    Shell: 5.3.3 - /bin/bash
  Binaries:
    Node: 24.8.0 - /run/user/1000/fnm_multishells/26925_1768214392161/bin/node
    Yarn: 1.22.22 - /run/user/1000/fnm_multishells/26925_1768214392161/bin/yarn
    npm: 11.6.0 - /run/user/1000/fnm_multishells/26925_1768214392161/bin/npm
    pnpm: 10.19.0 - /run/user/1000/fnm_multishells/26925_1768214392161/bin/pnpm
    bun: 1.3.5 - /home/reve/.bun/bin/bun
    Deno: 2.6.3 - /home/reve/.deno/bin/deno
  Browsers:
    Brave Browser: 143.1.85.118
```

### Any additional comments?

This pattern seems to be a little faster than 
```js
new Function('o', 'var x=1;return ()=>x+o')(0)(o)
``` 
so I want to try it out for some compilation work.

### PR DESCRIPTION
**Pull request by camc314**
fixes https://github.com/rolldown/rolldown/issues/7846

### CODE REVIEW

**Comment by camc314** [comment]
* **#18037** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18037?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#18036** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/18036?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#17926** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/17926?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/17926?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=17926).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs [hunk 1]
```diff
@@ -28,6 +28,16 @@ fn test_inline_single_use_variable() {
     test_same("async function wrapper(arg0, arg1) { await using x = foo; return x}");
     test_same("function wrapper(arg0) { eval('x'); var x = arg0; return x }");
 
+    test("{ let _; eval('_ = () => 1'); _() }", "{ let _; eval('_ = () => 1'), _() }");
+    test(
+        "{ let x = 1; eval('x = 2'); console.log(x) }",
+        "{ let x = 1; eval('x = 2'), console.log(x) }",
+    );
```
Comment (armano2) [inline crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs]: q: should this use test_same


```suggestion
    test("{ let _; eval('_ = () => 1'); _() }", "{ let _; eval('_ = () => 1'), _() }");
    test_same("{ let x = 1; eval('x = 2'); console.log(x) }");
```

Comment (camc314) [reply crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs]: yep

Comment (camc314) [reply crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs]: thanks - fixed

Comment (armano2) [reply crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs]: ops, this is wrong i just realized that there is `;` and `,`, sorry, PR looks good

Comment (camc314) [reply crates/oxc_minifier/tests/peephole/inline_single_use_variable.rs]: lol they look so similar

File: crates/oxc_minifier/src/ctx.rs [hunk 2]
```diff
@@ -197,8 +198,13 @@ impl<'a> Ctx<'a, '_> {
         }
 
         let scope_id = self.scoping.current_scope_id();
+        let scope_flags = self.scoping().scope_flags(scope_id);
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/ctx.rs:201]: Shouldn't this be the scope that the variable exists instead of the scope that is delcared?
Example:
```js
function foo() {
  {
    var bar = 0
  }
  eval("bar = 1");
  console.log(bar)
}
```

Comment (camc314) [reply crates/oxc_minifier/src/ctx.rs:201]: yes.. interestingly this case doesn't caue issues as `var` declarations are never inlined.

Fixed + added a test

https://github.com/Boshen/oxc/blob/3984750c69ecabe9cf152871b3da14941a7c7370/crates/oxc_minifier/src/peephole/inline.rs#L15

**Review by sapphi-red — APPROVED** [review]
