### PR TITLE
fix(formatter): Print comment in ternary jsx

### LINKED ISSUE #16194: formatter: Diff with Prettier on breaking ternary JSX with trailing `LineComment`
### Input

```tsx
{isVideo ? (
  <Video {...props} />
) : (
  <Image {...props} /> // eslint-disable-line
)}
```

### Config

```jsonc
{}
```

### Oxfmt output

Oxfmt version: `main@d053892`
```tsx
{
  isVideo ? <Video {...props} /> : <Image {...props} />; // eslint-disable-line
}

```

### Oxfmt playground link

https://playground.oxc.rs/#eNptU01v2zAM/SuGThuQj67AgCIYNgztAhTo1m4d2ksvtE27SmXJE+kkheH/PsqxlBToydajSD4+PvWqUCvVa3rQJbrsW/bhyWbZl8OpXywWrXctDdny65P9mK2m8HUDNb4NZ8tlhmS05XmpCXKDczmgZA1qppxa9cp3NnzCHbWqwBDOVOV8A8zo1Yp9JwB7sBTQdEWTM8BYXmFhwANrZykFd8+akVooMEEN2Nocj4VrWo90TKHCtRI+tKPXJncmnoqqnq4NM9WCp8CrV7hntCR9RSqmvcwDxrjdH+TO29uOSdRad7YI1GKp0BP9Fu/AS25Ex7yHi2vLXkvFIgUIhTbr4of3zk+ocAhajRzk/0SqXnWEfyE/DsWQP+qSn9XqfKbQlrfVjagvfE0ldFvpxlP84ky66SDR787xUacN7e/fgf+F013YshQDmlvEEkupKYvSQq++dE0DIWaMoDKHTsPKLLs4v8R38EpyJfdQvCDfy9IkPV6OKDR4YD71d/kGC3700EqNKGpoNHL9ziJk3glD9Cdpolby0UEvBl+j2E4hnZ99+iwFRMErrCRn7fylAaK1RlOmheC+Ra8btAxGnOfEeGkxEm00J/QnMpTAIsK0tfcd2ysSsq3sHr0F8VykWrgSaxzfhg07TnbcUOnkeU5qWut4rBURg3W8O1aJPg9miY9AJnftDW4xFX1BbH+JytE7Y6r40Zm1eDNkbNHnjk601DbsIITS3yBwOcoX4PQ3BDzIfDTr8B+Lio2T

### Prettier output

Prettier version: `3.7.0`
```tsx
{
  isVideo ? (
    <Video {...props} />
  ) : (
    <Image {...props} /> // eslint-disable-line
  );
}

```

### Prettier playground link

https://deploy-preview-18323--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwCWBnAamgJnCAAgH5CAKAHSkMIB4d8jgA6VgBwCcI2MBfQgPQA+KgEpCSclRq0AkgFsAhgHM4hFuy49+wwQMJwMAGzSwAtLkyKARkbhmTUOGN4gANCG4w00DMlCKHFwA7gAKgQh+KIpGwYoAnn4e1hyKYADWcDAAyorycAAypnDIAGYxGHAeENYAVnBgMADqqWzIIJyGcBwAbiXJqRlZ2WxppsrIMBwArlUglfJokzNzcAAebN1o+bAxAPKbqTAQHKEQGGje0O0IuO4g64fbCDAxACrdUIFohmUVcxcoMo7ABFaYQeB-IyVDy1DBrbLjUHgyFIcrQuYARxRcFCWiiIEUGDMTjg+DuHimijQjmUAGEIPIlO0YkZ7oDgXAAIIwKZoazTeChbpFJxQmEgAAWMHkRiaksuhlGYDg2UilzQPUu8XaYAwSRAPVmsig+Fg2TAHDQbBgXNN2Rg8Ts4rmnHOcBaijaKE6lV6-RApj9MDxKmZaP+HlGHD97UdmwwlutMHunFMzTwMElyAAHAAGDwcODYtBF0PKcPoiWvaxNTPZpAAJg800qbxsUSrq3k1jJ5IKiiB0xUcAAYiclLzxizBRAQLxeEA

### Additional notes

_No response_

### PR DESCRIPTION
**Pull request by leaysgur**
Fixes #16194

Just prints `self.expression`, instead of `FormatNodeWithoutTrailingComments`.

Aligned with Prettier 3.7.1 outputs:

```tsx
{
  isVideo ? (
    <Video {...props} />
  ) : (
    <Image {...props} /> // eslint-disable-line
  );
}

<>
  {isVideo ? (
    <Video {...props} />
  ) : (
    <Image {...props} /> // eslint-disable-line
  )}
</>;
```

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwCWBnAamgJnCAAgH5CAKAHSkMIB4d8jgA6VgBwCcI2MBfQgPQA+KgEpCSclRq0AkgFsAhgHM4hFuy49+wwQMJwMAGzSwAtLkyKARkbhmTUOGN5UqtEVHTY8BElOo6Bj8NZk5uPkFPcUlKQLklVXVWMK1I3QF9Q0cYCytbe0dnKFFXKFphEAAaEG4YNGgMZFBFDi4AdwAFVoQmlEUjdsUATyaa6w5FMABrOBgAZUV5OAAZUzhkADMBjDgaiGsAKzgwGAB1SbZkEE5DOA4ANw3xyZm5+bYp02VkGA4AVz2IF28jQvwBQLgAA82Pc0MtYAMAPKwyYwCAcToQDBoerQa4IXDVEDQ1HwhAwAYAFXuUFaaEMWx2QJxUGUdgAiv8IPAmUZdjVDhgofNvpzubykNt+UCAI4SuCdNLXRQYMxOOD4Ik1P6KNCOZQAYQg8iUKqMRmJrPZcAAgjA-mhrP94J17msnHyBSAABYweRGM4+3GGT5gODzXq4tAPXHDa5gDBjEAPQGyKD4WDzMAcNBsGC2jPzGDDOxeoHhXYXRRXFC3XaPZ4gUwNmBKlRmqXMmqfDgN67WGxwS093OwM54GA+5AADgADDUOHB5Wgl+3lJ3pd7KdYJ7gp8gAEw1f67Kk2PpbyHyayarUrRRs-4qOAAMQxSgd3xVLogIF4vBAA

### CODE REVIEW

**Comment by leaysgur** [comment]
* **#16230** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16230?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#16224** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16224?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16224?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=16224).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_formatter/src/utils/conditional.rs [hunk 1]
```diff
@@ -344,9 +344,9 @@ impl<'a> FormatConditionalLike<'a, '_> {
 
     /// Checks if any part of the conditional has multiline comments
     #[inline]
-    fn has_multiline_comment(_f: &Formatter<'_, 'a>) -> bool {
-        // TODO: Implement multiline comment detection
-        false
+    fn has_multiline_comment(&self, f: &Formatter<'_, 'a>) -> bool {
+        let span = self.span();
+        f.comments().has_comment_in_range(span.start, span.end)
```
Comment (Dunqing) [inline crates/oxc_formatter/src/utils/conditional.rs]: It doesn't check any comments to see whether they have multiple lines. 

I don't understand the logic in [Biome](https://github.com/biomejs/biome/blob/ceed34a164cc76406baf617000b8877160f0bcc3/crates/biome_js_formatter/src/utils/conditional.rs#L197-L219), and no tests fail by this, so I didn't implement it. Can you double what it does? Is there any case that would be affected by this?

Comment (leaysgur) [reply crates/oxc_formatter/src/utils/conditional.rs]: Oh, I didn't notice that. Also, even after making the following change, our tests continue to pass...!

```diff
diff --git a/crates/oxc_formatter/src/utils/conditional.rs b/crates/oxc_formatter/src/utils/conditional.rs
index 2972536b6..c89425bf9 100644
--- a/crates/oxc_formatter/src/utils/conditional.rs
+++ b/crates/oxc_formatter/src/utils/conditional.rs
@@ -342,13 +342,6 @@ impl<'a> FormatConditionalLike<'a, '_> {
         }
     }

-    /// Checks if any part of the conditional has multiline comments
-    #[inline]
-    fn has_multiline_comment(&self, f: &Formatter<'_, 'a>) -> bool {
-        let span = self.span();
-        f.comments().has_comment_in_range(span.start, span.end)
-    }
-
     /// Returns `true` if this is the root conditional expression and the parent is a [`StaticMemberExpression`].
     #[inline]
     fn is_parent_static_member_expression(&self, layout: ConditionalLayout) -> bool {
@@ -502,7 +495,6 @@ impl<'a> Format<'a> for FormatConditionalLike<'a, '_> {
     fn fmt(&self, f: &mut Formatter<'_, 'a>) {
         let layout = self.layout(f);
         let should_extra_indent = self.should_extra_indent(layout);
-        let has_multiline_comment = self.has_multiline_comment(f);
         let is_jsx_chain = self.options.jsx_chain || layout.is_jsx_chain();

         let format_inner = format_with(|f| {
@@ -580,11 +572,8 @@ impl<'a> Format<'a> for FormatConditionalLike<'a, '_> {
         });

         if layout.is_nested_test() || should_extra_indent {
-            write!(f, [group(&soft_block_indent(&grouped)).should_expand(has_multiline_comment)]);
+            write!(f, [group(&soft_block_indent(&grouped))]);
         } else {
-            if has_multiline_comment {
-                write!(f, [expand_parent()]);
-            }
             grouped.fmt(f);
         }
     }
```

I will look into Biome's case further.

Comment (Dunqing) [reply crates/oxc_formatter/src/utils/conditional.rs]: Take a look at Prettier as well, maybe it is already dead code

Comment (leaysgur) [reply crates/oxc_formatter/src/utils/conditional.rs]: - Biome
  - The same logic still exists
    - https://github.com/biomejs/biome/blob/e7e0f6c14df92d83d08f86b1e57fc82b4df775b7/crates/biome_js_formatter/src/utils/conditional.rs#L197
  - In either case, the test did not fail
    - always returning `false`
    - removing related code like our diff above
- Prettier
  - The most relevant lines are here
    - https://github.com/prettier/prettier/blob/fd69335e513232c9b7aad78c93b42d8d3dd00ae7/src/language-js/print/ternary-old.js#L326-L344
  - As you expected, if change this to `const shouldBreak = false`, the test did not fail!

Now let's apply diff above?

Comment (Dunqing) [reply crates/oxc_formatter/src/utils/conditional.rs]: Remove them then! File an issue about this in Prettier if you'd like.

Comment (Dunqing) [reply crates/oxc_formatter/src/utils/conditional.rs]: Wait, this PR should focus on fixing the issue and cleaning it up in the follow-up PR, which makes more sense to me.

Comment (leaysgur) [reply crates/oxc_formatter/src/utils/conditional.rs]: OK, I'll:

- Revert some useless change here to focus fixing bug
- Remove `has_multiline_comment` and related lines
- Report to prettier

**Comment by leaysgur** [comment]
👉🏻 Minimized the diff.

**Review by Dunqing — APPROVED** [review]
