### PR TITLE
feat(linter): support suggestions and dangerous fixes

### LINKED ISSUE #4211: feat(linter): Support potentially dangerous fixes behind a `--fix-dangerously` flag
Some problems are potentially auto fixable, but doing so may be undesireable. In some cases, it could produce incorrect code. In other cases, it could change the behavior of applications.

ESLint handles this with [Rule Suggestions](https://eslint.org/docs/latest/use/core-concepts#rule-suggestions), which are made available to language servers but do not get applied via `--fix`.

Since the linter is mostly used as a CLI (oxlint), we need to support applying suggestions there too. I think we should do this with a `--fix-dangerously` flag.

- [ ] refactor(linter): update `FIx` to support suggestions
- [ ] feat(cli): add `--fix-dangerously` flag 
- [ ] feat(lsp): add command to apply suggestions

### PR DESCRIPTION
**Pull request by DonIsaac**

### CODE REVIEW

**Comment by DonIsaac** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4223?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4223** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4223?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#4222** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4222?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @DonIsaac and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_linter/src/fixer/fix.rs [hunk 1]
```diff
@@ -1,7 +1,133 @@
...
+
+// TODO: rename
+#[derive(Debug, Default)]
+#[must_use = "Fixes must be used. If you don't need a fix, use `LintContext::diagnostic`, or create an empty fix using `RuleFixer::noop`."]
+pub struct RuleFix<'a> {
+    kind: FixKind,
+    /// A suggestion message. Will be shown in editors via code actions.
+    ///
+    /// NOTE: code actions aren't implemented yet.
+    message: Option<Cow<'a, str>>,
```
Comment (DonIsaac) [inline crates/oxc_linter/src/fixer/fix.rs:31]: We need a better way of reconciling `fix.message` and `diagnostic.help`

File: apps/oxlint/src/command/lint.rs [hunk 2]
```diff
@@ -122,6 +122,31 @@ pub struct FixOptions {
     /// Fix as many issues as possible. Only unfixed issues are reported in the output
     #[bpaf(switch)]
     pub fix: bool,
+    /// Apply all safe fixes and more-risky suggestions. Overrides `--fix`.
+    #[bpaf(switch)]
+    pub fix_suggestions: bool,
```
Comment (mysteryven) [inline apps/oxlint/src/command/lint.rs:127]: In my personal view, when I use`fix_suggestions` without taking a look at documents, my intuition tells me it will fix only suggestions. It's convenient to apply multi kind fixes in one command, but people might want to apply suggestions alone.

Comment (DonIsaac) [reply apps/oxlint/src/command/lint.rs:127]: That makes sense; how about a fix level, kind of like -O3?

Comment (mysteryven) [reply apps/oxlint/src/command/lint.rs:127]: LGTM

**Comment by mysteryven** [comment]
I may delay the review for this PR, anyway I will take a close look tonight!

File: crates/oxc_linter/src/fixer/fix.rs [hunk 3]
```diff
@@ -57,16 +288,83 @@ impl<'a> From<Option<Fix<'a>>> for CompositeFix<'a> {
...
 
 impl<'a> CompositeFix<'a> {
+    pub fn push(&mut self, fix: CompositeFix<'a>) {
+        match self {
+            Self::None => *self = fix,
+            Self::Single(fix1) => {
+                *self = Self::Multiple(vec![fix1.clone(), fix.normalize_fixes("")]);
+            }
+            Self::Multiple(fixes) => fixes.push(fix.normalize_fixes("")),
+        }
```
[the remark this answers is not in the document]
Comment (DonIsaac) [reply crates/oxc_linter/src/fixer/fix.rs:321]: I made the change in the no-console branch...

[the remark this answers is not in the document]
Comment (DonIsaac) [reply crates/oxc_linter/src/fixer/fix.rs]: Re-fixed

**Review by mysteryven — APPROVED** [review]
It's a nice PR!
