### PR TITLE
fix(minifier): avoid incorrect logical assignment transformation when base object may be mutated

### LINKED ISSUE #16647: Oxc-minifier: Incorrect ||= optimization when variable is reassigned before property assignment
### Summary
The minifier incorrectly uses the ||= (logical OR assignment) operator when a variable is reassigned within the same conditional block before a property is set on it. This causes a runtime error in strict mode.

### Minimal Reproduction
**Working code before minification**
```
function loadImage(input) {
    let imageElement = input;
    
    if (!imageElement.src) {
        imageElement = new Image();
        imageElement.src = typeof input === 'string' ? input : URL.createObjectURL(input);
    }
    
    return imageElement;
}
const result = loadImage('https://picsum.photos/200/300');
console.log('Success! Image src:', result.src);
```
**Broken code after minification**
```
function e(e) {
	let t = e;
	return t.src ||= (t = new Image(), typeof e == "string" ? e : URL.createObjectURL(e)), t;
}
const t = e("https://picsum.photos/200/300");
console.log("Success! Image src:", t.src);
```
### The Problem
The ||= operator evaluates as:
`t.src = t.src || (t=new Image, typeof e=='string'?e:URL.createObjectURL(e))`
Execution order when `t` is a string `'https://example.com/image.jpg':`

1. Capture assignment target: t.src (at this point, t is the string)
2. Evaluate left side: t.src → undefined (accessing .src on string)
3. Since falsy, evaluate right side: (t=new Image, value) - t is reassigned to Image object. Comma operator returns the URL string
4. Execute assignment: Try to set string.src = "https://..."
5. In strict mode (ES modules): TypeError: Cannot create property 'src' on string
### Expected Behavior
The minifier should recognize that when:

1. A variable is reassigned inside the conditional expression
2. A property is then set on that variable

### PR DESCRIPTION
**Pull request by camc314**
Fixes #16647

Use `symbol_is_mutated()` to check if the member expression base object may be reassigned, preventing incorrect transformations like `x.y || (x = {}, x.y = 3)` to `x.y ||= (x = {}, 3)`.

🤖 generated with help from Claude Opus 4.5

### CODE REVIEW

**Comment by camc314** [comment]
* **#16802** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16802?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/16802?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=16802).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_minifier/src/peephole/minimize_conditions.rs [hunk 1]
```diff
@@ -1417,6 +1417,25 @@ mod test {
...
+        test("var x; x.y || (new Foo(), x.y = 3)", "var x; x.y ||= (new Foo(), 3)");
+        test("var x; x.y || (tag``, x.y = 3)", "var x; x.y ||= (tag``, 3)");
+        // `x` is mutated inside function `f`, so conservatively don't transform
+        // (even though `f` is not called in the expression)
+        test_same("var x; function f() { x = {} } x.y || (foo(), x.y = 3)");
+        test_same("var x; x.y.z || (x.y = {}, x.y.z = 3)");
+        test_same("var x; x.y.z || (x = {}, x.y.z = 3)");
+        test_same("var x; x.y.z.w || (x.y = {}, x.y.z.w = 3)");
+        // `x` is not mutated anywhere, and the preceding expression `x.y.z = {}` doesn't affect `x`
+        test("var x; x.y || (x.y.z = {}, x.y = 3)", "var x; x.y ||= (x.y.z = {}, 3)");
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/peephole/minimize_conditions.rs]:
```suggestion
        test_same("var x = {}; x.y || (x = {}, x.y = 3)");
        test_same("var x = { y: 1 }; x.y && (x = {}, x.y = 3)");
        test_same("var x = {}; x.y ?? (x = {}, x.y = 3)");
        test_same("var x = {}; x.y || (a, x = {}, x.y = 3)");
        test_same("var x = {}; x.y || (foo(x = {}), x.y = 3)");
        test_same("var x = { y: {} }; x.y.z || (x.y = {}, x.y.z = 3)");
        test("x || (a, x = 3)", "x ||= (a, 3)");
        test("var x = {}; x.y || (foo(), x.y = 3)", "var x; x.y ||= (foo(), 3)");
        test("var x = {}; x.y || (new Foo(), x.y = 3)", "var x; x.y ||= (new Foo(), 3)");
        test("var x = {}; x.y || (tag``, x.y = 3)", "var x; x.y ||= (tag``, 3)");
        // `x` is mutated inside function `f`, so conservatively don't transform
        // (even though `f` is not called in the expression)
        test_same("var x = {}; function f() { x = {} } x.y || (foo(), x.y = 3)");
        test_same("var x = {}; x.y.z || (x.y = {}, x.y.z = 3)");
        test_same("var x = {}; x.y.z || (x = {}, x.y.z = 3)");
        test_same("var x = {}; x.y.z.w || (x.y = {}, x.y.z.w = 3)");
        // `x` is not mutated anywhere, and the preceding expression `x.y.z = {}` doesn't affect `x`
        test("var x = {}; x.y || (x.y.z = {}, x.y = 3)", "var x = {}; x.y ||= (x.y.z = {}, 3)");
```
So that we can actually observe the behavior difference.
Also added a new test (`var x = { y: {} }; x.y.z || (x.y = {}, x.y.z = 3)`).

File: crates/oxc_minifier/src/peephole/minimize_logical_expression.rs [hunk 2]
```diff
@@ -230,6 +230,13 @@ impl<'a> PeepholeOptimizations {
                 return;
             }
 
+            // Don't transform `x.y || (x = {}, x.y = 3)` to `x.y ||= (x = {}, 3)` because
+            // `||=` evaluates `x.y` (capturing `x`) before the RHS reassigns `x`.
+            // https://github.com/oxc-project/oxc/issues/16647
+            if Self::member_object_may_be_mutated(&assignment_expr.left, ctx) {
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/peephole/minimize_logical_expression.rs:236]: It seems we also need to check this for https://github.com/oxc-project/oxc/blob/8651f13217e173cf0c4224ef0b4c952cd28ba3b5/crates/oxc_minifier/src/peephole/remove_unused_expression.rs#L125-L126
```js
var x = {}; x.y != null || (x = {}, x.y = 3) // x is `{ y: 3 }`
var x = {}; x.y ??= (x = {}, 3) // x is `{}`
```

File: crates/oxc_minifier/src/peephole/minimize_logical_expression.rs [hunk 3]
```diff
@@ -285,4 +292,39 @@ impl<'a> PeepholeOptimizations {
...
+            Expression::ThisExpression(_) => false,
+            Expression::StaticMemberExpression(member_expr) => {
+                Self::expression_reference_may_be_mutated(&member_expr.object, ctx)
+            }
+            Expression::ComputedMemberExpression(member_expr) => {
+                Self::expression_reference_may_be_mutated(&member_expr.object, ctx)
+            }
+            Expression::PrivateFieldExpression(member_expr) => {
+                Self::expression_reference_may_be_mutated(&member_expr.object, ctx)
+            }
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/peephole/minimize_logical_expression.rs]:
```suggestion
```
This part needs to be removed to pass the new case I suggested above.

File: crates/oxc_minifier/src/peephole/minimize_logical_expression.rs [hunk 4]
```diff
@@ -285,4 +292,39 @@ impl<'a> PeepholeOptimizations {
...
+            AssignmentTarget::ComputedMemberExpression(member_expr) => &member_expr.object,
+            AssignmentTarget::PrivateFieldExpression(member_expr) => &member_expr.object,
+            AssignmentTarget::StaticMemberExpression(member_expr) => &member_expr.object,
+            _ => return false,
+        };
+
+        Self::expression_reference_may_be_mutated(object, ctx)
+    }
+
+    fn expression_reference_may_be_mutated(expr: &Expression<'a>, ctx: &Ctx<'a, '_>) -> bool {
```
Comment (sapphi-red) [inline crates/oxc_minifier/src/peephole/minimize_logical_expression.rs]: Maybe we can share the function in https://github.com/oxc-project/oxc/pull/16165/files#diff-3c15b0ee5c1dc8cc41f18d5484d955961a811e4afe0d6c3d8d7eca019973411aR1397-R1414 ?

**Review by sapphi-red — CHANGES_REQUESTED** [review]

File: crates/oxc_minifier/src/peephole/minimize_logical_expression.rs (hunk 2 above)
Comment (camc314) [reply crates/oxc_minifier/src/peephole/minimize_logical_expression.rs:236]: i'll do this in a follow up PR :+1:

**Review by sapphi-red — APPROVED** [review]
Thanks!
