### PR TITLE
fix(semantic): missing reference when `export default` references a type alias binding

### LINKED ISSUE #7809: linter: `no-unused-vars` false positive for `TSTypeAliasDeclaration` with `ExportDefaultDeclaration`
### What version of Oxlint are you using?

0.15.0

### What command did you run?

oxlint

### What does your `.oxlint.json` config file look like?

````
{
  "plugins": ["unicorn", "typescript", "oxc"],
  "categories": {
    "correctness": "error",
    "suspicious": "warn"
  },
  "rules": {
    "no-unused-vars": "error"
  }
}

````

### Setup:

```typescript
/// types.ts:
type ABC = Record<string, unknown>;

export default ABC;

/// index.ts
import Types from './types.ts';

const xxx = (): ABC => ({}};
```

### Result

```
  × eslint(no-unused-vars): Type alias 'ABC' is declared but never used.
    ╭─[src/build-from-oxlint-config/types.ts:21:6]
 20 │ 
 21 │ type ABC = Record<string, unknown>;
    ·      ─┬─
    ·       ╰── 'ABC' is declared here
 22 │ 
    ╰────
  help: Consider removing this declaration.
```

### Expected

No Error

### PR DESCRIPTION
**Pull request by Dunqing**
Fixes: #7809

`ExportNamedDecalration` and `ExportDefaultDeclaration` can reference both type binding and value, so we need to make sure the `ReferenceFlags` is `Read | Type`

### CODE REVIEW

**Comment by Dunqing** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7813?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7813** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7813?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7813?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#7799** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/7799?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=7813).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: crates/oxc_semantic/src/builder.rs [hunk 1]
```diff
@@ -1845,6 +1845,13 @@ impl<'a> SemanticBuilder<'a> {
         /* cfg */
 
         match kind {
+            AstKind::ExportDefaultDeclaration(decl) => {
+                // `export default Ident`
+                //                 ^^^^^ -> Can reference both type binding and value
+                if matches!(decl.declaration, ExportDefaultDeclarationKind::Identifier(_)) {
+                    self.current_reference_flags = ReferenceFlags::Read | ReferenceFlags::Type;
```
Comment (Boshen) [inline crates/oxc_semantic/src/builder.rs:1852]: `| ReferenceFlags::Type` feels weird.

**Comment by Dunqing** [comment]
### Merge activity

* **Dec 12, 9:08 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Dec 12, 9:08 AM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).

**Comment by Dunqing** [comment]
Merging this and making a small refactor in follow-up PR
