### PR TITLE
fix(transformer/react): react refresh panics when encounter `use` hook

### LINKED ISSUE #5766: transformer: react refresh panics when transforming `typescript.js`
I happened to run into this. When transforming `typescript.js` (one of fixtures used for minifier) with all transform options enabled, it panics:

```
thread 'main' panicked at crates/oxc_transformer/src/react/refresh.rs:933:52:
called `Option::unwrap()` on a `None` value
```

### PR DESCRIPTION
**Pull request by Dunqing**
close: #5766

I even forgot that React has a `use` hook in the latest version

### CODE REVIEW

**Comment by Dunqing** [comment]
* **#5768** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5768?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_transformer/src/react/refresh.rs [hunk 1]
```diff
@@ -985,3 +986,13 @@ fn get_symbol_id_from_function_and_declarator(stmt: &Statement<'_>) -> Vec<Symbo
 
     symbol_ids
 }
+
+#[test]
+fn test_is_hook_name() {
```
Comment (Boshen) [inline crates/oxc_transformer/src/react/refresh.rs:991]: A integration test is preferred, add to an existing test case?

Comment (Dunqing) [reply crates/oxc_transformer/src/react/refresh.rs]: Done
