### PR TITLE
fix(lsp): panic when open file not under workspace root

### LINKED ISSUE #1868: bug: language server panics if a file is opened that's not in a sub directory
Title isn't great. But if you do the following:

1. launch vscode/oxc lsp at the root of a git repo
2. open a typescript file that is not under the root of the git repo.

It panics here: https://github.com/oxc-project/oxc/blob/de2f83477444ea19e5e370419ab4678652c87d30/crates/oxc_language_server/src/main.rs#L335

because the ts file is not under the root path of the matcher.

```rs
    /// # Panics
    ///
    /// This method panics if the given file path is not under the root path
    /// of this matcher.
```

Logs:
```
[2024-01-01T20:45:37Z DEBUG oxc_vscode] initialize: Options { run: OnType, enable: true }
[2024-01-01T20:45:37Z DEBUG oxc_vscode] oxc initialized.
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ignore-0.4.21/src/gitignore.rs:229:9:
path is expected to be under the root
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 20:45:37] The oxc server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Closed #1868

### CODE REVIEW

File: crates/oxc_language_server/src/main.rs [hunk 1]
```diff
@@ -328,10 +328,19 @@ impl Backend {
...
 
     async fn is_ignored(&self, uri: &Url) -> bool {
+        let Some(Some(root_uri)) = self.root_uri.get() else {
+            return false;
+        };
         let Some(ref gitignore_globs) = *self.gitignore_glob.lock().await else {
             return false;
         };
+
+        let root_path = PathBuf::from(root_uri.path());
```
Comment (Boshen) [inline crates/oxc_language_server/src/main.rs:338]: Why do we need to allocate for these things? Does it work with `Path::new`?

File: crates/oxc_language_server/src/main.rs [hunk 2]
```diff
@@ -328,10 +328,19 @@ impl Backend {
...
         let path = PathBuf::from(uri.path());
+        // The file is not under current workspace
+        if !path.starts_with(root_path) {
```
Comment (Boshen) [inline crates/oxc_language_server/src/main.rs:341]: If allocation is removed, does it make sense to move this check before the ignore check?
