### PR TITLE
fix(linter/no-unused-vars): Recognize parameters used in await/yield expressions within comma expressions

### LINKED ISSUE #10806: linter: `no-unused-vars` ignores the use of await usage before the comma operator
### What version of Oxlint are you using?

0.16.9

### What command did you run?

`oxlint -D=no-unused-vars`

### What does your `.oxlintrc.json` config file look like?

`oxlint` is run without config file.

### What happened?

[playgound](https://playground.oxc.rs/#eNqdj01rg0AQhv+K7ElBSu3HRdqcSq4N7dXLZh3Dwjojs2M+CP73jhrTQ6GkBcGdZfZ53vdsnCkNHDtiSZoenXjCpCnSBsskzZLXVbJhan2Elz35epUl5worYZCeMbHxhO6yltqD9crANMuTIqtwqPAH9+Ef3N+Jj7cRb2I9/T3ddF/Jd/d5vmwW46Qm/UxuyJRnwz2OP0WIPZpSuIfcBI+ynKOjDq7Dqd1SWCZhi7Ehbk3Z2BBhyE1nOQKPRBsCHT4m73sv0dewvhRbnncMuruHjWXAeFVQzw7WPgDaVsVGIMqdRKP0MddE1/NVPuvE8g40tIH4cF88az0fKViB+g1csGxHs0qWoI5q2MHUXUXbAJ+Tt7XdHERXWo++8YvPEQpTWGur8dEeeEtR883AYfgCDj7xYA==)
 
```typescript
export function f1(fn: () => Promise<void>) {
	return async () => (await fn(), 1)
}
```

```
! eslint(no-unused-vars): Parameter 'fn' is declared but never used. Unused
  | parameters should start with a '_'.
   ,-[:1:20]
 1 | export function f1(fn: () => Promise<void>) {
   :                    ^|
   :                     `-- 'fn' is declared here
 2 |     return async () => (await fn(), 1)
   `----
  help: Consider removing this parameter.
```

It seems that the rule ignores the use of await usage before the comma operator.

### PR DESCRIPTION
**Pull request by magic-akari**
- Closes: #10806

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/no_unused_vars/usage.rs [hunk 1]
```diff
@@ -610,6 +610,9 @@ impl<'a> Symbol<'_, 'a> {
                     if matches!(parent, AstKind::CallExpression(_)) {
                         continue;
                     }
+                    if matches!(parent, AstKind::AwaitExpression(_) | AstKind::YieldExpression(_)) {
+                        continue;
+                    }
```
Comment (Dunqing) [inline crates/oxc_linter/src/rules/eslint/no_unused_vars/usage.rs:615]:
```suggestion
                    if matches!(parent, AstKind::CallExpression(_) | AstKind::AwaitExpression(_) | AstKind::YieldExpression(_)) {
                        continue;
                    }
```

These two branches can be folded into one.

**Review by Dunqing — DISMISSED** [review]

**Review by camc314 — APPROVED** [review]

**Review by camchenry — APPROVED** [review]
