### PR TITLE
fix(linter): ignore invalid or partial disable directives

### LINKED ISSUE #6041: Typo'd disable comments disable linting for the entire file
`// oxlint-disable-lext-nine prefer-spread`
Since the `L` and `N` are swapped, rather than doing nothing, this comment is being partially matched as `// oxlint-disable` and disabling the entire file, which is not the intention. This should instead be ignored.

### PR DESCRIPTION
**Pull request by camchenry**
- closes https://github.com/oxc-project/oxc/issues/6041

We were not ignoring cases where the directive was invalid, now we do.

### CODE REVIEW

**Comment by camchenry** [comment]
* **#6045** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6045?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @camchenry and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: crates/oxc_linter/src/disable_directives.rs [hunk 1]
```diff
@@ -161,17 +159,23 @@ impl<'a> DisableDirectivesBuilder<'a> {
                             .push(DisableRuleComment { span: comment.span, rules });
                     }
                     continue;
+                } else if
+                // If the rule text starts with a dash, it's probably a typo of the correct syntax.
+                // Like `eslint-disable-lext-nine` where `text` is `-lext-nine`
+                !text.starts_with('-') &&
+                    // We should match only `eslint-disable` comments, not `eslint-disablefoo`
+                    text.starts_with(' ')
```
Comment (DonIsaac) [inline crates/oxc_linter/src/disable_directives.rs:167]: This condition is logically identical to `text.starts_with(' ')`. You should be able to remove the `!text.starts_with('-')` part.

**Review by DonIsaac — APPROVED** [review]
