### PR TITLE
fix(regular_expression): Report more MayContainStrings error in (nested)class

### LINKED ISSUE #5632: regular_expression: Uncaught `MayContainStrings` in `/[^[\q{abc}]]/v`
Should be reported as error, but it's not.

image

Ultimaterly, `[^[[[[[[[[\q{abc}]]]]]]]]]` should be reported too.

### PR DESCRIPTION
**Pull request by leaysgur**
Fixes #5632

### CODE REVIEW

File: crates/oxc_regular_expression/src/ast.rs [hunk 1]
```diff
@@ -238,6 +238,7 @@ pub struct CharacterClass<'a> {
     pub span: Span,
     pub negative: bool,
     pub kind: CharacterClassContentsKind,
+    pub strings: bool,
```
Comment (Boshen) [inline crates/oxc_regular_expression/src/ast.rs:241]: We probably need some documentation around these fields, I don't know what they mean 😢

Comment (leaysgur) [reply crates/oxc_regular_expression/src/ast.rs:241]: OK, I'll review the AST documentation in another PR. 🏃🏻
