### PR TITLE
fix(linter/plugins): fall back to package name if meta.name is missing

### LINKED ISSUE #14937: linter: JS Plugins don't work if the package is missing meta.name
### What version of Oxlint are you using?

1.24.0

### What command did you run?

_No response_

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "jsPlugins": ["eslint-plugin-freeze-global"]
}
```

### What happened?

```
Failed to parse configuration file.

  × Failed to load JS plugin: eslint-plugin-freeze-global
  │   TypeError: Cannot read properties of undefined (reading 'name')
  │     at loadPluginImpl (file:///[MY REPO]/node_modules/.pnpm/oxlint@1.24.0/node_modules/oxlint/dist/plugins.js:820:31)
  │     at async loadPlugin (file:///[MY REPO]/node_modules/.pnpm/oxlint@1.24.0/node_modules/oxlint/dist/plugins.js:810:13)
```

### PR DESCRIPTION
**Pull request by wagenet**
Fixes #14937

### CODE REVIEW

**Review by Sysix — APPROVED** [review]
Used your PR to test a tool :) Worked like a charm!
Many plugins do not have the meta property 👍

File: apps/oxlint/src-js/plugins/load.ts [hunk 1]
```diff
@@ -110,7 +112,13 @@ async function loadPluginImpl(path: string): Promise<PluginDetails> {
...
 
   // TODO: Use a validation library to assert the shape of the plugin, and of rules
-  const pluginName = plugin.meta.name;
+  // Get plugin name from plugin.meta.name, or fall back to package name from package.json
+  const pluginName = plugin.meta?.name ?? packageName;
+  if (!pluginName) {
+    throw new TypeError(
+      'Plugin must have either meta.name or be loaded from an npm package with a name field in package.json',
+    );
+  }
```
Comment (camc314) [inline apps/oxlint/src-js/plugins/load.ts:121]: 😞 this is technically different behaviour rom eslint.
eslint appears to just completely ignore `plugin.meta.name`

**Review by camc314 — APPROVED** [review]
Thank you!
