### PR TITLE
fix(transformer/typescript): remove type-only `import =` when `only_remove_type_imports` is true

### LINKED ISSUE #3287: [Bug]: Typesript import aliases are treated like actual imports
### Reproduction link or steps

https://stackblitz.com/edit/github-zdltp46a?file=src%2Fentry.ts

```
import 'electron';
import HandlerDetails = Electron.HandlerDetails;
```

### What is expected?

there's no generated import for alias import (`HandlerDetails`)

### What is actually happening?

```
var import_electron = __toESM(require_electron(), 1);
var HandlerDetails = Electron.HandlerDetails;
```

### System Info

```Shell
stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: latest => 1.0.0-beta.1
```

### Any additional comments?

We cannot write `import type HandlerDetails = Electron.HandlerDetails` because we run into  error TS1392: An import alias cannot use 'import type'.

We can write `import type { HandlerDetails } from "electron"` in this particular case but it requires code changes for something that's unambiguously a namespace alias.

### LINKED ISSUE #8230: The TSImportEqualsDeclaration is typing is not remove.
### Input 
``` .js
import { X } from "abc";
// assume Y is a type only namespace
import Z = X.Y.Z;

function a(t: Z.T) {
  console.log(t);
}
```

### Output
``` .js
import { X } from "abc";
var Z = X.Y.Z;
function a(t) {
	console.log(t);
}
```

### Expected
The `Z` is a typing, it should be removed.
``` .js
function a(t) {
  console.log(t);
}
```

The bable also have a issue https://github.com/babel/babel/issues/15942, and also have a pr to resolve it https://github.com/babel/babel/pull/17025.

related https://github.com/rolldown/rolldown/issues/3287

### PR DESCRIPTION
**Pull request by Dunqing**
close: https://github.com/oxc-project/oxc/issues/8230
close: https://github.com/rolldown/rolldown/issues/3287

Related PR in Babel: https://github.com/oxc-project/oxc/issues/8230

I have compared our output with TypeScript, and it is the same as `TypeScript`, Babel's implementation currently hasn't removed imports referenced by type-only `TSImportEqualsDeclaration`

### CODE REVIEW

File: crates/oxc_transformer/src/typescript/module.rs [hunk 1]
```diff
@@ -7,12 +8,13 @@ use super::diagnostics;
 use crate::TransformCtx;
 
 pub struct TypeScriptModule<'a, 'ctx> {
+    only_remove_type_imports: bool,
```
Comment (Boshen) [inline crates/oxc_transformer/src/typescript/module.rs:11]: can you reference https://babeljs.io/docs/babel-preset-typescript#onlyremovetypeimports

File: tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+import nsa from "./module-a";
+var Foo = nsa.bar;
```
Comment (underfin) [inline tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js:2]: The `Foo` is not removed, it is a typing.

**Comment by underfin** [comment]
The type-only `TSImportEqualsDeclaration` always should be removed, look like it is unrelated with `only_remove_type_imports`.

File: tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js (hunk 2 above)
Comment (Dunqing) [reply tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js:2]: `only_remove_type_imports` is enabled, so it only removes type-only imports. This option is the same as [verbatimModuleSyntax] (https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax) in `TypeScript`.

Comment (Dunqing) [reply tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js:2]: See https://www.typescriptlang.org/play/?noLib=true&skipLibCheck=true&target=99&jsx=1&verbatimModuleSyntax=true#code/JYWwDg9gTgLgBAOwM4EM4DMoRHARAOgHoQIATAVwBsBTAWhVwG4AoUSWOAMQgjgF5EqfACMUUFswDGEZPHQ8AXFx784ABkZA

Comment (underfin) [reply tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js:2]: Ok. I get you. It shoulde be remove if `only_remove_type_imports` is enabled ,right?

Comment (Dunqing) [reply tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures/preserve-import-=/output.js:2]: Yes!

**Comment by Boshen** [comment]
@Dunqing feel free to merge.

**Comment by Boshen** [comment]
### Merge activity

* **Jan 11, 3:31 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
