### PR TITLE
fix(linter): respect category settings in overrides

### LINKED ISSUE #19409: linter: no-unused-vars rule is enabled despite correctness set to off
### What version of Oxlint are you using?

1.47.0

### What command did you run?

`oxlint`

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "$schema": "./node_modules/oxlint/configuration_schema.json",
  "plugins": ["react", "typescript"],
  "categories": {
    "correctness": "off"
  },
  "rules": {
    "react/no-multi-comp": "error",
    "@typescript-eslint/no-inferrable-types": "error"
  },
  "overrides": [
    {
      "files": [
        "subdir/**/*.ts",
        "subdir/**/*.tsx"
      ],
      "plugins": ["node"],
      "rules": {
        "node/global-require": "error"
      },
    }
  ]
}
```

### What happened?

Reproduction repo: https://github.com/connorshea/test-migrate

Reproduction instructions:

- `git clone https://github.com/connorshea/test-migrate`
- `cd test-migrate`
- `pnpm install`
- `pnpm oxlint`, see that it returns a warning for no-unused-vars despite that rule not being enabled.

The `foo.tsx` file is this:

```tsx
// This file will trigger the no-multi-comp rule, that's fine.
const ComponentOne = () => <div>A</div>;
const ComponentTwo = () => <div>B</div>;

// This next line triggers typescript/no-inferrable-type, that's fine.
// However, it also triggers typescript/no-unused-vars, despite that rule not being enabled in any way?
const a: number = 5;

export { ComponentOne, ComponentTwo };
```

Output of oxlint:

```
test-migrate % pnpm oxlint

  × eslint-plugin-react(no-multi-comp): Declare only one React component per file. Found: ComponentTwo
   ╭─[subdir/foo.tsx:3:7]
 2 │ const ComponentOne = () => <div>A</div>;
 3 │ const ComponentTwo = () => <div>B</div>;
   ·       ─────────────────────────────────
 4 │ 
   ╰────
  help: Move this component to a separate file.

  ⚠ eslint(no-unused-vars): Variable 'a' is declared but never used. Unused variables should start with a '_'.
   ╭─[subdir/foo.tsx:7:7]
 6 │ // It also triggers typescript/no-unused-vars, despite that rule not being enabled in any way?
 7 │ const a: number = 5;
   ·       ┬
   ·       ╰── 'a' is declared here
 8 │ 
   ╰────
  help: Consider removing this declaration.

  × typescript-eslint(no-inferrable-types): Type can be trivially inferred from the initializer
   ╭─[subdir/foo.tsx:7:8]
 6 │ // It also triggers typescript/no-unused-vars, despite that rule not being enabled in any way?
 7 │ const a: number = 5;
   ·        ────────
 8 │ 
   ╰────
  help: Remove the type annotation

Found 1 warning and 2 errors.
Finished in 5ms on 1 file with 2 rules using 8 threads.
```

This is a bizarre behavior and it should not be happening. `correctness` is set to "off", and the rule is not enabled explicitly in the config. So why does it still get triggered by this code?

I also tested this on 1.43.0 and it happens there too (before that, react/no-multi-comp doesn't exist so we'll maybe want to adjust the config to go back further, if we think this is a recent regression).

A similar problem occurs if I change the `foo.tsx` file:

```tsx
// This file will trigger the no-multi-comp rule.
const ComponentOne = () => <div>A</div>;
const ComponentTwo = () => <div>B</div>;

const a: number = 5;

export { ComponentOne, ComponentTwo };

// Now this has a warning that it should not have:
if (a === {}) {
  console.log("foo");
}
```

Resulting warning from oxlint:

```
  ⚠ eslint(no-constant-binary-expression): Unexpected comparison to newly constructed object
    ╭─[subdir/foo.tsx:11:5]
 10 │ 
 11 │ if (a === {}) {
    ·     ────────
 12 │   console.log("foo");
    ╰────
  help: These two values can never be equal

Found 1 warning and 2 errors.
Finished in 26ms on 1 file with 2 rules using 8 threads.
```

### PR DESCRIPTION
**Pull request by connorshea**
Fix #19409.

In certain cases where there was an override in the Oxlint config and the override enabled specific non-default plugins, Oxlint would re-enable the default correctness rules for the files in that override.

For an example of the problematic behavior here, this is my oxlint config:

```json
{
  "plugins": ["react"],
  "categories": {
    // Disable correctness rules.
    "correctness": "off"
  },
  "rules": {
    "react/no-multi-comp": "error",
  },
  "overrides": [
    {
      "files": ["subdir/**/*.tsx"],
      "plugins": ["node"], // enable at least one non-default plugin in this override
      "rules": {
        "node/global-require": "error"
      },
    }
  ]
}
```

If I have a file at `subdir/Foo.tsx`, which matches the glob pattern from the override, with this content, it triggers the `no-unused-vars` rule as a warn-level violation:

```tsx
// This file will trigger the `react/no-multi-comp` rule and that's fine and good.
const ComponentOne = () => <div>A</div>;
const ComponentTwo = () => <div>B</div>;

// This should *not* be a violation, as all default rules are disabled.
// BUT due to a bug, it triggers `no-unused-vars` - which is a
// default rule - despite the fact that that rule *should*
// be disabled globally:
const a: number = 5;
```

It _should not do that_, for two reasons:

1) categories cannot be enabled/disabled in the override and so there's no way to fix it/work around it
2) this only happens if the plugins array has an explicit value *and* that value includes one of the non-default plugins. If I were to either leave the plugins array for the override unset, or set the plugins array for the override to `"plugins": ["eslint"]`, the bug does not occur and `no-unused-vars` does not get re-activated. This problem is _only_ manifested when the `plugins` array is set to something that includes at least one non-default plugin, e.g. `"plugins": ["react"]` or `"plugins": ["eslint", "promise"]`.

This PR fixes that bug to ensure this no longer occurs.

### CODE REVIEW

File: crates/oxc_linter/src/config/config_builder.rs [hunk 1]
```diff
@@ -254,7 +254,7 @@ impl ConfigStoreBuilder {
         let mut categories = oxlintrc.categories.clone();
 
         if !start_empty {
-            categories.insert(RuleCategory::Correctness, AllowWarnDeny::Warn);
+            categories.entry(RuleCategory::Correctness).or_insert(AllowWarnDeny::Warn);
```
Comment (connorshea) [inline crates/oxc_linter/src/config/config_builder.rs:258]: Per the docs for `insert`:

> Inserts a key-value pair into the map.
> 
> If the map did not have this key present, None is returned.
> 
> If the map did have this key present, the value is updated, and the old value is returned.

So now we only insert if it doesn't exist in the first place.

File: apps/oxlint/src/lint.rs [hunk 2]
```diff
@@ -1163,6 +1163,22 @@ mod test {
         Tester::new().with_cwd("fixtures/issue_10394".into()).test_and_snapshot(args);
     }
 
+    // https://github.com/oxc-project/oxc/issues/19409
+    #[test]
+    fn test_overrides_correctness_off_not_reenabled_by_plugin() {
+        let args = &["-c", ".oxlintrc.json"];
+        Tester::new().with_cwd("fixtures/overrides_correctness_off".into()).test_and_snapshot(args);
```
Comment (Afsoon) [inline apps/oxlint/src/lint.rs]: I'm being nitpicking, you can omit it, but I prefer folder name have the prefix `issue_19409`. This way, we don't need to see the test comment to know the test case fix a bug reported.

File: apps/oxlint/src/lint.rs [hunk 3]
```diff
@@ -1163,6 +1163,22 @@ mod test {
...
+    }
+
+    // https://github.com/oxc-project/oxc/issues/19409
+    #[test]
+    fn test_overrides_correctness_off_no_constant_binary_expression() {
+        let args = &["-c", ".oxlintrc.json"];
+        Tester::new()
+            .with_cwd("fixtures/overrides_correctness_off_constant_binary".into())
```
Comment (Afsoon) [inline apps/oxlint/src/lint.rs]: I'm being nitpicking, you can omit it, but I prefer folder name have the prefix `issue_19409`. This way, we don't need to see the test comment to know the test case fix a bug reported.

File: apps/oxlint/src/lint.rs (hunk 2 above)
Comment (connorshea) [reply apps/oxlint/src/lint.rs]: Fair enough, updated.

**Comment by connorshea** [comment]
@camc314 bumping this PR since I think it's important to fix :)

**Comment by connorshea** [comment]
@camc314 I think this PR might be fixed by the vitest fix in https://github.com/oxc-project/oxc/commit/44b5b35b66decc6f90a64bce322567db966bb5c3? Not totally sure if it fixes the same problem

**Review by camc314 — APPROVED** [review]
💪 thanks - sorry for the delay in getting to it.
