### PR TITLE
fix(napi/minify): handle boolean values for `compress.unused` option

### LINKED ISSUE #14512: napi/minifier: `compress.unused` option cannot be set correctly from napi binding
## Description

The `compress.unused` option implemented in PR #11796 cannot accept boolean values from the napi,
making it impossible to properly control unused variable removal behavior.

## Current Behavior

- TypeScript definition declares `unused?: true | false | 'keep_assign'`
- Rust implementation uses `Option<String>`, which cannot handle boolean values correctly
- Setting `unused: true` or `unused: false` doesn't work as expected and causes panic

## Expected Behavior

The option should accept three types of values:

- `unused: true` → Remove unused variables (`CompressOptionsUnused::Remove`)
- `unused: false` → Keep unused variables (`CompressOptionsUnused::Keep`)
- `unused: 'keep_assign'` → Keep variables with assignments (`CompressOptionsUnused::KeepAssign`)

## Related

- PR #11796 - feat(minifier): remove unused variable declaration

### PR DESCRIPTION
**Pull request by sushichan044**
fixes https://github.com/oxc-project/oxc/issues/14512

Fixes the `compress.unused` option implemented in PR #11796 to properly accept boolean values from the napi binding.

### CODE REVIEW

File: napi/minify/src/options.rs [hunk 1]
```diff
@@ -55,8 +56,14 @@ impl TryFrom<&CompressOptions> for oxc_minifier::CompressOptions {
...
             sequences: true,
-            // TODO
-            unused: oxc_minifier::CompressOptionsUnused::Keep,
+            unused: match &o.unused {
+                Some(Either::A(true)) => oxc_minifier::CompressOptionsUnused::Remove,
+                Some(Either::A(false)) => oxc_minifier::CompressOptionsUnused::Keep,
+                Some(Either::B(s)) if s == "keep_assign" => {
+                    oxc_minifier::CompressOptionsUnused::KeepAssign
+                }
+                None | Some(Either::B(_)) => default.unused,
```
Comment (sapphi-red) [inline napi/minify/src/options.rs]: Would you return an error if a string other than `keep_assign` is specified like this line in rolldown?
https://github.com/rolldown/rolldown/blob/c746e1128d98c6847056d35425986fe31293e12d/crates/rolldown_binding/src/options/plugin/types/binding_resolved_external.rs#L18-L21

Comment (sushichan044) [reply napi/minify/src/options.rs]: @sapphi-red 
Thank you for the comment. I fixed: df5926cc88aee7c8b9f351587837db0c49722578
I’m new to Rust, so please feel free to point out any mistakes or suggest better ways to do things.

**Comment by sushichan044** [comment]
https://github.com/oxc-project/oxc/compare/c93aa2fe1a5b16dcbb014f5a4b1e8796941aba7e..df5926cc88aee7c8b9f351587837db0c49722578: rebased with https://github.com/oxc-project/oxc/pull/14545

**Review by sapphi-red — APPROVED** [review]
Thank you!
