### PR TITLE
fix(linter): false positive in `unicorn/catch-error-name`

### LINKED ISSUE #9723: linter: unicorn/catch-error-name auto-fix does not rename references to old name
### What version of Oxlint are you using?

0.15.14

### What command did you run?

`oxlint -D unicorn/catch-error-name file.ts`

### What does your `.oxlintrc.json` config file look like?

Not relevant. Just the one rule is enough to reproduce.

### What happened?

The auto-fix for the `unicorn/catch-error-name` rule does not rename references to the old variable name.

```ts
try {
	throw new Error();
} catch (err) {
	console.error('An error occurred!', err);
}
```

Is auto-fixed to:
```ts
try {
	throw new Error();
} catch (error) {
	console.error('An error occurred!', err); // <--- This was not renamed
}
```

In constract, the `eslint-plugin-unicorn` plugin correctly renames the reference in my example.

### PR DESCRIPTION
**Pull request by shulaoda**
closes #9723

### CODE REVIEW

File: crates/oxc_linter/src/rules/unicorn/catch_error_name.rs [hunk 1]
```diff
@@ -241,7 +213,25 @@ impl CatchErrorName {
...
                     binding_ident.span,
                 ),
-                |fixer| fixer.replace(binding_ident.span, self.name.clone()),
+                |fixer| {
+                    if iter.peek().is_none() {
+                        return fixer.replace(binding_ident.span, self.name.clone());
+                    }
+
+                    let fixer = fixer.for_multifix();
+                    let mut declaration_fix = fixer.new_fix_with_capacity(2);
```
Comment (camc314) [inline crates/oxc_linter/src/rules/unicorn/catch_error_name.rs:222]: should `2` be the len of iter instead?

Comment (shulaoda) [reply crates/oxc_linter/src/rules/unicorn/catch_error_name.rs:222]: Yeah!  My negligence!

**Review by camc314 — APPROVED** [review]
:mu

**Comment by camc314** [comment]
### Merge activity

* **Mar 13, 4:50 PM EDT**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
