### PR TITLE
fix(linter): update prefer-destructuring rule metadata

### LINKED ISSUE #17641: `prefer-destructuring` auto-fix not appearing in VS Code despite being implemented

### PR DESCRIPTION
**Pull request by hirehamir**
Fixes #17641

### CODE REVIEW

File: crates/oxc_linter/src/rules/eslint/prefer_destructuring.rs [hunk 1]
```diff
@@ -86,7 +86,7 @@ declare_oxc_lint!(
     PreferDestructuring,
     eslint,
     style,
-    fix,
+    conditional_fix,
```
Comment (camc314) [inline crates/oxc_linter/src/rules/eslint/prefer_destructuring.rs:89]: how does changing the fix kind fix the issue?

(i'm not saying we shouldn't change this to `conditional_fix`, just that i don't understand why changing it fixes the issue.

Comment (hirehamir) [reply crates/oxc_linter/src/rules/eslint/prefer_destructuring.rs:89]: Ah, that was the original goal. I'll update the commit message and pull request title now.

Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/prefer_destructuring.rs:89]: can you explain in the description how changing the metadata fixes this issue.
