### PR TITLE
fix(linter): improve rule docs page autofix description

### LINKED ISSUE #663: Auto-fix text can sometimes be inaccurate
> I think this phrasing could/should probably be improved, the currently phrasing implies active development on a lint rule. But really, it just means the fix is marked `pending`.
> 
> And all `pending` means is that:
> 
> - the developer that wrote the rule didn't add a fix when initially contributing the rule
> - the developer that wrote the rule believed - and any code reviewers that reviewed the PR did not disagree - that an autofix could reasonably be written and is possible.
> 
> So the phrasing should probably be updated to something like "an autofixer is planned", 

 _Originally posted by @connorshea in [#467](https://github.com/oxc-project/oxc-project.github.io/issues/467#issuecomment-3537272909)_

### PR DESCRIPTION
**Pull request by hirehamir**
Fixes https://github.com/oxc-project/oxc-project.github.io/issues/663

### CODE REVIEW

File: crates/oxc_linter/src/rule.rs [hunk 1]
```diff
@@ -339,7 +339,7 @@ impl RuleFixMeta {
     pub fn description(self) -> Cow<'static, str> {
         match self {
             Self::None => Cow::Borrowed("No auto-fix is available for this rule."),
-            Self::FixPending => Cow::Borrowed("An auto-fix is still under development."),
```
Comment (hirehamir) [inline crates/oxc_linter/src/rule.rs:342]: This isn't actually true all the time.

Comment (camc314) [reply crates/oxc_linter/src/rule.rs:342]: the updated text still doesn't really sound right to me?

I think it should be something like "An auto-fix is planned for this rule, but not implemented at this time"

**Review by camc314 — APPROVED** [review]
Thank you!

**Comment by hirehamir** [comment]
You're welcome!
