### PR TITLE
fix(editor): execute `oxc.path.server` in win32 with shell

### LINKED ISSUE #14167: VSCode: allow `oxc.path.server` to be used in Linux & Windows
> I see https://github.com/oxc-project/oxc/pull/13542 was merged an hour ago. This only covers the case with the relative path, correct? I could not share `oxc.path.server` as a project wide setting in my `.vscode/settings.json`, if I have a mix of Windows and non-Windows developers as I sometimes would have to use `.exe` and sometimes not. (Referring to [this comment](https://github.com/oxc-project/oxc/issues/12849#issuecomment-3160832991).) 

 _Originally posted by @donaldpipowitch in [#12849](https://github.com/oxc-project/oxc/issues/12849#issuecomment-3278213562)_

Created an own issue for it, because it is more work than expected.
There is no `.exe`, only `.CMD` and `.ps1` (in NPM/PNPM). 
Bun has  `.exe` file in `node_modules/.bin`. 

There could be 2 solutions:

Enable `shell` option, so VSCode can use `node_modules/.bin/language_server` too.
This will enable a security hole (https://github.com/oxc-project/oxc/pull/13732#discussion_r2345327975), which should be covered by https://github.com/oxc-project/oxc/pull/13740 and https://github.com/oxc-project/oxc/pull/13734.
I would like to force somehow more checks before enabling this.

Search for `.exe` inside `node_modules`.
This could be a bit difficult because the package manager could but the file somewhere else than expected.
The other editors could have solved this already. But we should check if this works with different package managers as expected.

### PR DESCRIPTION
**Pull request by Sysix**
closes #14167
This allows cross-platform configuration in a project.
The project can now define `oxc.path.server` to `node_modules/.bin/oxc_language_server` and windows will pick it up too.

 With `validateSafeBinaryPath` in `Pathvalidator.ts`, we should be sure that bad actors can not harm the user's machine.

This is needed because the VSCode extension will not ship the language server in the future.

### CODE REVIEW

**Comment by Sysix** [comment]
* **#14203** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/14203?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/oxc-project/oxc/14203?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#15680** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15680?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15611** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15611?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15610** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15610?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15609** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15609?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15563** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15563?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#15608](https://github.com/oxc-project/oxc/pull/15608) <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15608?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#15505** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15505?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#15568** <a href="https://app.graphite.com/github/pr/oxc-project/oxc/15568?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=14203).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: editors/vscode/client/extension.ts [hunk 1]
```diff
@@ -155,10 +154,20 @@ export async function activate(context: ExtensionContext) {
     );
   }
 
-  const command = await findBinary();
+  const userDefinedBinary = configService.getUserServerBinPath();
+  const command = await findBinary(userDefinedBinary);
   const run: Executable = {
     command: command!,
     options: {
+      // On Windows we need to run the binary in a shell to be able to execute the shell npm bin script.
```
Comment (nrayburn-tech) [inline editors/vscode/client/extension.ts]: Is this because windows can’t execute this script directly? I think there’s another alternative to spawn a cmd prompt with the argument to execute the script, then you don’t need shell: true.

Not sure if it matters or if there’s any reason to prefer one or the other.

File: editors/vscode/client/extension.ts [hunk 2]
```diff
@@ -155,10 +154,20 @@ export async function activate(context: ExtensionContext) {
...
+      // This is only needed when the user explicitly configures the binary to point to the npm bin script.
+      // The extension is shipped with the `.exe` file, we don't need to run it in a shell.
+      // Searching for the right `.exe` file inside `node_modules/` is not reliable as it depends on
+      // the package manager used (npm, yarn, pnpm, etc) and the package version.
+      // The npm bin script is a shell script that points to the actual binary.
+      // Security: We validated the userDefinedBinary in `configService.getUserServerBinPath()`.
+      shell: process.platform === 'win32' && command === userDefinedBinary &&
+        userDefinedBinary?.endsWith('node_modules\\.bin\\oxc_language_server'),
```
Comment (nrayburn-tech) [inline editors/vscode/client/extension.ts]: I don’t personally think this (or the other path validations) are necessary.

If the user has opted into the trusted workspace, they have consented to these settings. I don’t think the extension is responsible for validating what the path might look like or what the contents of the evaluated file might be.

It has potential to make it harder for users to use, for what I would consider little to no real security benefit.

File: editors/vscode/client/extension.ts (hunk 1 above)
Comment (Sysix) [reply editors/vscode/client/extension.ts]: Yes, it does not handle the sh shebang in the file. Calling the CMD file or ps1 file inside `node_modules/.bin/` will not work. This is the only solution or searching for the `.exe` file.
But searching for the `.exe` file will create more problems with the location of the .exe. 
Your examples in the issue did not check for different package versions. Calling the wrapper script in `node_modules/.bin/` "should" be the right way.

File: editors/vscode/client/extension.ts (hunk 2 above)
Comment (Sysix) [reply editors/vscode/client/extension.ts]: A user would trust the extension more than a freshly opened workspace. Even when a user has trusted a workspace by accident (when the workspace is inside a parent folder, which is already been trusted). Opening the extension to execute untrusted binaries / shell script should still be validated.
Maybe not all restrictions are needed and can frustrate users to set up the `oxc.path.server` correctly.
But I will take the cost for better end-user security.

Comment (nrayburn-tech) [reply editors/vscode/client/extension.ts]: I think what you’re trying to solve is possibly a gap in the trusted workspace feature. Instead of trusting an entire workspace, you want users to trust specific values within the workspace. It doesn’t feel like the responsibility of the extension.

I think the definition of setting the oxc.path.server “correctly” is subjective. If I want to use whatever characters in my path, that shouldn’t be prevented by the extension.

I understand the desire for security though. I don’t think this is a blocker by any means, just wanted to bring it up as something to consider.

**Comment by nrayburn-tech** [comment]
I won’t be able to actually review any code for a few days, but I don’t think I’ll have much to share other than the few considerations I mentioned before.

Just things for the team to consider.

For what it’s worth, the IntelliJ plugin doesn’t do any path validation and it’s not something I would personally add. The IntelliJ plugin also uses some abstraction provided by IntelliJ, but I believe by default it executes the same file that is being suggested for this PR. However, if a user specifies an exe path directly, that still works too. Specifying an exe path directly just won’t work cross platform (in typical scenarios).

---

I think I mentioned this a while ago when the IDE development was only beginning. It might be beneficial to have documentation on how we want the different IDE plugins owned by the Oxc team to function. This would provide users with a consistent experience across the different IDEs. Currently, users likely have a slightly different experience between the various IDEs (VS Code, IntelliJ, Zed, etc.)

**Comment by Sysix** [comment]
moving it back to a draft.
Reason: maybe with the node integration for js-plugins, this is not needed anymore.
Idea from: https://github.com/oxc-project/oxc-intellij-plugin/issues/239#issuecomment-3393576927

EDIT: there is still a need after testing it with windows

**Review by camc314 — APPROVED** [review]

**Comment by camc314** [comment]
### Merge activity

* **Nov 14, 1:18 PM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Nov 14, 1:18 PM UTC**: `camc314` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Nov 14, 1:22 PM UTC**: The [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) removed this pull request due to **downstack failures on PR #[15680](https://app.graphite.com/github/pr/oxc-project/oxc/15680)**.
* **Nov 14, 1:22 PM UTC**: The [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) removed this pull request due to **downstack failures on PR #[15680](https://app.graphite.com/github/pr/oxc-project/oxc/15680)**.
* **Nov 14, 1:32 PM UTC**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Nov 14, 1:36 PM UTC**: `Sysix` added this pull request to the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
* **Nov 14, 1:41 PM UTC**: Merged by the [Graphite merge queue](https://app.graphite.com/merges?org=oxc-project&repo=oxc).
