### PR TITLE
fix(tasks/lint_rules): refactor to mjs to support ESM dependencies

### LINKED ISSUE #9214: ci ` Update implementation status of all linter plugins` fails
https://github.com/oxc-project/oxc/actions/runs/13397479664/job/37420023510
https://github.com/oxc-project/oxc/actions/runs/13397267270/job/37419334533

### PR DESCRIPTION
**Pull request by Sysix**
closes #9214

### CODE REVIEW

**Comment by Sysix** [comment]
* **#9246** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9246?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/9246?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add either label to this PR to merge it via the merge queue:
- <kbd>0-merge</kbd> - adds this PR to the back of the merge queue
- <kbd>hotfix</kbd> - for urgent hot fixes, skip the queue and merge this PR next

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.dev/invite/github/oxc-project?ref=merge-queue-instructions-in-stack-comment&prId=9246).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: tasks/lint_rules/src/eslint-rules.mjs [hunk 1]
```diff
@@ -10,62 +10,76 @@ const { Linter } = require('eslint');
...
-} = require('eslint-plugin-promise');
-// https://github.com/veritem/eslint-plugin-vitest/blob/v1.1.9/src/index.ts
+} = pluginReactPerf;
+
 const {
-  rules: pluginVitestRules,
   configs: pluginVitestConfigs,
-} = require('eslint-plugin-vitest');
+  rules: pluginVitestRules,
+} = pluginVitest;
```
Comment (leaysgur) [inline tasks/lint_rules/src/eslint-rules.mjs:82]: Because some of them only use a default export, it's not possible to standardize the way of writing? 👀 

It would be nice to have a comment for that at the beginning, and I think it's fine to remove extra blank lines between them.

**Review by leaysgur — COMMENTED** [review]
There's also a section about `cjs` in the `README.md`, it should be updated as well.

Thank you for working on this!

**Review by leaysgur — APPROVED** [review]
🚀

**Comment by Sysix** [comment]
merging because it can not be more broken then the current state.

**Comment by Sysix** [comment]
### Merge activity

* **Feb 20, 7:29 PM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.
* **Feb 20, 7:29 PM EST**: A user added this pull request to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc).
