### PR TITLE
fix(lower): avoid stack overflow during expression visit

### LINKED ISSUE #396: Avoid stack overflow during binary expression visiting
We need to use the heap for this instead of visiting recursively.

Current visitors include:
* ast lower
* minifying printer

### PR DESCRIPTION
**Pull request by Boshen**
closes #396

### CODE REVIEW

**Comment by MichaReiser** [comment]
I'm surprised that this isn't impacting performance more....

File: crates/oxc_ast_lower/src/lib.rs [hunk 1]
```diff
@@ -265,93 +273,105 @@ impl<'a> AstLower<'a> {
...
-            // Syntax trimmed for the following expressions
-            ast::Expression::TSAsExpression(expr) => self.lower_expression(&expr.expression),
-            ast::Expression::TSSatisfiesExpression(expr) => self.lower_expression(&expr.expression),
-            ast::Expression::TSNonNullExpression(expr) => self.lower_expression(&expr.expression),
-            ast::Expression::TSTypeAssertion(expr) => self.lower_expression(&expr.expression),
-            ast::Expression::TSInstantiationExpression(expr) => {
-                self.lower_expression(&expr.expression)
-            }
-        }
+        ensure_sufficient_stack(|| {
```
Comment (MichaReiser) [inline crates/oxc_ast_lower/src/lib.rs:276]: Would it be sufficient to only call into this for expressions that support nesting?

Comment (Boshen) [reply crates/oxc_ast_lower/src/lib.rs:276]: I don't think so, rustc does this on the whole expr.

It is probably due to condition + binary + paren expresions can nest over each other during recursion.
