### PR TITLE
fix(linter): fix no-fallthrough rule, when the default condition is not last

### LINKED ISSUE #12793: linter: no-fallthrough has different from eslint
### What version of Oxlint are you using?

1.9.0

### What command did you run?

_No response_

### What does your `.oxlintrc.json` config file look like?

```jsonc
{
  "no-fallroughness": "error"
}
```

### What happened?

When the code is as follows, oxlint will error, but eslint will not error.

```js
const a  = 'a';

switch(a) {
  case 'a':
  default:
    console.log('value is a or defualt');
    break;
  case 'b':
    console.log('value is b');
    break;
}
```

[oxlint playground](https://playground.oxc.rs/#eNp1kMFOwzAMhl8l8mWbNBAgcSnihnYFwbUXN3W7iDSunGRjqvruOK22C+IUO7Y///4nsFCB5RCTQWNezQY3L3WoQzy7ZI9b3JmpDsZYjFRqVUla6jD7tMRa0mH2dO+5325O6DMZFxXGUhoz+rTZKbK0NkL4vcQrr1l5/zGaP4Mz7IGhmkByKE+8hIQ/UCXJtAfvQrrG0fJIt+QyNOyvWRIMsWMZoOrQR5r3MKJEkkJE7/n8SSlLeM8pupYOOdjkWPet46OQ9p7oA4VCXH8VUZavCD2mc73aOtWq01OsoVIXIfCd7vPpKJz7Y/msgURYaphnUMRN2MpJKD3pQUDx6eHxWU93ahImat/IehQsqlTA9QjLLfW0+EIBG09fnMXSgONN5OCC69yCXwZCEvYHvbgMnUgajmraCiyCdDnGBPMvuyy8lQ==)

[eslint playground](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgYSAgPSAnYSc7XG5cbnN3aXRjaChhKXtcbiAgY2FzZSAnYSc6XG4gIGRlZmF1bHQ6XG4gICAgY29uc29sZS5sb2coJ3ZhbHVlIGlzIGEgb3IgZGVmdWFsdCcpO1xuICAgIGJyZWFrO1xuICBjYXNlICdiJzpcbiAgICBjb25zb2xlLmxvZygndmFsdWUgaXMgYicpO1xuICAgIGJyZWFrO1xufSIsIm9wdGlvbnMiOnsicnVsZXMiOnsibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXX0sImxhbmd1YWdlT3B0aW9ucyI6eyJzb3VyY2VUeXBlIjoibW9kdWxlIiwicGFyc2VyT3B0aW9ucyI6eyJlY21hRmVhdHVyZXMiOnt9fX19fQ==)

### PR DESCRIPTION
**Pull request by lambda47**
In the previous implementation, if the default condition was not the last one, the order of cfg_ids was incorrect

fixes #12793

### CODE REVIEW

**Comment by camc314** [comment]
thanks for the contribution, can we add a test case for this behaviour.

**Comment by lambda47** [comment]
I add the test case for it.

File: crates/oxc_linter/src/rules/eslint/no_fallthrough.rs [hunk 1]
```diff
@@ -482,6 +483,7 @@ fn get_switch_semantic_cases(
     } else {
         (None, exit)
     };
+    cfg_ids.sort_by_key(|cfg_id| nodes.iter().position(|it| it.cfg_id() == *cfg_id));
```
Comment (camc314) [inline crates/oxc_linter/src/rules/eslint/no_fallthrough.rs]: did the original solution of pushing cfg ids to a vec work? I think that solution is preferable as this could be pretty slow if cfg_ids is large, as it's going to have to loop over all nodes fo find the right one

Comment (lambda47) [reply crates/oxc_linter/src/rules/eslint/no_fallthrough.rs]: The original implementation, the order of cfg_ids is dependent on the order of edges returned by edges_directed function. It is dependent on the edges_directed’s internal implementation. I think it’s not good, but it quick. So I decide to use the original implementation.

Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_fallthrough.rs]: I think this is likely also why there's a perf regression

Comment (camc314) [reply crates/oxc_linter/src/rules/eslint/no_fallthrough.rs]: Screenshot 2025-08-10 at 12 40 46

**Review by camc314 — APPROVED** [review]
thanks!

**Review by camc314 — APPROVED** [review]
thank you!
