### PR TITLE
fix(codegen): escape `</script`

### LINKED ISSUE #10334: codegen: escape `</script`
We should pass these tests

https://github.com/oxc-project/oxc/blob/9533d09bbd2c3397202d2746bfbd6d0dc4dbacf1/crates/oxc_codegen/tests/integration/esbuild.rs#L1009-L1058

esbuild commits:

* Avoid generating the character sequence `</script>` https://github.com/evanw/esbuild/commit/5e749a2d763e36df43b249daac497b77bd17b141
* allow disabling escaping of </script> https://github.com/evanw/esbuild/commit/328ce1290d45cb8b54c2fcc89fcf7da3bfdbc3db

I thought this is easy before looking at the test cases - we need to handle strings, templates, comments and regexes as well as disabling this feature.

This is what I have written so far:

```diff
diff --git a/crates/oxc_codegen/src/str.rs b/crates/oxc_codegen/src/str.rs
index af68886a2..4c24b5841 100644
--- a/crates/oxc_codegen/src/str.rs
+++ b/crates/oxc_codegen/src/str.rs
@@ -338,6 +338,7 @@ enum Escape {
     LS = 14, // LS/PS - U+2028 LINE SEPARATOR or U+2029 PARAGRAPH SEPARATOR (first byte)
     NB = 15, // NBSP  - Non-breaking space (first byte)
     LO = 16, // �     - U+FFFD lossy replacement character (first byte)
+    LT = 17, // <     - Less-than sign
 }
 
 /// Struct which ensures content is aligned on 128.
@@ -357,7 +358,7 @@ static ESCAPES: Aligned128<[Escape; 256]> = {
         NU, __, __, __, __, __, __, BE, BK, __, NL, VT, FF, CR, __, __, // 0
         __, __, __, __, __, __, __, __, __, __, __, ES, __, __, __, __, // 1
         __, __, DQ, __, DO, __, __, SQ, __, __, __, __, __, __, __, __, // 2
-        __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, // 3
+        __, __, __, __, __, __, __, __, __, __, __, __, LT, __, __, __, // 3
         __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, // 4
         __, __, __, __, __, __, __, __, __, __, __, __, BS, __, __, __, // 5
         BQ, __, __, __, __, __, __, __, __, __, __, __, __, __, __, __, // 6
@@ -382,7 +383,7 @@ type ByteHandler = unsafe fn(&mut Codegen, &mut PrintStringState);
 ///
 /// Function pointers are 8 bytes each, so `BYTE_HANDLERS` is 128 bytes in total.
 /// Aligned on 128, so occupies a pair of L1 cache lines.
-static BYTE_HANDLERS: Aligned128<[ByteHandler; 16]> = Aligned128([
+static BYTE_HANDLERS: Aligned128<[ByteHandler; 17]> = Aligned128([
     print_null,
     print_bell,
     print_backspace,
@@ -399,6 +400,7 @@ static BYTE_HANDLERS: Aligned128<[ByteHandler; 16]> = Aligned128([
     print_ls_or_ps,
     print_non_breaking_space,
     print_lossy_replacement,
+    print_less_than,
 ]);
 
 /// Call byte handler for byte which needs escaping.
@@ -574,6 +576,29 @@ unsafe fn print_dollar(codegen: &mut Codegen, state: &mut PrintStringState) {
     }
 }
 
+// <
+unsafe fn print_less_than(codegen: &mut Codegen, state: &mut PrintStringState) {
+    dbg!("in");
+    debug_assert_eq!(state.peek(), Some(b'<'));
+    // SAFETY: Next byte is <, which is ASCII.
+    unsafe { state.consume_byte_unchecked() };
+
+    if state.peek() == Some(b'/') {
+        let slice = state.bytes.as_slice();
+        if slice.len() >= 7 {
+            for (i, c) in "script".bytes().enumerate() {
+                let d = slice[i + 1];
+                if c != d.to_ascii_lowercase() {
+                    return;
+                }
+            }
+            // SAFETY: Next byte is `/`, which is ASCII
+            unsafe { state.flush_and_consume_byte(codegen) };
+            codegen.print_str("\\/");
+        }
+    }
+}
+
 // 0xE2 - first byte of <LS> or <PS>
 unsafe fn print_ls_or_ps(codegen: &mut Codegen, state: &mut PrintStringState) {
     debug_assert_eq!(state.peek(), Some(0xE2));
```

### PR DESCRIPTION
**Pull request by xu-cheng**
Fixes #10334.

Replace #10340 to cover the escape for both template literals and comments. We don’t need to handle regex, which is already covered by existing codegen. 

Please let me know anything needed to merge this PR. Thanks.

### CODE REVIEW

**Comment by overlookmotel** [comment]
Thanks very much for doing this! I'm tied up next few days, but will endeavor to review (and hopefully merge) early next week.

File: crates/oxc_codegen/src/lib.rs [hunk 1]
```diff
@@ -230,6 +230,57 @@ impl<'a> Codegen<'a> {
...
+            i += 1;
+        }
+
+        // SAFETY:
+        // The slice guarantees to be a valid UTF-8 string.
+        // The consumed index is always pointed to a UTF-8 char boundary.
+        unsafe {
+            self.code.print_bytes_unchecked(&slice[consumed..]);
+        }
+    }
```
Comment (overlookmotel) [inline crates/oxc_codegen/src/lib.rs]: Much of the logic in this function is repeated in `print_less_than`. Can we have a shared function called something like `is_script_close_tag` which both functions use, rather than repeating the code twice?

Comment (xu-cheng) [reply crates/oxc_codegen/src/lib.rs]: Done.

File: crates/oxc_codegen/src/str.rs [hunk 2]
```diff
@@ -696,3 +722,20 @@ unsafe fn print_lossy_replacement(codegen: &mut Codegen, state: &mut PrintString
...
+    if slice.len() == 8 {
+        // Compiler condenses these operations to an 8-byte read, u64 AND, and u64 compare.
+        // https://godbolt.org/z/oGG16fK6v
+        let mut slice: [u8; 8] = slice.try_into().unwrap();
+        for b in slice.iter_mut().skip(2) {
+            // `| 32` converts ASCII upper case letters to lower case.
+            *b |= 32;
+        }
+
+        slice == *b"</script"
```
Comment (overlookmotel) [inline crates/oxc_codegen/src/str.rs:737]: Nice! You shaved a branch off my version.

**Review by overlookmotel — APPROVED** [review]
Thank you!

-2% on codegen benchmarks, which isn't surprising given the extra checks. I'll try to optimize it a little in a follow-up.
